### ISSUE TITLE
Open Existing Files from Local or URL

### ISSUE THREAD

**Issue by benjamenharper** [coleam00/bolt.new-any-llm#102]
The original bolt.new allows a user to open exiting projects via url such as: https://bolt.new/~/githubusername/reponame

The critical feature is to find any method to allow user to edit pre existing code via bolt.  

I don't care if it's through the url or through local file system or both.

I have started working on this for myself, but I would be excited to see this handled by core contributors.

**Comment by Toolbox-AI** [comment]
#27
