### ISSUE TITLE
Langgraph AGI

### ISSUE THREAD

**Issue by rezzie-rich** [coleam00/bolt.new-any-llm#116]
**Is your feature request related to a problem? Please describe:**

After closely observing agentic developers like opendevin and recent swebench verified score of sonnet3.5+tools(no agent), it's clear that agents sometimes over complicate the task resulting worse performance (Sonnets scores highest on verified list beating all agents)

**Describe the solution you'd like:**

Instead of having multiple agents running in the background, there should be only 1 agent(with possible subagents) working as the intermediary between bolt and the llm using langchain-openai-api-bridge. This way, the agent will serve only one purpose, which is to increase the general performance of the llm. This will also improve the quality of small llms.

**Describe alternatives you've considered:**

There could be multiple sets of intermediate agents that users can choose, i.e., COT, reflection, etc. Different mindmaps could be more effective for different models. 

**Additional context:**

https://www.swebench.com/

**Comment by chrismahoney** [comment]
Without me stumbling out of my comfort zone about LLM interactions, I'm not sure if a single agent serving as a bridge to Bolt is a valid constraint when multiple agents in a voting circle could potentially be used/necessary for things like useful code reviews inline, etc. - This is a good conversation worth having though and I'd love to get more context.
