### ISSUE TITLE
Let's tag these issues! 🫡

### ISSUE THREAD

**Issue by chrismahoney** [coleam00/bolt.new-any-llm#121]
**Is your feature request related to a problem? Please describe:**

I'd like to help establish some issue labels for this repo in order to triage and route bugs, enhancements, etc.

**Describe the solution you'd like:**

Labels! for Issues!

**Describe alternatives you've considered:**

Not organizing the issues at all. That is low energy, sad. 🤣

**Additional context:**

Action item out of this issue that could close it would be to quickly agree on common labels to use and when, if anyone has a go-to strategy there I'd be happy to start tagging. Just got pulled away but I'll suggest a set later if need be.

**Comment by hillct** [comment]
Similarly, we need a project roadmap (document) where features can b prioritized, and possibly an alternate forum like a discord server where trivial issues like onboarding can be addressed rather than having github issues being opened for howto related problems.
