### ISSUE TITLE
Error: write EOF

### ISSUE THREAD

**Issue by schilling3003** [coleam00/bolt.new-any-llm#123]
### Describe the bug

I have installed Node.js (v20.15.1) and pnpm (v9.4.0). After cloning the git and running pnpm install I don't get any errors. But when I try to run the development server I get the error below. I have tries this on a clean install of Windows and continue to get the same error.

> bolt@ dev F:\bolt.new
> remix vite:dev

Error: write EOF
    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:95:16)
    at WriteWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
  errno: -4095,
  code: 'EOF',
  syscall: 'write'
}
 ELIFECYCLE  Command failed with exit code 1.

### Link to the Bolt URL that caused the error

NA

### Steps to reproduce

1. Clone Github
2. Run pnpm install
3. pnpm run dev

### Expected behavior

The development server to run

### Platform

-OS: Windows 11

**Comment by hillct** [comment]
I haven't been able to reproduce this. Might it be a permissions issue in your case?  Does the issue occur when running from a command prompt running as Administrator?

**Comment by darkflare** [comment]
Same error.

Clean Windows Installation.
Node.js (v23.2.0) and pnpm (v9.13.2).

Steps to reproduce:
    Clone Github
    Run pnpm install
    pnpm run dev

(command prompt running as Administrator)

ERROR:
```
PS F:\AILLM\bolt.new-any-llm> pnpm run dev

> bolt@ dev F:\AILLM\bolt.new-any-llm
> remix vite:dev

Error: write EOF
    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:87:19)
    at WriteWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
  errno: -4095,
  code: 'EOF',
  syscall: 'write'
}
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by ErkoMd** [comment]
The same issue for me

**Comment by jinyun** [comment]
The same issue for me
