### ISSUE TITLE
Bolt stuck because create-next-app is waiting a response

### ISSUE THREAD

**Issue by mangandini** [coleam00/bolt.new-any-llm#129]
### Describe the bug

I ran a sample prompt and bolt executed the first command:

Run command
`npx create-next-app@latest youtube-clone --typescript --tailwind --eslint --app --src-dir --import-alias "@/*" && cd youtube-clone && npm install @heroicons/react date-fns`

Bolt get stuck over this because the create next app command is waiting for a response

Console reads:
`[2K[1G? Would you like to use Turbopack for next dev? › No / Yes`

There is no way to input a response

### Link to the Bolt URL that caused the error

http://127.0.0.1:3000/

### Steps to reproduce

- Start the development server or build the app
- Run this prompt
```
> Build a YouTube clone with a modern UI using Next.js, TypeScript, App Router, and Tailwind CSS. Include core features:
> 
> 1. Video grid layout with thumbnails and metadata 2. Video player page with title, description, and comments 3. Search functionality 4. Responsive design for mobile/desktop 5. Dark mode support 6. Video categories/filters 7. View count and timestamp display Use the following command to create the project:
> After setup, implement the features step-by-step, focusing on clean code architecture and best practices for Next.js and TypeScript.[object Object][object Object]
```

Bolt will return this

> Certainly! I'll create a YouTube clone with the features you've requested using Next.js, TypeScript, App Router, and Tailwind CSS. Let's set up the project and implement the features step-by-step.
> 
> 
> YouTube Clone with Next.js, TypeScript, and Tailwind CSS
> Click to open Workbench
> 
> Run command
> npx create-next-app@latest youtube-clone --typescript --eslint --tailwind --app --src-dir --import-alias "@/*" --use-npm && cd youtube-clone && npm install @heroicons/react

### Expected behavior

Bolt must continue the process without waiting for an input

### Screen Recording / Screenshot

![64275](https://github.com/user-attachments/assets/9c2532da-e56c-4a7d-aed2-654e1e6e335e)

### Platform

- OS: MacOS
- Browser: Chrome Canary

**Comment by ruhrbaron** [comment]
Can confirm, redproducibly hangs for me too at this step when creating a Next App. I was able to circumvent this limitation by asking it to manually create the app in the prompt, avoiding ´create-next-app´:

```
Build a text-based role-playing game using Next.js, TypeScript, App Router, and Tailwind CSS. Include features like character creation, turn-based combat, inventory management, and a simple storyline. Implement state management for game progress and use server-side rendering for improved performance.

Avoid using ´create-next-app´ but create the required files and folder layout yourself instead.

**Comment by hillct** [comment]
Certainly the LLM should be calling these tools in a non-interactive mode, but alternatively, the (tool) prompt requiring user input should be displayed in the webContainer terminal where h user can respond to the waitig prompt, without having to reproduce the command entirely.

The solution is probably twofold:

1. prompt enginering
2. terminal integration within webContainers (to handle outliers gracefully)
