### ISSUE TITLE
Local Ollama -> Fetch localhost on front end.

### ISSUE THREAD

**Issue by lucticas** [coleam00/bolt.new-any-llm#133]
### Describe the bug

The front end makes a direct request to the Ollama endpoint at localhost:11434
This creates a problem when we run the front end on the web or on another machine outside of localhost.

### Link to the Bolt URL that caused the error

server:locallhost

### Steps to reproduce

clone, configure env. docker compose.
then make a revese proxy to docker .

### Expected behavior

expected the fetch request on container context, not front end context

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/e398f82f-3175-42fd-a14e-5e55512be2b1)
![image](https://github.com/user-attachments/assets/0da17a32-b068-4cd0-b64f-743f872cc064)

### Platform

docker so,

### Additional context

Dockerized bolt + docker ollama;
they both can acces each other  on docker network, but front end files at revese proxy tries to browser -> ip .

**Comment by hillct** [comment]
Simply specify he hostname in the .env/.env.local file. As you corrctly point out, you must specify a hostname that is accessibly from your proxy endpoint, so for example, if you're proxying to the WAN side of your firewall, and the Ollama host is on the LAN side, you'd ned to do some port forwarding, to get your ollama API to show up on the WAN side of your firewall on port 11434. It should also be noted, that you can launch your docker container with the parameter `--env_file .env.local` to force the environment to be populated if for some reason vite is trying to prioritize variable sources improperly, in your environment.

**Comment by lucticas** [comment]
![Screenshot_8](https://github.com/user-attachments/assets/f84eb17d-0434-4c36-8177-e64a8807d2bc)
![Screenshot_9](https://github.com/user-attachments/assets/cbb07bb3-5334-4fe3-aeb2-b3305a9cd62d)


Same, it corretly points to but cant load http,( with https CORS erros )

at docker container bash i can curl with no erros, there prob. be an frame work cors-https error.
![Screenshot_10](https://github.com/user-attachments/assets/c819207a-06f0-4307-a93b-de047d575eba)

**Comment by hillct** [comment]
Your screenshot itself contains the answer. Your bolt that new deployment is being provied, and served with a TLS certificate(HTTPS) and your ollama API endpoint is not. To make this successful you would need to proxy the llama endpoint providing a TLS certificate.

An alternative approach to resolving this issue would be to deliver a Coors security upgrade header exempting, the llama endpoint from the security check. Since this is fundamentally less secure, we need to consider more carefully the ramifications of this approach.

**Comment by lucticas** [comment]
![image](https://github.com/user-attachments/assets/40bf4438-4dba-4ea5-b949-b3700eb12645)
both serverd on https ollama endpoint + bolt

**Comment by aaronbolton** [comment]
I've had some luck with this, it not bolt which is the issue but rather the Ollama config, you need to set CORS Origins to 

OLLAMA_ORIGINS=*

**Comment by lucticas** [comment]
done, but its the same.

ollama served on nginx https = works alone.
ollama on localhost/docker network/ip local networks = works.

bolt ( on nginx) - works but when tries to get ollama :
1.http = on docker network  = error "must be https".
2. https  = over 'internet' cors ( event with OLLAMA_ORIGINS=* in enviroment) .

Ty all,  maybe in future.

**Comment by hillct** [comment]
There are essentially two approaches to this problem. The most secure would be to enable a local proxy URL for requests to Ollama such that the bolt server performs these requests on the back end and passes the results to the front end for rendering where the only problematic requests are in fact on the front end because that's the only case where you have mixed security content.

The less secure methodology would be to add, add a content security policy. Metatag to the pages where the Ollama model lists are being displayed for example: 
```html
<meta http-equiv="Content-Security-Policy" content="connect-src https: http://192.168.1.1:11434;">
```
Personally, I would favor the more secure methodology which to my way of thinking, only requires marginally more code than the insecure methodology.

**Comment by aaronbolton** [comment]
Could we use something like litellm to achieve this?

https://docs.litellm.ai

**Comment by hillct** [comment]
> Could we use something like litellm to achieve this?
> 
> https://docs.litellm.ai

Wow! That's pretty neat, it's way Overkill for what we need. Something as simple as this or even simpler would achieve the objective: 
https://www.npmjs.com/package/bouncy

All we need to do is map the endpoint to a local endpoint (part of the bolt server) like /ollama which would then route traffic to http:// 192.168.1.1: 11434

In this way we assure that we're using the same HTTPS/ http protocol and also avoid any cross-origin issues, although that's generally handled on the ollama endpoint side anyway.

**Comment by aaronbolton** [comment]
@hillct, thanks for this. It does appear to be much simpler. I've been having a play around with this and got a very simple code snippet working, but I'm well outside my comfort zone. Could you assist if you're able to help implement this into the project?

below is what I have up to now.

```
require('dotenv').config({ path: '.env.local' });

const bouncy = require('bouncy');

const targetHost = process.env.OLLAMA_TARGET_HOST || 'localhost';
const targetPort = process.env.OLLAMA_TARGET_PORT || 11434;

// Log the environment variables
console.log(`Target Host: ${targetHost}`);
console.log(`Target Port: ${targetPort}`);

const server = bouncy((req, res, bounce) => {
    try {
        bounce({
            host: targetHost,
            port: targetPort
        }).on('error', (err) => {
            res.statusCode = 502;
            res.end('Bad Gateway');
        });
    } catch (error) {
        res.statusCode = 500;
        res.end('Internal Server Error');
    }
});

server.listen(8000, () => {
    console.log('Server listening on port 8000');
});

// Handle server errors
server.on('error', (err) => {
    console.error('Server error:', err);
    process.exit(1);
});
```

**Comment by hillct** [comment]
> @hillct, thanks for this. It does appear to be much simpler. I've been having a play around with this and got a very simple code snippet working, but I'm well outside my comfort zone. Could you assist if you're able to help implement this into the project?

Happy to help, although it will not likely be in the next day or two. My first note would be to not separate the host and Port, but simply accept the single ollama endpoint URL and parse out the relevant data using new URL(process.env.OLLAMA_ENDPOINT_URL).host and .port

Is this in a branch we should be working from or just ad hoc for the moment?

> 
> below is what I have up to now.
> 
> ```
> require('dotenv').config({ path: '.env.local' });
> 
> const bouncy = require('bouncy');
> 
> const targetHost = process.env.OLLAMA_TARGET_HOST || 'localhost';
> const targetPort = process.env.OLLAMA_TARGET_PORT || 11434;
> 
> // Log the environment variables
> console.log(`Target Host: ${targetHost}`);
> console.log(`Target Port: ${targetPort}`);
> 
> const server = bouncy((req, res, bounce) => {
>     try {
>         bounce({
>             host: targetHost,
>             port: targetPort
>         }).on('error', (err) => {
>             res.statusCode = 502;
>             res.end('Bad Gateway');
>         });
>     } catch (error) {
>         res.statusCode = 500;
>         res.end('Internal Server Error');
>     }
> });
> 
> server.listen(8000, () => {
>     console.log('Server listening on port 8000');
> });
> 
> // Handle server errors
> server.on('error', (err) => {
>     console.error('Server error:', err);
>     process.exit(1);
> });
> ```

**Comment by aaronbolton** [comment]
No problem at all I didn't expect you to just jump on it 😀, yes a single variable sounds a lot better idea and yes it was just a bit of adhoc code I was running local not integrated with bolt I was just curling the local address to test

**Comment by Psxmaster83** [comment]
where i need add the code tell me the file and location pls ? cause i got same problem :S
