### ISSUE TITLE
Move from Bolt.new to Local Version

### ISSUE THREAD

**Issue by xenstar** [coleam00/bolt.new-any-llm#141]
**Is your feature request related to a problem? Please describe:**

Many of us will find this version, when our token is finished. 

**Describe the solution you'd like:**

There should be a clear and easy transition option, where we can download our bolt.new project, and continue working on local version which is created by you. 

Either we can upload the project on github, and then download from github to local version to continue.

**Comment by Toolbox-AI** [comment]
#27
