### ISSUE TITLE
Uploading the image to the prompt

### ISSUE THREAD

**Issue by PBemm69** [coleam00/bolt.new-any-llm#143]
### Describe the bug

I am not sure whether this is a bug or a feature not still available in the system. I tried to drop an image to the prompt but it was not working.  Just thought I will put it here so that you will not overlook that feature.

### Link to the Bolt URL that caused the error

N/A

### Steps to reproduce

N/A

### Expected behavior

Attachment of the image to the prompt

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

### Additional context

N/A

**Comment by santhiprakash** [comment]
Image upload option is not ready. It should be available in the next versions. That is one of the features in high priority.

**Comment by Mukulbaid63** [comment]
@santhiprakash I can work on it

**Comment by PBemm69** [comment]
This is excellent news!

**Comment by Mukulbaid63** [comment]
@coleam00 can you assign this issue to me?

**Comment by coleam00** [comment]
Sure thing, @Mukulbaid63! Thank you!

**Comment by manoj-lk-code** [comment]
It would be nice if we can add multiple attachment or folder or app that we have built on bolt.
