### ISSUE TITLE
Hey guys i think you must use devdocs Api for reference!

### ISSUE THREAD

**Issue by majidomri** [coleam00/bolt.new-any-llm#145]
**Is your feature request related to a problem? Please describe:**
Several time we used to see so many errors in bolt.new! 

**Describe the solution you'd like:**
To rectify those errors from code generation to production, we can set modules or apis to follow those standards for every stack. So that it will reduce the error generation.

**Describe alternatives you've considered:**
We can set a RAG Layer for everystack like **devdocs** to follow the instrucions from there!
this will make code generation and production error free!
please consider this repo for reference in our opensource bolt code generator.
here is the link below for reference and api:
https://github.com/freeCodeCamp/devdocs

**Additional context:**
if you have any quesiton you can drop the message!

**Comment by hillct** [comment]
This seems out of scope for a frontend like bolt.new. Cerainly, there is value in creating a RAG implementation around a projct like DevDocs or similar, but that seems like a secondary project, with which bolt.new might optionally integrate.  Of more concern, to me at least is the BOLD headline on the readme for the DevDocs project "**We are currently searching for **maintainers****"

Never a good idea to crate a dependency on an unmaintained project.
