### ISSUE TITLE
UI is like Web 2.0

### ISSUE THREAD

**Issue by faddy19** [coleam00/bolt.new-any-llm#15]
### Describe the bug

The UI is like Web 2.0 in 1995. I will add a screenshot of an example Pomodore App. 

### Link to the Bolt URL that caused the error

bolt.new

### Steps to reproduce

1. Give a prompt 
2. Start and get shocked

### Expected behavior

Beautiful UI like Next js and Apple

### Screen Recording / Screenshot

<img width="342" alt="Bildschirmfoto 2024-10-21 um 17 56 58" src="https://github.com/user-attachments/assets/4f6033a0-5fd3-4a04-aab7-57b8d387e78f">

**Comment by kofi-bhr** [comment]
hey! this is actually just a prompting thing :)

Try something like:

> Create a modern pomodoro timer with a sleek UI using Tailwind CSS. Make it look professional like Apple's design - clean, minimal, with proper spacing and subtle animations.

The more specific you are about design/styling, the better the output. Bolt can definitely do modern UIs, just needs the right prompts!

Let me know if you need any other prompting tips ✌️

**Comment by faddy19** [comment]
Thats not true. I tried these kinds of prompts still ugly. Try it on this local bolt not on the bolt.new site. So what is the reason for the ugly site?

**Comment by Prathamesh-Shanbhag** [comment]
+ 1 @faddy19 - This is not a prompting issue.
The model is unable to generate good UI's.

For now its focusing more on functionality rather than looking good.

If you ask it to make a landing page for some local business - It makes the worst layout and designs.
I was somehow hoping to improve this - But don't know how.

**Comment by faddy19** [comment]
Found this and it can solve the UI problem

https://x.com/nickadobos/status/1850017917628535090?s=46&t=VT70WICa668Q38QaXYKxGA

That is generating insanely good UIs

**Comment by Prathamesh-Shanbhag** [comment]
@faddy19 is it the same for the OS version? The video example on twitter is using the closed source version of bolt.new right?
I also wonder what parts did they choose to hide or remove to create the OS version?
