### ISSUE TITLE
bolt can't create files like index.html etc.

### ISSUE THREAD

**Issue by niboz** [coleam00/bolt.new-any-llm#151]
### Describe the bug

bolt can't create files like index.html etc.
![bolt-1](https://github.com/user-attachments/assets/625e8222-961b-4b41-b058-93ca2cffec59)

### Link to the Bolt URL that caused the error

#

### Steps to reproduce

start request and nothing happens

### Expected behavior

bolt can't create files like index.html etc.

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/af890926-e786-4d35-a0a6-976f968e33f4)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by niboz** [comment]
Platform
OS: [Linux]
Browser: [Chrome]
Version: [130.0.6723.92]

**Comment by ElG0hary** [comment]
which api used ?

**Comment by Aswinajay** [comment]
i am also facing the same issue, im using google api

**Comment by Aswinajay** [comment]
![Screenshot 2024-11-03 005433](https://github.com/user-attachments/assets/b79d00f1-ca79-44d6-81f1-cf40b8a16d53)

**Comment by blancmat** [comment]
Hello, exactly the same problem here, using openai api , impossible to make it work , no solution ?

**Comment by niboz** [comment]
Problem was: 
Failed to spawn shell
Failed to execute 'postMessage' on 'Worker': SharedArrayBuffer transfer requires self.crossOriginIsolated.

Solution:
I have installed bolt on a linux vm where no browser or desktop is installed and where is running on a different server. When bolt url is called from another client browser the error ‘Failed to spawn shell’ occurs because the SharedArrayBuffer is used, which requires certain security conditions for cross-origin isolation.
For solving this issue, I have installed WSL on my Windows-pc and installed bolt on WSL.
after installation of Bolt on WSL is Bolt callable with http://localhost:<port> and this error no longer occurs

**Comment by hknerdr** [comment]
> Problem was: Failed to spawn shell Failed to execute 'postMessage' on 'Worker': SharedArrayBuffer transfer requires self.crossOriginIsolated.
> 
> Solution: I have installed bolt on a linux vm where no browser or desktop is installed and where is running on a different server. When bolt url is called from another client browser the error ‘Failed to spawn shell’ occurs because the SharedArrayBuffer is used, which requires certain security conditions for cross-origin isolation. For solving this issue, I have installed WSL on my Windows-pc and installed bolt on WSL. after installation of Bolt on WSL is Bolt callable with http://localhost: and this error no longer occurs

I am using google cloud console ec2 i am getting same error.
what should i do?

**Comment by mpisat** [comment]
I have the same issue.
Failed to spawn bolt shell

Failed to execute 'postMessage' on 'Worker': SharedArrayBuffer transfer requires self.crossOriginIsolated.

using XAI - Grok beta
