### ISSUE TITLE
Using Ollama makes the response like any other AI model, instead of populating the project

### ISSUE THREAD

**Issue by ameetqyrus** [coleam00/bolt.new-any-llm#152]
### Describe the bug

The response is on chat like any other AI model instead of building project.

### Link to the Bolt URL that caused the error

localhost://5173

### Steps to reproduce

1. Setup Bolt
2. Select Ollama and CodeLlama:7B
3. Prompt
4

### Expected behavior

The project needs to be built instead of general response like any other model. 

### Screen Recording / Screenshot

<img width="1060" alt="image" src="https://github.com/user-attachments/assets/051cc018-debc-45bc-9510-430695d8eaa2">
<img width="1703" alt="image" src="https://github.com/user-attachments/assets/9cd7898f-aa12-4bc9-9896-23d1f29fea25">

### Platform

- Macos Sequioa
- Chrome
- 130.0.6723.70 (Official Build) (arm64)

**Comment by Archviz360** [comment]
i have same problem here. it also not saving the chat.

**Comment by ElG0hary** [comment]
same here

**Comment by ElG0hary** [comment]
> i have same problem here. it also not saving the chat.

it does save, if u noticed it shows like that in link like /chat1 or /chat2 so on

**Comment by Archviz360** [comment]
@ElG0hary yes i saw it. now how do io get it to create the main files in the editor. right now it works like any chat bot for me but it doesnt add content to the editor.

**Comment by ElG0hary** [comment]
if using Ollama, it does have this bug with ollama only, try to use any other API and it would works fine

**Comment by Archviz360** [comment]
@ElG0hary isthere free api without limits?

**Comment by the0ckid82** [comment]
some what of a work around that works "most of the time" start your project and after you submit your first message stop it right away. click the code button to open the editor and then resubmit your first message. Cole mentioned this in one of his YT videos  [Cole mentioned this in one of his YT videos](https://youtu.be/p1YvKuRfEhg?t=761)

**Comment by ElG0hary** [comment]
**### Solved**:
Create a file name Modelfile (no file extension)
then open it with notepad and paste this:
```
FROM llama3.2:latest
PARAMETER num_ctx 32768
```

change only the model name as what u are using.
after that open cmd
and use this command 
`ollama create -f Modelfile bolt.new-Ollama`
**Note:** _bolt.new-Ollama is the new model you are gonna choose when using it with your locale Bolt.new so dont choose regular ollama 3.2b_

**Reason for not working to begin with:** Difference between Context window between ollama and other models.
