### ISSUE TITLE
can you make this compatible with php and mysql to create plugins for wordpress?

### ISSUE THREAD

**Issue by incodexss** [coleam00/bolt.new-any-llm#157]
Can you make this compatible with PHP and MySQL to create plugins for WordPress?

It would be great if we could create plugins for wordpress to use on our websites

**Comment by iServU** [comment]
Hi,

Wondering if this issue was closed completed or closed dismissed? I think it would be invaluable in opening new avenues for Bolt.diy adoption to allow the creation of PHP based web apps. 

Thanks for all the hard work regardless of whether this gets into the pipeline or not :-)
