### ISSUE TITLE
How can I add a Perplexity API Key in .env.local? 

### ISSUE THREAD

**Issue by achimghita** [coleam00/bolt.new-any-llm#183]
Not sure what I need to write here: OPENAI_LIKE_API_BASE_URL=??? Tried without any success https://api.perplexity.ai and https://api.perplexity.ai/chat/completions 

How about for Grok?

**Comment by felipe2g** [comment]
Do you need to use this branch until get merged: meetpateltech:pplx-models

Please, test and coment on this pr for increase merge speed :)

https://github.com/coleam00/bolt.new-any-llm/pull/97
