### ISSUE TITLE
will not create file sometimes and puts code in chat no matter how you prompt 

### ISSUE THREAD

**Issue by bantzclan** [coleam00/bolt.new-any-llm#185]
### Describe the bug

so after a while running it will for some reason glitch out and start putting the code within the chat space rather than creating a file, you can make a prompt to remind it and tell it it did wrong, it responds agreeing but still puts the code within the chat box 

### Link to the Bolt URL that caused the error

http://localhost:5173/chat/

### Steps to reproduce

happens randomly 

### Expected behavior

for it to actually make the file

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by Psxmaster83** [comment]
yeah i can confirm it´s buggy often :3
