### ISSUE TITLE
Support for github new markplace llm models api key 

### ISSUE THREAD

**Issue by TUX-A1CUA0** [coleam00/bolt.new-any-llm#186]
There is like a recently new github marketplace models that has free api key to gpt4o are you guys like planning to add it in  this project

**Comment by nandan121** [comment]
It can be done using OPENAI_LIKE... , but be careful as model names duplicated is not handled in the application currently. I would suggest you comment out OPENAI_API_KEY and do the testing. 

See https://github.com/coleam00/bolt.new-any-llm/issues/184
