### ISSUE TITLE
liteLLM issue

### ISSUE THREAD

**Issue by nushret** [coleam00/bolt.new-any-llm#189]
### Describe the bug

liteLLM is installed on my windows local machine. and I can access it with the link http://localhost:4000.

I added this to the .env file as below. 

OPENAI_LIKE_API_BASE_URL=http://localhost:4000

I see the model in the OpenAILike section of the models, but when I type prompt. I get the following error.

Messages: [ [Object] ],
    vehicles: undefined,
    tool_choice: undefined,
    flow: right
  },
  statusCode: 401,
  responseHeaders: {
    'cf-cache-status': 'DYNAMIC',
    'cf-ray': '8de466b78e69ca29-OTP',
    connection: 'keep-alive',
    'content-length': '97',
    'content-type': 'application/json',
    date: 'Wed, 06 Nov 2024 10:29:13 GMT',
    'request-id': 'req_017a4hYd66XdNsKbTKkkcRAjx',
    server: “cloudflare”,
    via: '1.1 google',
    'x-robots-tag': 'none',
    'x-should-retry': 'false'
  },
  responseBody: '{“type”: “error“, ‘error’:{”type": “authentication_error”, ‘message’: “x-api-key header is required"}}',
  isRetryable: false,
  Data: {
    type: 'error',
    Error: {
      tip: 'authentication_error',
      message: 'x-api-key header required'
    }
  },
  [Symbol(vercel.ai.error)]: true,
  [Symbol(vercel.ai.error.AI_APICallError)]: true
}

### Link to the Bolt URL that caused the error

http://localhost:5173/

### Steps to reproduce

iteLLM is installed on my windows local machine. and I can access it with the link http://localhost:4000.

I added this to the .env file as below. 

OPENAI_LIKE_API_BASE_URL=http://localhost:4000

I see the model in the OpenAILike section of the models, but when I type prompt. I get the following error.

### Expected behavior

How do I connect to openAILike url without auth?

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by nandan121** [comment]
I think if you set the KEY it should work, the KEY should not be blank. I could get it working. Be careful to use a model name that is unique else use
[TommyHolmberg:respect-provider-choice
](https://github.com/TommyHolmberg/bolt.new-any-llm/tree/respect-provider-choice)


#testing Litellm
OPENAI_LIKE_API_BASE_URL=http://0.0.0.0:4000
# Get your OpenAI Like API Key
OPENAI_LIKE_API_KEY=doesnotmatter

**Comment by ank-it07** [comment]
@nandan121 just running in virtual env made the suggested changes but getting the same error, 
![image](https://github.com/user-attachments/assets/fd156848-0913-4bf2-85f8-755574bec857)
![image](https://github.com/user-attachments/assets/e5ea290d-3f3e-49b4-b64c-937405562962)

**Comment by ank-it07** [comment]
Thanks @nandan121 
tried your suggestion "litellm --config config.yaml --detailed_debug" , my API_KEY was empty, fixed it.

**Comment by Digitl-Alchemyst** [comment]
@nushret Does this fix your issue as well?

**Comment by nandan121** [comment]
> my .env
> 
> # You only need this environment variable set if you want to use OpenAI Like models
> OPENAI_LIKE_API_BASE_URL=http://127.0.0.1:4000
> 
> # Get your OpenAI Like API Key
> OPENAI_LIKE_API_KEY=

put

OPENAI_LIKE_API_KEY=dsdfsadad

and it should work
**You should not leave it empty**, though it does not matter what you put. UNLESS you have set the api key in litellm .env as
LITELLM_MASTER_KEY=sk-34....

**Comment by Digitl-Alchemyst** [comment]
@nushret tag me when you get to try this out after setting your .env file as @nandan121 has suggested. 
the open AI like key cannot be blank enough though its value does not matter. 
Basically, it still needs an API key, you just make up your own and provide it through the .env file.
I will give this another try this afternoon myself and make double sure to repeat every step I can as per your details.
