### ISSUE TITLE
Ollama over internet problem

### ISSUE THREAD

**Issue by Psxmaster83** [coleam00/bolt.new-any-llm#191]
### Describe the bug

then i use ollama locally it shows my model then i wanna use it over the internet it´s empty 

### Link to the Bolt URL that caused the error

https://github.com/coleam00/bolt.new-any-llm/

### Steps to reproduce

i started server in docker mode

### Expected behavior

i want that it gonna work over the internet too so i can use it anywhere with phone over the internet then my server running at home

### Screen Recording / Screenshot

the first screenshot shows ollama in localhost
![ollama localhost](https://github.com/user-attachments/assets/4202686e-c2c7-4215-b9f1-aa63ffccbc86)
that screenshot shows ollama over the internet ip it´s empty :(
![ollama over inet](https://github.com/user-attachments/assets/ecca4e82-a4db-47e2-94d3-fb14c5b87fe5)

### Platform

- OS:   [Windows 11]
- Browser: [Firefox]
- Version: [Latest]

### Additional context

maybe someone can fix the problem idk what to do it´s strange i think something wrong with the config or so idk i not an expert i use latest code with docker

**Comment by lucticas** [comment]
check this [https://github.com/coleam00/bolt.new-any-llm/issues/133](https://github.com/coleam00/bolt.new-any-llm/issues/133)

**Comment by Psxmaster83** [comment]
first i wanna say thx for help  <3 i check the link but i not understand what need to change where i need put that code what file i need to change and yes this is the same problem i get here ???

require('dotenv').config({ path: '.env.local' });

const bouncy = require('bouncy');

const targetHost = process.env.OLLAMA_TARGET_HOST || 'localhost';
const targetPort = process.env.OLLAMA_TARGET_PORT || 11434;

// Log the environment variables
console.log(`Target Host: ${targetHost}`);
console.log(`Target Port: ${targetPort}`);

const server = bouncy((req, res, bounce) => {
    try {
        bounce({
            host: targetHost,
            port: targetPort
        }).on('error', (err) => {
            res.statusCode = 502;
            res.end('Bad Gateway');
        });
    } catch (error) {
        res.statusCode = 500;
        res.end('Internal Server Error');
    }
});

server.listen(8000, () => {
    console.log('Server listening on port 8000');
});

// Handle server errors
server.on('error', (err) => {
    console.error('Server error:', err);
    process.exit(1);
});

**Comment by thecodacus** [comment]
its working for me.
can you clarify below points

- Bolt running on (local host/docker)?:
- Ollama running on (local host /docker)?:
- content of docker run command or compose file used to start the container?:
