### ISSUE TITLE
Add online free models

### ISSUE THREAD

**Issue by lucticas** [coleam00/bolt.new-any-llm#192]
[**Is your feature request related to a problem? Please describe:**
no

Add free models 
**Describe the solution you'd like:**
a list of working free models on internet

**Describe alternatives you've considered:**

**Additional context:**
like this ->>> (https://bolt.myaibuilt.app/) <<--- list here.

]

**Comment by bantzclan** [comment]
> [**Is your feature request related to a problem? Please describe:** no
> 
> Add free models **Describe the solution you'd like:** a list of working free models on internet
> 
> **Describe alternatives you've considered:**
> 
> **Additional context:** like this ->>> (https://bolt.myaibuilt.app/) <<--- list here.
> 
> ]
the problem is with the link you shared, that system is not creating and coding the files its basically just acting like a chat bot and not doing as it should

**Comment by schilling3003** [comment]
> > [**Is your feature request related to a problem? Please describe:** no
> > Add free models **Describe the solution you'd like:** a list of working free models on internet
> > **Describe alternatives you've considered:**
> > **Additional context:** like this ->>> (https://bolt.myaibuilt.app/) <<--- list here.
> > ]
> > the problem is with the link you shared, that system is not creating and coding the files its basically just acting like a chat bot and not doing as it should

That depends on the LLM used. With llama 3.1 405b and 8k context it worked. The main issue here is context window and even if it works, it's 8k is definitely going to hinder it.
