### ISSUE TITLE
Bolt Local Web Container Issue

### ISSUE THREAD

**Issue by nextdoormarketing** [coleam00/bolt.new-any-llm#193]
### Describe the bug

Hello Bolt community!

I just setup Bolt locally in Docker. All settings are default. I tried to wipe and reload a few times and keep getting this when loading into a project. Any ideas what I can do to fix this? I really appreciate any help you can provide. Thanks in advance!

Failed to spawn shell

Failed to execute 'postMessage' on 'Worker': SharedArrayBuffer transfer requires self.crossOriginIsolated.

### Link to the Bolt URL that caused the error

http://localhost:5173/chat/todo-app

### Steps to reproduce

1. go to the homepage of the app.
2. Choose LLM (Tried Groq Llama 3.1 70b, Mistrial 7B and Mistrial Large Latest)
3. Tried any example option at the bottom. (Build a todo app in React using Tailwind)
4. When redirected to the project, it tries to start, but all actions have an X or just keeps loading. On the right, when I toggle the terminal I get the error that shows the issue.

### Expected behavior

Start creating the files and show an example app on the right side.

### Platform

- OS: [Windows 10 Client] Server [Ubuntu Server 20.04.6 LTS, Docker version 27.3.1,build ce12230] 
- Browser: [Chrome]

### Additional context

![chrome_Kk4eIvWQhm](https://github.com/user-attachments/assets/4aaeb2fd-0887-47f2-a39c-f503bf095202)
![chrome_U9UJljgJUr](https://github.com/user-attachments/assets/8250066b-3db6-4141-a42d-f4cc78a13696)

**Comment by neilyboy** [comment]
I am getting exact same thing on a fresh install of ubuntu server 24.04.1
Have tried in Firefox Version 132.0.1 (64-bit)
Chrome Canary Version 132.0.6821.0 (Official Build) canary (64-bit)

![image](https://github.com/user-attachments/assets/9b1a19a5-6ec6-4f79-9680-4f82dd581488)

**Comment by nextdoormarketing** [comment]
Thank you for the quick reply for both of you. I was using Chrome and now tried Firefox but had the same error with this...Note I don't have SSL enabled yet.
![firefox_hME9pAl68M](https://github.com/user-attachments/assets/7773f0ec-61b4-46d1-9b9a-2dac796480b3)
![firefox_YTlX7oU5Dm](https://github.com/user-attachments/assets/0d46ced4-e5d7-40e4-88cc-5b451bb5ab63)

**Comment by nextdoormarketing** [comment]
Does anyone else notice this with a non SSL version? 

I actually searched this and checked other LLM's such as Claude and got this response but after implimenting this it did not resolve either.

The error message provides context. The issue you're facing is related to the Vite development server not properly configuring the necessary CORS (Cross-Origin Resource Sharing) headers for SharedArrayBuffer usage.

To resolve this, you'll need to update your Vite configuration and potentially add a custom middleware to your development server. Here's what you can do:

1. In your `vite.config.ts` file, add the following configuration:

```typescript
export default defineConfig({
  server: {
    headers: {
      'Cross-Origin-Opener-Policy': 'same-origin',
      'Cross-Origin-Embedder-Policy': 'require-corp',
    },
  },
  // rest of your Vite configuration
});
```

This will ensure that the Vite development server sends the necessary CORS headers to enable SharedArrayBuffer usage.

2. Additionally, create a new file called `server-middleware.js` in the root of your project and add the following code:

```javascript
export function securityMiddleware(req, res, next) {
  res.setHeader('Cross-Origin-Opener-Policy', 'same-origin');
  res.setHeader('Cross-Origin-Embedder-Policy', 'require-corp');
  next();
}
```

3. Then, in your `vite.config.ts` file, import and use the `securityMiddleware` function:

```typescript
import { defineConfig } from 'vite';
import { securityMiddleware } from './server-middleware';

export default defineConfig({
  server: {
    middlewareMode: 'html',
    middleware: [
      securityMiddleware,
    ],
    headers: {
      'Cross-Origin-Opener-Policy': 'same-origin',
      'Cross-Origin-Embedder-Policy': 'require-corp',
    },
  },
  // rest of your Vite configuration
});
```

This will apply the necessary CORS headers to the Vite development server's responses.

After making these changes, try restarting your development server. The `SharedArrayBuffer` error should be resolved, and you should be able to continue working on your Bolt.new application.

**Comment by neilyboy** [comment]
You ever find a way around this? ill try bare metal install I guess.

**Comment by nextdoormarketing** [comment]
I think it requires an SSL certificate to use but will confirm later or tomorrow. 
I see your running on bare metal. I'm in docker but it does not matter the environment in most cases. We are also both on Ubuntu server and extremely close versions. 
I will let you know either way.

**Comment by radumalica** [comment]
It will not work only with SSL cert. The serving web server for the application must send the CORS headers when WebContainers are called, otherwise you get that error. What i ended up doing is :
- deployed a standalone Traefik server with docker compose, having all Cors headers configured, letsencrypt etc
- added labels to current docker-compose.yaml for "bolt-ai production" to use the Traefik ingress controller. 

This is how my docker-compose looks now:

`services:
  bolt-ai:
    image: bolt-ai:production
    build:
      context: .
      dockerfile: Dockerfile
      target: bolt-ai-production
    ports:
      - "5173"
    env_file: ".env"
    labels:
      traefik.enable: true
      traefik.http.routers.bolt.rule: Host(`bolt.hostname.here`)
      traefik.http.routers.bolt.entrypoints: https
      traefik.http.routers.bolt.tls.certresolver: letsencrypt
      traefik.http.routers.bolt.middlewares: corsHeader
      traefik.http.services.bolt.loadbalancer.server.port: 5173`

and here is my standalone traefik ingress:

`volumes:
  traefik-ingress:
services:
  traefik-ingress:
    image: traefik
    restart: unless-stopped
    command:
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"
      - "--accesslog=true"
      - "--providers.docker"
      - "--providers.docker.exposedByDefault=false"
      - "--certificatesresolvers.letsencrypt.acme.email=tox2k4@gmail.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=/data/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge.delaybeforecheck=10"
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge.resolvers=1.1.1.1:53,8.8.8.8:53"
      - "--entrypoints.https.http.tls.certResolver=letsencrypt"
      - "--entrypoints.https.http.tls.domains[0].main=your_domain.com"
      - "--entrypoints.https.http.tls.domains[0].sans=*.your_domain.com"
      - "--serversTransport.insecureSkipVerify=true"
      - "--global.sendAnonymousUsage=false"
      - "--api.dashboard=true"
      - "--api.insecure=false"
    labels:
      traefik.enable: true
      traefik.http.middlewares.redirect-to-https.redirectscheme.scheme: https
      traefik.http.routers.redirs.entrypoints: http
      traefik.http.routers.redirs.middlewares: redirect-to-https
      traefik.http.routers.redirs.rule: hostregexp(`{host:.+}`)
      traefik.http.middlewares.dashboard-auth.basicauth.users: "admin:do_a_bcrypt_hash_here_of_your_password"

      traefik.http.routers.traefik-dashboard.rule: "Host(`dashboard.your.host`)"
      traefik.http.routers.traefik-dashboard.service: api@internal
      traefik.http.routers.traefik-dashboard.middlewares: dashboard-auth
      traefik.http.routers.traefik-dashboards.entrypoints: "https"
      traefik.http.routers.traefik-dashboard.tls: true
      traefik.http.routers.traefik-dashboard.tls.certresolver: letsencrypt

      traefik.http.middlewares.corsHeader.headers.accessControlAllowOriginList: "*"
      traefik.http.middlewares.corsHeader.headers.accessControlAllowMethods: "GET,OPTIONS,PUT,POST,DELETE"
      traefik.http.middlewares.corsHeader.headers.accessControlAllowHeaders: "Content-Type,Authorization"
      traefik.http.middlewares.corsHeader.headers.accessControlAllowCredentials: true
    ports:
      - 80:80/tcp
      - 443:443/tcp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-ingress:/data
    networks:
      - boltnew-any-llm_bolt
    environment:
      - CF_API_EMAIL=your_CF_email
      - CF_DNS_API_TOKEN=your_CF_API_TOKEN
networks:
  boltnew-any-llm_bolt:
    external: true
`

What this does: spins up traefik using Cloudflare DNS challenge, deploys with LE a wildcard SSL for *.yourdomain, and also spins up the Traefik dashboard with host "dashboard.your.host" which also has LE SSL.

See the CORS settings just above ports, and how they look

Notice also the networks definition, Traefik must sit in the same network with Bolt network to be able to provide ingress services.

In my setup, `boltnew-any-llm_bolt` is the bolt-any-llm created when hitting docker-compose up. 

So first, spin up your bolt, with the labels that i pasted above, and the spin up your traefik . You should be able to access "bolt.yourhost.here" for the actual application, and "dashboard.your.host/dashboard" for the Traefik dashboard.

**Comment by neilyboy** [comment]
I'm not using traefik. I'm just freshly installed Ubuntu server on a little m920q threw docker/compose on it and tried to access it locally with canary browser as the readme suggests.

**Comment by nextdoormarketing** [comment]
Hello everyone, 

I'm back. I got it working in a docker container using this video as a guide.
https://www.youtube.com/watch?v=n1vOfdz5Nm8 
with these notes from the video: https://technotim.live/posts/traefik-3-docker-certificates/

Quite helpful deploying a traefik service to help with Let's Encrypt certs. Had a few issues and needed ChatGPT to clarify some of the labels and issues. ACME was not populating properly and DNS config for cname. After that, I got Bolt working. So to clarify, it was an SSL issue. Take a look, @neilyboy, and hope this can help you.
Thanks, @radumalica, for the right direction.

I have some new issues getting the .env.local being injected, but after that was able to delpoy.

Not I have issues for general functions now, as it's having an issue creating files, not modifying after the first creation, and refreshing. I will make a new thread as Bolt for these; I think its just a config issue, but not sure. 

Should I close this as @neilyboy is still having issues?

**Comment by hknerdr** [comment]
I am having the same issue:

Failed to spawn bolt shell

Failed to execute 'postMessage' on 'Worker': SharedArrayBuffer transfer requires self.crossOriginIsolated.

also on console i have these errors:

The Cross-Origin-Opener-Policy header has been ignored, because the URL's origin was untrustworthy. It was defined either in the final response or a redirect. Please deliver the response using the HTTPS protocol. You can also use the 'localhost' origin instead. See https://www.w3.org/TR/powerful-features/#potentially-trustworthy-origin and https://html.spec.whatwg.org/#the-cross-origin-opener-policy-header.
chunk-PV7Z3PNX.js:28440 Download the React DevTools for a better development experience: https://reactjs.org/link/react-devtools
3stackblitz.com/headless?version=1.3.0-internal.10:1 
        
client:535  WebSocket connection to 'wss://X.X.X.X:5173/' failed: 

i tried to enable ssl but couldn't succeed. i am using google cloud console ec2 instance.

**Comment by rutravis** [comment]
> The Cross-Origin-Opener-Policy header has been ignored, because the URL's origin was untrustworthy. It was defined either in the final response or a redirect. Please deliver the response using the HTTPS protocol. You can also use the 'localhost' origin instead.

Are you saying that this will work properly on localhost, but not on a remote host?

**Comment by hknerdr** [comment]
> > The Cross-Origin-Opener-Policy header has been ignored, because the URL's origin was untrustworthy. It was defined either in the final response or a redirect. Please deliver the response using the HTTPS protocol. You can also use the 'localhost' origin instead.
> 
> Are you saying that this will work properly on localhost, but not on a remote host?

I am not sure if it works on localhost or not but it doesn't on remote host. Trying to figure out how to solve that.

**Comment by nextdoormarketing** [comment]
I tried local, and if you want a valid cert you need a domain attached publicly or using a DNS challenge internally but still need a domain to confirm ownership. 

My previous comment I explained this a little bit how I solved this with Trafeik and a DNS challenge. 

Please see this video for reference on a how-to: https://www.youtube.com/watch?v=n1vOfdz5Nm8
with these notes from the video: https://technotim.live/posts/traefik-3-docker-certificates/

**Comment by aliasfoxkde** [comment]
Maybe try the flag to disable TLS temporarily before running dev/local mode?

```
set NODE_TLS_REJECT_UNAUTHORIZED=0
pnpm run dev
```

**Comment by wiwa1978** [comment]
I can confirm the issue does not occur on Localhost but it occurs when --host is being used. 

> Maybe try the flag to disable TLS temporarily before running dev/local mode?
> 
> ```
> set NODE_TLS_REJECT_UNAUTHORIZED=0
> pnpm run dev
> ```
This does not work

**Comment by mdlmarkham** [comment]
I'm running ProxMox as a homelab, and I'd like to run bolt.diy in an LCX container environment. I don't need to expose my environments to the web because I use Tailscale for direct VPN access remotely. I'd like to avoid setting up a proxy server if possible. Does anyone know of a way around this that doesn't require setting up a reverse proxy?
