### ISSUE TITLE
Do not expose this tool on any networks

### ISSUE THREAD

**Issue by Shybella** [coleam00/bolt.new-any-llm#194]
### Describe the bug

I own/operate dedicated infrastructure, I had a virtualizor VM running Ubuntu 22.04 Jammy, I did have this application exposed to the internet. However, I received a notification from the datacenter on an attack coming from that VM. I instantly took a peak and saw the VM used almost 1TB of bandwidth in the last day. 

I have the VM off and untouched, this thing was attacking every IP/Machine on our internet network. If someone wants to investigate I can provide the VM creds. 

The only two things on the VM was Ubuntu 22.04 Jammy + Bolt, nothing else, it was a fresh VM specifically for bolt. 

### Link to the Bolt URL that caused the error

I don't have one

### Steps to reproduce

1. Install Ubuntu 22.04 Jammy and Bolt and expose with --host

### Expected behavior

Not to go rogue

### Platform

Ubuntu 22.04 Jammy

**Comment by syndicate604** [comment]
Your going to need a lot more logs, and screenshots also just stating you have a VM in a datacenter = you can get hacked in 5 minutes.  It's got nothing to do with Bolt or Ubuntu - your in a public datacenter.

**Comment by Shybella** [comment]
> Your going to need a lot more logs, and screenshots also just stating you have a VM in a datacenter = you can get hacked in 5 minutes. It's got nothing to do with Bolt or Ubuntu - your in a public datacenter.

Again, I am including someone who works on Bolt access to the VM/image and any logs they need. I am not going to publicly broadcast this stuff here, that would be dumb. 

However, its extremely high chance that Bolt has something to do with it given there is plenty of VMs on 22.04 running on same build.

**Comment by syndicate604** [comment]
Depends on what API calls your making also and how many, and if running ollama what your downloading

**Comment by syndicate604** [comment]
I see nothing in bolt code that can do anything you describe:

![image](https://github.com/user-attachments/assets/e2d2add3-e2b0-4fa4-b709-496ea8227616)

**Comment by coleam00** [comment]
I'm thinking of closing this issue because I don't think this is related to the project really as @syndicate604 is saying. But please provide more details if you have that @Shybella
