### ISSUE TITLE
Open in a devcontainer?

### ISSUE THREAD

**Issue by sumith** [coleam00/bolt.new-any-llm#20]
**Is your feature request related to a problem? Please describe:**

I would like to run this in a docker container to get the obvious benefits of containers.

**Describe the solution you'd like:**

Add a .devcontainer and include the Dockerfile, docker-compose.yml to run Node.js, pnpm and to have the correct ports open to access Bolt from the host machine.

**Describe alternatives you've considered:**

**Additional context:**

I've tried adding the Dockerfile and docker-compose.yml.  However, getting stuck with `pnpm run preview` or `pnpm run start`.  Apparently it can't find the `./bindings.sh` file!  Running `pnpm run dev --host' option does start.  However, accessing it via the regular Chrome receives the message to use Canary.  However, the page never opens in Canary!

**Comment by HomeDev68** [comment]
Probably this might be solved if everything about the WebContainer was done offline.

**Comment by hillct** [comment]
This issue is addressed by PR https://github.com/coleam00/bolt.new-any-llm/pull/71
