### ISSUE TITLE
Output does not match the prompt

### ISSUE THREAD

**Issue by ag2design** [coleam00/bolt.new-any-llm#200]
### Describe the bug

Am I missing something in my set up? I have used the prompt in both bolt-new-any-llm and on bolt.new the website. I get completely different outputs.

This is bolt-new-any-llm
![Screenshot 2024-11-07 at 10 20 25](https://github.com/user-attachments/assets/d7beb66f-441b-4436-927d-6a742636f8dc)
This is bolt.new website
![Screenshot 2024-11-07 at 10 20 36](https://github.com/user-attachments/assets/4021ca63-1e34-48f8-9c7a-5ffa3b327e6d)
Everytime run a prompt to create a website on bolt-new-any-llm I just get a basic website
This is another example
![Screenshot 2024-11-07 at 10 26 39](https://github.com/user-attachments/assets/d79b3cbd-625b-4410-b13e-f94ca406676e)

### Link to the Bolt URL that caused the error

http://localhost:5173/chat/carlas-coffee-website-5

### Steps to reproduce

Create a 3 page website for Carlas Coffee in Harrogate

Home
Our Coffee
Contact

Make it a modern design with sleek ui

### Expected behavior

Expected to get something more modern looking

### Platform

macOs
Chrome

**Comment by SouthPenninesDT** [comment]
Just a thought but could this be to do with the UI framework that's used? Have you tried specifying a framework (such as Material, Bulma, Tailwind etc) ?.

**Comment by ag2design** [comment]
> Just a thought but could this be to do with the UI framework that's used? Have you tried specifying a framework (such as Material, Bulma, Tailwind etc) ?.

Here is an example with React and Tailwind - I am not sure if I have my set up wrong or am missing something

<img width="1685" alt="Screenshot 2024-11-07 at 12 56 41" src="https://github.com/user-attachments/assets/d0494f89-260c-4812-85e4-2c3a6775fa1c">
