### ISSUE TITLE
No files generated and no preview shown

### ISSUE THREAD

**Issue by SouthPenninesDT** [coleam00/bolt.new-any-llm#203]
### Describe the bug

No code files generated when prompt has finished and no preview of the output is shown.

### Link to the Bolt URL that caused the error

http://localhost:5173/chat/24

### Steps to reproduce

See video attached

### Expected behavior

Expecting the files to be shown in the file explorer on the right, and for the preview to show the generated output.

### Screen Recording / Screenshot

https://github.com/user-attachments/assets/2f5eaac7-7fb7-4210-878a-4828bbccb320

### Platform

- OS: macOS
- Browser: Vivaldi (Chrome-based)
- Version: Latest pull

**Comment by coleam00** [comment]
I see you are using Llama 3.2 3b. Unfortunately from my testing any model smaller than 7 billion parameters doesn't seem to be able to handle the large Bolt.new prompt. So this isn't an issue with the app rather it's the LLM just not being capable enough to produce the necessary output to work with the webcontainer.

If you want something pretty lightweight that still kicks butt, I would try qwen2.5-coder:7b!

**Comment by SouthPenninesDT** [comment]
Hey @coleam00 thank you. I made this change and increased the context parameter, but I'm still getting the same issue.

**Comment by coleam00** [comment]
Which model are you using @SouthPenninesDT? Smaller models will struggle with this even with the extra context length unfortunately.

**Comment by SouthPenninesDT** [comment]
Hi, I'm using qwen2.5-coder:7b

**Comment by coleam00** [comment]
Huh, I definitely get good results with Qwen 2.5 coder! Sometimes local LLMs still hallucinate though and it's best to just try another time or two, that honestly usually fixes it for me.

**Comment by SouthPenninesDT** [comment]
No worries @coleam00. I'll try again, thanks for coming back to me this is a great project!

**Comment by coleam00** [comment]
You are welcome, thank you @SouthPenninesDT!
