### ISSUE TITLE
Bolt is limited to 1 page due to massively high Token Use 

### ISSUE THREAD

**Issue by syndicate604** [coleam00/bolt.new-any-llm#207]
### Describe the bug

Using Bolt to make a 1 page website you will hit 80k input tokens pretty quick, you now need to be on Tier 2 Anthropic to even make 1 call per minute.   And since Bolt appears to write entire files it consumes 10x more token then needed.  Also when mistakes are made you can spend 500,000 credits getting the files BACK to where you were.    

### Link to the Bolt URL that caused the error

www.bolt.new

### Steps to reproduce

Use bolt 

### Expected behavior

Use less tokens making diffs vs full rewrites

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by dustinwloring1988** [comment]
this is an outdated version please try the latest and start a new issue if the problem persists
