### ISSUE TITLE
Sync Files

### ISSUE THREAD

**Issue by AlexanderHanff** [coleam00/bolt.new-any-llm#208]
### Describe the bug

No documentation on how to setup Sync Files feature

### Link to the Bolt URL that caused the error

http://localhost:8788

### Steps to reproduce

When I click on Sync Files, I simply get an error - I cannot find anything in the UI or anything in the README.md which allows or explains how to configure this feature.

### Expected behavior

Files should sync to a local folder

### Platform

- OS: MacOS
- Browser: Brave
- Version: Latest

**Comment by guzdal** [comment]
same error with Docker, MacOS (M1) and Ollama.
