### ISSUE TITLE
Ollama not working on other listening IP's

### ISSUE THREAD

**Issue by aaronbolton** [coleam00/bolt.new-any-llm#21]
### Describe the bug

when running the applcaition with --host Ollama doesn't connect so models arent listed, is the ollama modules hard code to use the browsed IP as the address for connection to Ollama?

also being able to configure a remote ollama server would be good

### Link to the Bolt URL that caused the error

n/a

### Steps to reproduce

browse to anything other than localhost

### Expected behavior

ollama to list available models

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by JRufer** [comment]
I think I may be running into the same issue. 
I installed this repo and got it running perfectly locally on windows but I use ngrok to forward ports on my local machine to have remote access. I noticed that when I access Bolt not from localhost but from my ngrok provided URL, the Ollama list of models is always empty. 
I could really use some help getting this working.

**Comment by leex279** [comment]
See #57 - I´ve got the same problems.
