### ISSUE TITLE
How can you use this to import local git repo or public git repo ?

### ISSUE THREAD

**Issue by LuD1161** [coleam00/bolt.new-any-llm#211]
**Is your feature request related to a problem? Please describe:**

How can you use this to import local git repo or public git repo ?

**Describe the solution you'd like:**

Like on bolt.new we can import a public repo by just appending to the url, like this - `bolt.new/~/github.com/LuD1161/your_repo_here`

If there's a way to import local repos or even remote repos, that would be awesome.

**Comment by traflagar** [comment]
That import causes bolt.new to give me the error "you don't have permission to access this repository". I have it set up through stackblitz and can access repositories. Any idea?

I haven't actually got coleam00's bolt.new to work. I was working to set it up with a Runpod. It would be great to be able to simply connect bolt to a project folder and manage my stuff locally.
