### ISSUE TITLE
NO Preview generated - Deepseek coder api

### ISSUE THREAD

**Issue by LuD1161** [coleam00/bolt.new-any-llm#212]
### Describe the bug

Hello team,

Thanks for the awesome tool. I've a paid API access to DeepSeek API and I am trying to build my app there. However, I am not able to see any preview yet. The files are generated, hence the context size isn't an issue.

<img width="1907" alt="image" src="https://github.com/user-attachments/assets/fceff605-4754-4f4d-a4c5-cafd879c8d84">

### Link to the Bolt URL that caused the error

http://localhost:5173/chat/todo-app-react-tailwind

### Steps to reproduce

1. Run the app in development mode.
2. Build the todo app.
3. It gets stuck in preview stage. See screenshot below. <img width="1907" alt="image" src="https://github.com/user-attachments/assets/fceff605-4754-4f4d-a4c5-cafd879c8d84">

### Expected behavior

The preview should be generated.

### Screen Recording / Screenshot

<img width="1907" alt="image" src="https://github.com/user-attachments/assets/fceff605-4754-4f4d-a4c5-cafd879c8d84">

### Platform

- OS: macOS
- Browser: Firefox

**Comment by LuD1161** [comment]
For some reason it gets generated in chrome but it still shows as running for the last command - `npm run dev`

<img width="1506" alt="image" src="https://github.com/user-attachments/assets/828bf750-365e-4e96-ac2e-f6ce321d6068">

Any ideas ?

**Comment by LuD1161** [comment]
Also the preview looks very bad, with the deepseek coder api. is this how it is supposed to be 🤔 ?

**Comment by ag2design** [comment]
I have been struggling with this for the last 24 hours - also using Deepseek and also Anthropic - I have tried running with and without Docker - what I am finding is that when I give an instruction like Create an Astro site it can't complete it. 

using terminal and running npm create astro@latest

I get this

project initializing...
         ▶ Template copying...
         □ TypeScript
         □ Dependencies
      ▲  error Failed to fetch https://api.github.com/repos/withastro/astro/tarball/examples/basics
      ▲  error TypeError: fetch failed
      ▲  error SocketError: other side closed
      ▲  error Unable to download template basics
npm ERR! code 1
npm ERR! path /home/project
npm ERR! command failed
npm ERR! command sh -c create-astro

**Comment by JaswinderJohal** [comment]
i am running into same issue. Using Deepseek API. Have tried 3 different browsers. FF, Chrome Canary and Safari. It generates the code, then stuck on "Run Command" which keeps spinning forever. Only displaying white page in preview window. Anyone able get past it? Not sure what i am doing wrong.

**Comment by HatNet85** [comment]
I use Linux I don't have any problem but slow to do coding take 1 min at list and only use deepseek chat model not deepseek coder even I select coder some reason

**Comment by veerababumanyam** [comment]
I wasted almost 3 days on the same issues. Tried both IE and Chrom but no help. Also, I tried using different LLM Anthropic, OpenAI, DeepsekCoder, QwenCoder. I tried both docker version and windows version but no help. I did all the setting including Context length for all local model but still no help. I formatted my entire windows and did clean install of ollama and bolt.new but still no help. I doubt if this is really working for anyone? If yes, suggest me what exactly required to make it work. I did all in github, watched videos and followed every step but no help. 
![image](https://github.com/user-attachments/assets/819b53b8-ced9-41dd-91b5-13fc02c30511)
![image](https://github.com/user-attachments/assets/f0ff00cd-f43a-4432-877d-40a1cdf6ed3c)
![image](https://github.com/user-attachments/assets/50bf3ccc-ef11-41b4-96cb-56e0f58c849d)
![image](https://github.com/user-attachments/assets/79a88178-376a-4b7f-800e-11bd7dc49373)

**Comment by questautomata** [comment]
I'm having the same issue but so far it's due to my model half applying actions and half just responding to messages. 90% of the time with deepseek it doesn't even control the codebase. Personally with my issue I have dependencies that aren't being installed and when i manually install they get deleted again. because the commands arent being executed im getting ports opened and they wont close unless i close bolt, and kill the processes manually. with xAI i can get one or two commands in before it hangs. nothing at all with deepseek.
![msedge_fs17nuDp7z](https://github.com/user-attachments/assets/044b84a9-51e7-4b56-b39a-d7ae9066f340)

**Comment by questautomata** [comment]
A workaround fix for me has been to tell the LLM specifically not to use ANY commands which are persistent (npm start, node for server, nodemon etc) and that i would start them myself. that allowed me to finally see updated preview.
Hope this works for someone!

**Comment by dilzilla** [comment]
yeah doesnt work for me unless the project is simple html no tailwind or anything
