### ISSUE TITLE
No previews with anything but Sonnet 3.5

### ISSUE THREAD

**Issue by sandervdorth** [coleam00/bolt.new-any-llm#216]
### Describe the bug

when using any other llm than Sonnet 3.5 i get nothing in the Preview window no matter how many times i prompt the bloddy thing. Gemini, Deepseek, 4o none can give me a preview. I've tried with and without Docker multiple times now.

### Link to the Bolt URL that caused the error

http://localhost:5173/chat/huijsmeester-pwa-setup

### Steps to reproduce

no special, just prompt it 

### Expected behavior

I need to be able to see stuff in the preview window as im not a coder

### Platform

- OS: Windows
- Browser: Canary
- Version: Latest

### Additional context

its been like this for a couple of days and im about to say goodbye and move back to Bolt.new

**Comment by dilzilla** [comment]
yeah no preview for me either! not really useable yet
