### ISSUE TITLE
FEATURE: Mistral and Codestral cloud API free for experiments, as well as Cerebras

### ISSUE THREAD

**Issue by PieBru** [coleam00/bolt.new-any-llm#22]
**Is your feature request related to a problem? Please describe:**
No problems, just good news.
I just saw the details [here by AiCodeKing](https://www.youtube.com/watch?v=igE0X25bHcE&list=LL&index=5), and it seems great news for our beloved "Bold" fork.

**Describe the solution you'd like:**
Integration with Mistral.ai free tier inference API.

**Describe alternatives you've considered:**
Also [Cerebras](https://cloud.cerebras.ai/) has an useful free inference API tier with "reasonable" daily/monthly auto-renew limits, but they now support only Llama3.1 8B and 70B.

**Additional context:**

**Comment by ArulGandhi** [comment]
I've done this already. I'll make the repo public soon as when I confirm it's stable. Likely in about 3 hours.

**Comment by ArulGandhi** [comment]
here's mistral. I'll update for cerebras soon.
https://github.com/ArulGandhi/bolt.new-any-llm

**Comment by ArulGandhi** [comment]
API key for cerebras isn't available yet and I don't see an option for it on the Vercel AI SDK page. Do you have any alternatives? Otherwise, the project would need a custom implementation just for this one provider (feel free to correct me)

**Comment by ArulGandhi** [comment]
@coleam00 Mistral has been finalized. Please merge at the earliest. Thanks

**Comment by PieBru** [comment]
> API key for cerebras isn't available yet and I don't see an option for it on the Vercel AI SDK page. Do you have any alternatives? Otherwise, the project would need a custom implementation just for this one provider (feel free to correct me)

I got the Free tier API access from https://inference.cerebras.ai/ after signup and a week or so later I've been approved. 

PLEASE NOTE:
1. I'm not affiliated in any way with those organizations. More, where possible I like to embrace the "LocalLlama" lifestyle, as other people do https://www.reddit.com/r/LocalLLaMA/
2. I'm personally comfortable with those LLM inference cloud services, however keep in mind that using any "FREE" cloud service (like FB, WA, Instagram, uncle G.) you are "the product", not the customer ;-)

**Comment by PieBru** [comment]
Also Sambanova https://cloud.sambanova.ai/pricing has a free tier. Although I don't know the actual limits, it seems pretty usable, at least for now.

**Comment by ArulGandhi** [comment]
I'll try and see if they can be integrated. Thanks for the heads up!

**Comment by PixifyAI** [comment]
can you make sure that Codestral api is added not just Mistral api, they are not the same api.

**Comment by ArulGandhi** [comment]
With the current setup codestral is working. If you face an issue, create one in my repo and I'll fix it within 24h. 😁😀

**Comment by ArulGandhi** [comment]
@PieBru I just got access to the Cerebras API. I'll make a PR soon since it shouldn't be difficult to add (OpenAI like, similar to Groq)

**Comment by ArulGandhi** [comment]
I'll open another issue to track this addition. @coleam00, What's your opinion on the required rate-limiting / tokens / inference time / context window for this project?

**Comment by ArulGandhi** [comment]
#127 😄 Cerebras is in!

**Comment by PieBru** [comment]
> What's your opinion on the required rate-limiting / tokens / inference time / context window for this project?

Pretty useful for a single dev, more useful than Groq.

**Comment by ArulGandhi** [comment]
No, like what values are recommended to be worked with? Rate-limiting : Gemini limits to 2 RPM so that's low and troublesome. Token limits are also not very lenient for actually good models and Amazon Bedrock has a lower and artificial output token limit of 4096. Not very helpful. Also, Llama 3.1 70B isn't working very well (code quality-wise). Can you recommend something else with a better model and similar free tier? Thanks!
