### ISSUE TITLE
Unable to create a NextJS project

### ISSUE THREAD

**Issue by svzi** [coleam00/bolt.new-any-llm#220]
### Describe the bug

I'm using this simple prompt to create a NextJS app:
```
Create a todo app with NextJS and Shadcn
```
Then I get this response:
<img width="573" alt="image" src="https://github.com/user-attachments/assets/63524222-da6d-415b-ae8c-140a235276f7">

And there it stands for ever. Spinning on the first command. Looking an the JavaScript console shows the following:
<img width="665" alt="image" src="https://github.com/user-attachments/assets/911c188e-97d4-4d32-8311-875bf5c4fb92">

So I assume that the command to create the NextJS app is still waiting for a user feedback (if he wants to use Turbopack yes or no). I could be handled without user interaction,

We could make the command non-interactive by adding the `--yes` or `-y` parameter. Here's the complete command:

```bash
npx create-next-app@latest todo-app --typescript --eslint --tailwind --app --src-dir --use-npm --yes
```

Alternatively, we could also set all other parameters as defaults by prefixing them with `--no-` if you don't want them. For example:

```bash
npx create-next-app@latest todo-app --typescript --eslint --tailwind --app --src-dir --use-npm --no-import-alias --yes
```

The most important parameters are:
- `--yes` or `-y`: Skips all prompts and uses defaults
- `--typescript`: TypeScript setup
- `--tailwind`: TailwindCSS installation
- `--eslint`: ESLint setup
- `--app`: Uses the App Router (instead of Pages Router)
- `--src-dir`: Creates a src/ directory
- `--use-npm`: Uses npm instead of yarn
- `--import-alias`: Sets the import alias (default is @/*)

### Link to the Bolt URL that caused the error

http://localhost:5173/chat/nextjs-shadcn-todo-app

### Steps to reproduce

I installed the fork locally on my mac and run it with `pnpm run dev`.

And then simply use the aforementioned prompt:

```
Create a todo app with NextJS and Shadcn
```

### Expected behavior

It should create a NextJS app and doesn't wait for user interactions that I can't do.

### Platform

- OS: macOS
- Browser: Google Chrome Canary
- Version: 132.0.6826.0

**Comment by svzi** [comment]
I would also like to note that I have no "Bolt" terminal, like at bolt.new where I can see what he does.

Here is the official version:
<img width="362" alt="image" src="https://github.com/user-attachments/assets/e5a39dcf-e12a-4cc8-bc78-d3d91ccc888c">

And here how it looks like when I run this fork locally:
<img width="502" alt="Bildschirmfoto 2024-11-08 um 20 36 55" src="https://github.com/user-attachments/assets/af1afb94-05b9-4048-b74c-6310d3ff7ed1">

**Comment by leex279** [comment]
next also not working for me. I also see it is not available within bolt, even my powershell says it is there:
![image](https://github.com/user-attachments/assets/d7d87787-f1c2-470e-ab7e-4f202fa18424)

**Comment by dpaluy** [comment]
I'm getting a similar issue 

It is stuck on the initial setup 
![CleanShot 2024-11-11 at 16 46 03@2x](https://github.com/user-attachments/assets/9243ce97-8a64-4a9c-922a-3a9985ac0eec)

**Comment by moemar** [comment]
Same when trying Nuxt project.

![image](https://github.com/user-attachments/assets/3580c893-5bbb-4916-9821-8f6e3fca22c1)

**Comment by joacorob** [comment]
Same issue here!
