### ISSUE TITLE
Code quality does not match bolt.new

### ISSUE THREAD

**Issue by aphtechme** [coleam00/bolt.new-any-llm#223]
Firstly, thank you for this amazing fork! We tried testing it with OpenAI, Anthropic and qwen2.5-coder and the quality of the code and the UI does not match the same request made on bolt.new, which organises the code better, generates better looking UI, etc. I'm assuming they are using different prompts to generate the code? How can we improve this fork to deliver the same quality as bolt.new?

**Comment by CRYPTO-GENIK** [comment]
I can't even get it to build and run a hello world app. Which AI are you using?

**Comment by uniqcli** [comment]
Same here. It can't write anything. Looks like there are permission error

**Comment by thecodacus** [comment]
this is related to issue #52 
we need to work on project templates to match the code quality

**Comment by thecodacus** [comment]
I have already raised 2 pr 

code streaming : #213   for streaming the code to the UI editor
bolt terminal: #228  for having a dedicated terminal to work with bolt this solves the problem of dev server keeps running in background when another start command is executed

**Comment by aphtechme** [comment]
> I have already raised 2 pr
> 
> code streaming : #213 for streaming the code to the UI editor bolt terminal: #228 for having a dedicated terminal to work with bolt this solves the problem of dev server keeps running in background when another start command is executed

@thecodacus Thank you for your work! Do your PR improve the code generation to near the quality of bolt.new site?

**Comment by aphtechme** [comment]
Closing this as it's been report in https://github.com/coleam00/bolt.new-any-llm/issues/52
