### ISSUE TITLE
Allow loading an existing codebase to expand on

### ISSUE THREAD

**Issue by Mouradif** [coleam00/bolt.new-any-llm#232]
**Describe the solution you'd like:**

Instead of an initial prompt, I would love to have the ability to load an existing project by specifying the folder (the same way sync files does but files would move from the selected folder to the Bolt context). Then I would be able to prompt the AI to make changes directly on the existing project.

**Comment by Intiiii** [comment]
the downside is that you start with a large project, so you'll burn through your tokens from the start, and it will take longer to generate an answer

**Comment by Mouradif** [comment]
True, but if your goal is to build a large project with, it would burn much more tokens starting from scratch anyway. Also, nothing forces you to start with a large project.
