### ISSUE TITLE
Doesnt work in Arc Browser

### ISSUE THREAD

**Issue by MatQV** [coleam00/bolt.new-any-llm#234]
Noob question, can I use Arc browser to use it in the first place? I've read some things about Chrome Canary, I'm trying that after writing this, but I thought it could help sharing my issue.

Everytime I try to create a project, ie. "Create a simple contact form" it all goes well until it gets stuck on the **`npm run dev`** command, it opens like 2 or 3 separate windows with this error:

![SS - 000482](https://github.com/user-attachments/assets/ab92d651-f264-46b8-9726-9969c4d11422)

Here's what I get on the console:

![SS - 000481](https://github.com/user-attachments/assets/5c5d5d61-d43a-4f05-83ee-7b4f3e2b7f5a)

Maybe I'm missing something (not really a coder over here), any ideas? For what I can see, it has something to do with WebContainer API, should I add my API somewhere?

Thanks!

**Comment by chrismahoney** [comment]
I get this as well within Brave Browser, it’s recommended to stick to the Chrome Canary requirement for now as I’ve seen less of an issue there. Two PRs are in flight right now regarding code streaming and re-introduction of the main “bolt” terminal, which I’m seeing resolve my `npm run dev` failures to complete in initial testing. 

Bolt terminal: #228 
Code streaming: #213

**Comment by MatQV** [comment]
I can confirm it's the browser, I've installed firefox and all working well. Hope this can be fixed someday! Thank you!
