### ISSUE TITLE
Docker run: The Compose file is invalid ...

### ISSUE THREAD

**Issue by checkso** [coleam00/bolt.new-any-llm#241]
### Describe the bug

I followed the instructions but got this error when trying to start the container.

```
bolt.new-any-llm$ docker-compose --profile development up
WARNING: The GROQ_API_KEY variable is not set. Defaulting to a blank string.
WARNING: The OPENAI_API_KEY variable is not set. Defaulting to a blank string.
WARNING: The ANTHROPIC_API_KEY variable is not set. Defaulting to a blank string.
WARNING: The OPEN_ROUTER_API_KEY variable is not set. Defaulting to a blank string.
WARNING: The GOOGLE_GENERATIVE_AI_API_KEY variable is not set. Defaulting to a blank string.
WARNING: The OLLAMA_API_BASE_URL variable is not set. Defaulting to a blank string.
ERROR: The Compose file is invalid because:
Service bolt-ai-dev has neither an image nor a build context specified. At least one must be provided.
```

Any ideas, what is wrong? I cannot figure it out...

### Link to the Bolt URL that caused the error

https://github.com/coleam00/bolt.new-any-llm/

### Steps to reproduce

docker-compose --profile development up

### Expected behavior

container starts

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by mmundy3832** [comment]
Yesterday I got the docker container to work on my windows dev machine. But it was all on CPU. I decided to put it on my Linux Mint with dual NVidia GPU, and I got this same error today. No clue so far.

**Comment by checkso** [comment]
Hm, maybe something on Linux which might be the issue? Didn't test yet on windows.

**Comment by mmundy3832** [comment]
I'm still working through this, and I discovered that the images did not have names. With a little chatgpt help, I added tags to the images with the commands:
docker build -t bolt-ai:development .
docker build -t bolt-ai:production .

Unfortunately, I'm still having the same issue when I run the docker-compose up command. I'll see where I can get from here

**Comment by mmundy3832** [comment]
OK, forget what I said before, that didn't work, and I removed those images.

As a workaround, I was able to get the production profile to launch properly, but only after I commented out the entire bolt-ai-dev section. Perhaps there is a syntax error in that section because when I had only that section available, I still get the same error as above. 

At the moment, I think that is good enough workaround for me. I hope it helps you too. Hopefully this will lead someone to find a more permanent fix

**Comment by checkso** [comment]
ok got it to work.

Following needs to be added:
![image](https://github.com/user-attachments/assets/045e9b3a-93db-41fd-bd27-f5309de56c1b)

```
  bolt-ai-dev:
    image: bolt-ai:development
    build:
      context: .
      dockerfile: Dockerfile
      target: bolt-ai-development
    env_file: ".env.local"
```

**Comment by mmundy3832** [comment]
This seems to work on my Windows box. I will have to try it on my Linux machine later to verify this solves the problem over there as well.

**Comment by chrismahoney** [comment]
Thanks for keeping everyone posted, this seems unusual but typical for making sure cross-platform docker works. Making a note

**Comment by guzdal** [comment]
> ok got it to work.
> 
> Following needs to be added: ![image](https://private-user-images.githubusercontent.com/11270200/385715893-045e9b3a-93db-41fd-bd27-f5309de56c1b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyOTI0OTIsIm5iZiI6MTczMjI5MjE5MiwicGF0aCI6Ii8xMTI3MDIwMC8zODU3MTU4OTMtMDQ1ZTliM2EtOTNkYi00MWZkLWJkMjctZjUzMDlkZTU2YzFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIyVDE2MTYzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjNWE5Nzk3Mjk0NThmYWVkZTZmMzk0MzZiZjVlN2I1NTExODk3Y2NkN2EwMjRkOWY1ODMxMzg3NGY2YjQ1MWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.RynUwP24FrisunMTMhKsZh-5pA17-XhULJ2HT9_Byw0)
> 
> ```
>   bolt-ai-dev:
>     image: bolt-ai:development
>     build:
>       context: .
>       dockerfile: Dockerfile
>       target: bolt-ai-development
>     env_file: ".env.local"
> ```

this one sparks joy! 
thank you, it's working on my own Linux MINT machine, i'm trying a very small llama model first, then on my M1 chip. 
It gives me some ideas to try and 'clusterize' ollama instances :^)
