### ISSUE TITLE
404 Not Found - Webcontainer Issue

### ISSUE THREAD

**Issue by heartsiddharth1** [coleam00/bolt.new-any-llm#248]
### Describe the bug

getting 404 not found after code is generated and npm run dev is done. 

### Link to the Bolt URL that caused the error

https://github.com/coleam00/bolt.new-any-llm/

### Steps to reproduce

pnpm install affter fresh new git clone

set ollama  url for api of local ollama 

select the ollama as the provider and then the model of extra context so that the coding gets generated and files

post the file creation complete the coding window does npm run dev and then we get the error 

### Expected behavior

It should work as usual how the bolt.new is performing for local ollama 

### Screen Recording / Screenshot

https://github.com/user-attachments/assets/ad1e1d30-f0bb-4d54-ad23-fb0ad9823f8d

### Platform

- OS: Windows 
- Browser: Chrome,Edge

### Additional context

none

**Comment by RustyRSR** [comment]
I have the same issue using the docker build

**Comment by heartsiddharth1** [comment]
> I have the same issue using the docker build

The thing is there is no clue why it is happening. I am not running this in docker. I just did a pnpm install and did pnpm run dev and  post api population of ollama url , i went to create the todo in react . and this happens.;    

we have so many people contributing to the project. i am sure someone knows the answer to it.

**Comment by anas-kech** [comment]
Same issue no preview when using ollama even with Deepseek Coder V 2 15.7B or Qwen 2.5 Coder 7B

**Comment by coleam00** [comment]
I'm sorry you guys are having trouble with this @anas-kech @heartsiddharth1 @RustyRSR! This is unfortunately caused by the LLM hallucinating and giving the wrong command/url for the preview. We have a PR out now that should help this immensely:

https://github.com/coleam00/bolt.new-any-llm/pull/228

**Comment by heartsiddharth1** [comment]
> I'm sorry you guys are having trouble with this @anas-kech @heartsiddharth1 @RustyRSR! This is unfortunately caused by the LLM hallucinating and giving the wrong command/url for the preview. We have a PR out now that should help this immensely:
> 
> #228

Thank you Cole for your kind reply. Could you please give an eta.

**Comment by coleam00** [comment]
This week for sure @heartsiddharth1!

**Comment by chrismahoney** [comment]
#228 is merged to main, any issues you might find related to that please create a new issue. 🙌

**Comment by chrismahoney** [comment]
For future reference, having the Todo app with Tailwind at the top of the suggested prompt list might be generating a lot of issues as with a small model it’s not properly creating all of the necessary files (which I assume results in the 404). I would suggest trying progressively more detailed custom prompts and some adjustment of the suggestion list that are more friendly to smaller model usage.

**Comment by heartsiddharth1** [comment]
@chrismahoney  @coleam00  

![image](https://github.com/user-attachments/assets/79a017f9-6756-487c-b2be-283cf7fa6f89)


at this moment its like litreally tears coming out that this is still not fixed :( 
 please help ,

**Comment by chrismahoney** [comment]
Going to bring up some potential solutions tomorrow, I've been looking at it quite a bit this evening.

**Comment by thecodacus** [comment]
whats the output coming on terminal?

**Comment by heartsiddharth1** [comment]
> Going to bring up some potential solutions tomorrow, I've been looking at it quite a bit this evening.

any update on this one your kindself sir ?

**Comment by RosaiJ** [comment]
FWIW, here's a couple of screenies.. no docker just straight pnpm run dev
![image](https://github.com/user-attachments/assets/b291b50d-d65e-4dd2-bef0-9e612aaa7d57)
![image](https://github.com/user-attachments/assets/2044ced3-5f87-400e-84ca-630dd73d0cd3)

**Comment by heartsiddharth1** [comment]
@chrismahoney  i am sure you are working on this one on priority as you mentioned earlier in the thread. But just to put things in context-  If the container is not runing primarily with pnpm run dev. It is stopping us to create new things . I want to be able to try this  in the container before i proceed to do things. This was the very reason i chose bolt.new any llm and i think . This needs to be a priority threaed to resolve. As it is going to help so many people in  on this git. 
i hope you understnd the urgency. Whilst i truly appreciate that you have commitments and respect your time. 

Thank you Chris for your help hope we get a detailed answer and expected timeframe from you and also some insights as to why this is happening, So that we all can learn something from this.

**Comment by thecodacus** [comment]
can you ask it to write a vite config and then ask it to run start the application

**Comment by chrismahoney** [comment]
👍 to @thecodacus suggestion. These failure states are our main focus right now, making sure we account for any and all local/remote providers.

**Comment by chrismahoney** [comment]
For transparency, the core solution here is having a set of sane templates to work from, which once loaded contain all of the proper dependencies, npm scripts, and model context awareness to land on a non-error preview load the first time. This will not only result in accurate project starts, but ideally also a drop in token usage to get started.

That’s the intention, and it may just take a while to lock that in. I assure you it is front and center priority. 🙌

**Comment by heartsiddharth1** [comment]
@chrismahoney  @coleam00  -  git cloned a fresh install and getting this below error :(  Kindly provided a detailed way of solving this please. 

![image](https://github.com/user-attachments/assets/c48402af-7d78-4985-8fab-a7796051e369)

**Comment by coleam00** [comment]
@heartsiddharth1 I would try repulling, I know for sure this isn't an issue right now!

**Comment by jvxcampos** [comment]
I have exactly the same problem, even with everything updated

**Comment by devictang** [comment]
Same problem here. Hope someone can help.

**Comment by dustinwloring1988** [comment]
What model are you using with ollama and what is your prompt.

**Comment by devictang** [comment]
> What model are you using with ollama and what is your prompt.

Model used: Ollama qwen2.5-coder:latest
Prompt: Build a simple counter for me in react. A counter with large text displayed. Two buttons below it, left button add one to counter when clicked, right button reset counter to 0 when clicked. Counter is updated real-time.
Current Result: Either it says "no preview available" despite no error message shown up in bolt terminal, or a white screen is displayed (network tab says 404 not found, but with a bunch of code 200)

<img width="1468" alt="螢幕截圖 2024-12-23 下午10 25 42" src="https://github.com/user-attachments/assets/16396ca4-af46-44d4-9acb-953cfa6c2649" />

If I enter "npm run dev" manually in bolt terminal, 404 error observed in network tab.
<img width="1468" alt="螢幕截圖 2024-12-23 下午10 49 37" src="https://github.com/user-attachments/assets/df712988-fefd-4aa7-8e4d-05285c51fadb" />

No error message in bolt terminal
<img width="1468" alt="螢幕截圖 2024-12-23 下午10 50 38" src="https://github.com/user-attachments/assets/5432b234-0b31-40a0-947a-0df45082cdd2" />

**Comment by dustinwloring1988** [comment]
use a bigger model I use the 32B version of qwen2.5-coder. This snippit is from the docs:
![image](https://github.com/user-attachments/assets/77ab40ab-1524-474b-9ab1-e62547d7530a)

**Comment by devictang** [comment]
> use a bigger model I use the 32B version of qwen2.5-coder. This snippit is from the docs: ![image](https://private-user-images.githubusercontent.com/21135165/398203416-77ab40ab-1524-474b-9ab1-e62547d7530a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5Njk2ODksIm5iZiI6MTczNDk2OTM4OSwicGF0aCI6Ii8yMTEzNTE2NS8zOTgyMDM0MTYtNzdhYjQwYWItMTUyNC00NzRiLTlhYjEtZTYyNTQ3ZDc1MzBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIzVDE1NTYyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlMTQyYjNhZWRhOTU5YzUxNDY3MDNhNzFlNjJlZmUyNzY5MzI2ZTRmNDNkM2Y4MjNlNmM2NDBkNGZiNGU5OGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.UnJYFxdqLi3srdbrPs6oR_SZIquTXJpVPZFCGydWIb8)

I have already extended the qwen2.5-coder:latest model to 32768, shouldn't that still be the problem? When watching some Youtube tutorials they were using the 7b version and still get the preview.

Currently I get the preview if I ask bolt to write a HTML webpage, but no preview available for react webpage. Another problem happens coincide and I'm not sure if my set up is wrong somewhere so I'm gonna mention it here: I cannot connect my Claude API key to bolt.diy, I have added the key to .env but still can't use Claude AI for code generation.
