### ISSUE TITLE
Ollama out of memory

### ISSUE THREAD

**Issue by Intiiii** [coleam00/bolt.new-any-llm#249]
### Describe the bug

Hi, I'm sorry if this is a dumb question, but I cant get ollama to work. Its saying in the logs "model requires more system memory (19.5 GiB) than is available (15.4 GiB)", but when I run the model just in cmd or powershell, it works just fine. Is this because the rest is using memory as well? or is this caused by something else?

### Link to the Bolt URL that caused the error

none

### Steps to reproduce

1. Install a ollama model
2. select it in bolt
3. send message
4. receive error

### Expected behavior

Working the right way, aka responding 

### Platform

Windows 10, Google chrome, latest version

**Comment by omarnahdi** [comment]
@Intiiii It's happening with me too

**Comment by chrismahoney** [comment]
How large is the model you are trying to run, and what system specifications are you running with? If the model won’t fit within RAM via Ollama, it certainly won’t be usable with oTToDev. Please share those specs and try to utilize smaller models, 19.5GB sounds like a larger model and it appears you’re running a 16GB video RAM environment.

**Comment by Intiiii** [comment]
I'm trying to run deepseek-coder-v2, wich is only 8.9GB...

**Comment by radumalica** [comment]
it won't work. I have rtx 4070 with 12gb vram and ryzen 5 with 64gb ram and even GGUF deepseek-coder-v2-instruct lite with Q4 quantization consumes from start 24GB of ram (vram+ram) and kills the ryzen cpu 65% and 4070 at 55% and after 3 minutes it times out with error, and ollama hangs on stopping the model until i kill it. Tried a deepseeker coder lite gguf with q2 quantization that consumes only 17GB and that is working, but slow.  The best compromise is llama3.1 as i've seen. qwen2.5 is too big, haven't tested others. Better option is buyin a 4090 rtx or setup a server with Nvidia Tesla K80 which has 2xgpus inside with 12gb each so total 24gb vram. You could get a dual PCIE 3.0x (this is the lane used by K80) and install 2x K80 with 48gb vram total and that will work. One board is around 100E in Europe, and less in US.

**Comment by omarnahdi** [comment]
@coleam00 Is there a solution to run deepseek coder? it always runs out of memory for some reason, even though it runs quick in the terminal. @radumalica I also notice when I try to load Phi3.5 base model (which is only 2.2GB) It also throws out of memory error on that too, which is clearly non sense.

**Comment by coleam00** [comment]
@omarnahdi Are you running it through Ollama or OpenRouter? I haven't had this happen myself with either actually but I'm curious. And are you using the 16b or 236b parameter version?

**Comment by omarnahdi** [comment]
@coleam00 I am using ollama and was running the 16B variant of the model

**Comment by omarnahdi** [comment]
@coleam00 I have i9-13900H CPU, 32GB DDR5 RAM, Iris xe integrated graphics, 1TB SSD, I run models on my CPU

**Comment by jsbrown88** [comment]
What model are you loading in to Ollama ?

**Comment by omarnahdi** [comment]
> Got it @omarnahdi, what are your system specs?

Also I have moved on from the deepseek model and currently using the qwen 2.5 coder 7B.
