### ISSUE TITLE
pinokio

### ISSUE THREAD

**Issue by deekaljin** [coleam00/bolt.new-any-llm#250]
i have pinokio installed on the D drive (not the windows C drive), and I ran into the issue in the attached image. anyone has an idea what to do?

![bolt-pinokio](https://github.com/user-attachments/assets/22482a85-0430-4610-a438-1e383e3348fd)

**Comment by chrismahoney** [comment]
This is probably going to be more of a question related to Pinokio, for anyone unaware Pinokio is a self-contained system to run apps like this in a sandbox of sorts. I don’t think anyone has been doing work specific to this, so if anyone has previous experience with setting up Pinokio app definitions a PR would be super helpful.
