### ISSUE TITLE
feat: can you add a dark mode?

### ISSUE THREAD

**Issue by twicer-is-coder** [coleam00/bolt.new-any-llm#260]
**Is your feature request related to a problem? Please describe:**
Add a dark mode please like original bolt app, or please put instructions in docs to enable dark mode.

**Describe the solution you'd like:**
a dark mode which replaces all white colors.

**Describe alternatives you've considered:**
No alternative tried.

**Additional context:**
none.

**Comment by AnonymousCoderArtist** [comment]
its already in dark theme no?

**Comment by twicer-is-coder** [comment]
Closed, dark mode is located at the bottom left of the popped up sidebar unlike original bolt.
