### ISSUE TITLE
Request for help setting up bolt.new in a private AI environment

### ISSUE THREAD

**Issue by traflagar** [coleam00/bolt.new-any-llm#263]
Hi,

I have worked for hours trying to get bolt.new to work with a Runpod instance and haven't come close.

I could really use some help getting bolt.new connected to a private AI. My research and development relates to making AI products and I do not want to feed it into the giant's maws.

I'll tip $50 for the help. Runpod doesn't have to be the provider. IF you have already set up bolt.new with a no-logs provider, please please contact me.

Discord: traflagar_17037 I am usually available sometime from 10AM to 7PM eastern.

**Comment by traflagar** [comment]
I'll tip $75. Really need a hand with this from someone who has bolt.new running with a remote private AI provider.

**Comment by jasper11452** [comment]
<img width="743" alt="截屏2024-11-15 13 13 42" src="https://github.com/user-attachments/assets/09a9abaa-72de-4fd1-88f1-818241f90c51">
You can find these settings in the environment settings. Use the custom `base_url` to access the custom model

**Comment by pawan941394** [comment]
@traflagar connect me on https://www.instagram.com/p_awan__kumar/
i can help you with runpod i have hosted there my bolt new project with ollama
