### ISSUE TITLE
Feature Request: Import Existing Project Folder in bolt.new Chat Instance

### ISSUE THREAD

**Issue by viaahmed** [coleam00/bolt.new-any-llm#268]
**Is your feature request related to a problem? Please describe:**  
Currently, bolt.new does not provide an option to import an existing project folder into a chat instance, which limits its usefulness for developers who want to work on pre-existing codebases directly within the tool. This restriction can make it challenging for users to transition ongoing projects to bolt.new without manual adjustments, which can be time-consuming and reduce productivity.

**Describe the solution you'd like:**  
It would be valuable to have an "Import Project" feature, allowing users to upload an entire project directory or select specific folders/files to integrate into the bolt.new chat instance. This would ideally include:
- The ability to upload project folders and subfolders with their full structure intact.
- Seamless integration with bolt.new’s existing file editor, allowing users to edit, manage, and save imported files.

**Describe alternatives you've considered:**  
- Manually copying and pasting code files, which is inefficient for large projects.
- Using other IDEs or cloud-based development tools with integrated AI support; however, these tools may lack bolt.new's unique features and LLM integrations.
  
**Additional context:**  
Including this feature could expand bolt.new's appeal to developers who often switch between projects or want to leverage bolt.new’s AI-enhanced code suggestions for ongoing development. This functionality would enhance productivity and broaden the tool's application across different use cases.

**Comment by clickbrain** [comment]
I attempted to get it to read in a repository from Github and it could not. Would be great to be able to enter an API token from Github, point it to a repo, fork it or at least add the files to the project in Bolt and then be able to work on that from there.

**Comment by Blitchy** [comment]
> I attempted to get it to read in a repository from Github and it could not. Would be great to be able to enter an API token from Github, point it to a repo, fork it or at least add the files to the project in Bolt and then be able to work on that from there.

i found this video that you can import repository to bolt and make edit on it 
https://youtu.be/gpI7kU-zxJE?si=CskuUwvp2NriSLGy
but it work only with bolt.new/~/github..... not with  localhost

**Comment by Stephanisk** [comment]
I had exactly the same question I googled minutes ago. Would be amazing if we could get a project folder uploaded into the system.

Similarly you can not upload your own images to be included in the codebase (for webdesign) this would also be amazing if this were possible.

**Comment by dustinwloring1988** [comment]
please try the latest version if you are still having problems please open a new issue
