### ISSUE TITLE
Connecting the LLM wit  localHost

### ISSUE THREAD

**Issue by Muggel74** [coleam00/bolt.new-any-llm#269]
### Describe the bug

Hello, we are trying to configure the local machine for the local Host with DeepSeek. We can go to our 
Local Host website but we can't select something in the second menu. We need help!
![Bild 13 11 24 um 19 04](https://github.com/user-attachments/assets/82b1e5f6-c712-457a-bc01-0521e54d04f1)

### Link to the Bolt URL that caused the error

Bot.New.net

### Steps to reproduce

no

### Expected behavior

yes

### Screen Recording / Screenshot

no

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

### Additional context

Please answer fast we give you the payment of 5 Dollars 💵

**Comment by Intiiii** [comment]
are you saying that you are running deepseek locally on your computer? If thats the case, you can use ollama for example to choose it directly from the list

**Comment by dustinwloring1988** [comment]
please try the latest version if you are still having problems please open a new issue
