### ISSUE TITLE
FEATURE: Load github repositories similar to bolt.new

### ISSUE THREAD

**Issue by Craig-97** [coleam00/bolt.new-any-llm#27]
**Is your feature request related to a problem? Please describe:**

I'm unable to load my projects from github repositories like I can in the deployed version of bolt.new

**Describe the solution you'd like:**

However it can be done, bolt.new achieives it by just adding bolt.new into the github link like so:

`https://bolt.new/github.com/username/project-name`

Local project loading would be a good step until this is done as well which I've seen on the requested feature list already.
**Describe alternatives you've considered:**

**Additional context:**

**Comment by 80Builder80** [comment]
I'm sure this is one of their features for the paid version. Not all the features are open source. It is on the list of To Do's.

**Comment by MaximPro** [comment]
I think we all need a virtual local deployment base, that is easy copyable/importable to coolify or docker etc.
