### ISSUE TITLE
Can't select model from OpenaiLike

### ISSUE THREAD

**Issue by Intiiii** [coleam00/bolt.new-any-llm#271]
### Describe the bug

I know you can select a openai like api thingy, but is there a way to configure what model you want to use for it? by default it uses the claude-3-5-sonnet, as stated in the utils/constants.ts
![image](https://github.com/user-attachments/assets/6d800d53-a3da-4798-93b0-4dbf887ecb61)
but i cant figure out how to change it without changing the default model setting

### Link to the Bolt URL that caused the error

none

### Steps to reproduce

1. configure the env.local
2. run the project

### Expected behavior

you can select the model that you want to use

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/8700e66a-2bd1-459f-a3ca-7bd08ea292ad)
it looks like it wants to display something, but there is nothing to display 

### Platform

- OS: Windows
- Browser: Chrome
- Version: Latest

**Comment by the-Arka** [comment]
in .env set both:
OPENAI_LIKE_API_BASE_URL=
OPENAI_LIKE_API_KEY=
if it's still does not shows up, restart the bolt (happened to me few times)

**Comment by chrismahoney** [comment]
Please see #251 to keep track of provider refactors that will improve this support.

**Comment by dctfor** [comment]
@Intiiii 
This issue actually is the same as with Ollama, plz check [this other related issue](https://github.com/coleam00/bolt.new-any-llm/issues/259)
I currently have[ a PR for that](https://github.com/coleam00/bolt.new-any-llm/pull/306), may be not the best solution but it worked for me after several iterations for making it work

**Comment by chrismahoney** [comment]
Not familiar with Github Models yet, tagging this to be included in provider overview in #276 to make sure it's captured.
