### ISSUE TITLE
HOW DO I RUN BOLT ON GOOGLE CANARY

### ISSUE THREAD

**Issue by jameycb7** [coleam00/bolt.new-any-llm#272]
I have everything set up it seems I just now need to run the new bolt on the web browser on a local host

**Comment by Mouradif** [comment]
I get that it's frustrating when things don't work but the all caps title makes it sound like you're shouting at us, it doesn't really make people want to help.

Now let's still try. As you might expect, not everyone has your issue (it worked fine for me), could you say more about your setup? What OS are you running? Are you running the project with Docker? What error do you get when you open the browser at the URL served by Vite?

**Comment by chrismahoney** [comment]
Please use the [Bug Report issue template](https://github.com/coleam00/bolt.new-any-llm/issues/new?assignees=&labels=&projects=&template=bug_report.yml) and fill in as much information/context as you can about your issue. Thanks!

**Comment by jameycb7** [comment]
> I get that it's frustrating when things don't work but the all caps title makes it sound like you're shouting at us, it doesn't really make people want to help.
> 
> Now let's still try. As you might expect, not everyone has your issue (it worked fine for me), could you say more about your setup? What OS are you running? Are you running the project with Docker? What error do you get when you open the browser at the URL served by Vite?

Bro chill, I accidentally had caps on. If I wanted to show that I'm shouting I would add an exclamation point. I appreciate you wanting to help but I don't need all that extra stuff.

**Comment by jameycb7** [comment]
I'm running it on mac os. I have everything set up. I have chrome canary. I'm just wondering how do I now run the modified bolt.new. There's no error yet. I haven't initiated running it.
