### ISSUE TITLE
Latest changes nothing works anymore since adding Bolt Terminal etc

### ISSUE THREAD

**Issue by syndicate604** [coleam00/bolt.new-any-llm#277]
### Describe the bug

Sonnet3.5 cannot even make a simple premade prompt like the Space Invaders anymore it breaks and misses stuff and no previews work etc.

### Link to the Bolt URL that caused the error

localhost

### Steps to reproduce

Run the system prompts which used to work fine and all breakdown now

### Expected behavior

They work like they used to before latest commits

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/63886d2e-5555-4baa-912a-8f73cd6f76f8)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by chrismahoney** [comment]
Terminal and code streaming were initial priority, there are some issues with provider and model selection most likely responsible for this type of issue. Looking to push an update soon to address this, if interested keep tabs on #276.
