### ISSUE TITLE
Bolt (Offline / Non-Virtual Filesystem (stackblitz))?

### ISSUE THREAD

**Issue by x0BSCUREx** [coleam00/bolt.new-any-llm#284]
I want to be able to run this offline. no network just use localized / downloaded models from ollama or other websites.
i would also like it to not use (stackblitz) or virtual based filesystem. i want the code to be created on my pc in a selected directory.

**Comment by tzcat8** [comment]
个人认为你要找的可能是 cline/cline。
在我看来 bolt.new 的竞争力就在于「虚拟的文件系统」—— 基于WebContainers的浏览器开发环境。

Personally I think what you are looking for may be cline/cline.
In my opinion, the competitiveness of bolt.new lies in the "virtual file system" - a browser development environment based on WebContainers.

**Comment by wonderwhy-er** [comment]
I agree with @tzcat8 
Most interesting aspect of Bolt is that it can be hosted as website while code actually runs and is developed locally.
Its a very interesting feature making it very portable.

In theory it should work locally and sync with local file system is coming.

But we also are looking at making WebContainers dependency switchable to other options.
WebContainer probably will stay as default as its most portable option.

And, switching it out is a VERY big effort. So not sure when and who can get to that.
