### ISSUE TITLE
issue  escaltion issue

### ISSUE THREAD

**Issue by jachenms** [coleam00/bolt.new-any-llm#288]
**Is your feature request related to a problem? Please describe:**

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

**Comment by jachenms** [comment]
![image](https://github.com/user-attachments/assets/a2fc49b6-a0f9-494d-8086-941ba1061d2f)
 how to sovel the  issue

**Comment by Prathamesh-Shanbhag** [comment]
Duplicate #287
