### ISSUE TITLE
Ollama Models not showing up

### ISSUE THREAD

**Issue by openmoto** [coleam00/bolt.new-any-llm#29]
### Describe the bug

Ollama Models are not showing up
![image](https://github.com/user-attachments/assets/92164b03-9693-4ad9-a7c4-3227f92716c2)

### Link to the Bolt URL that caused the error

http://192.148.0.207:5173/

### Steps to reproduce

Environment :
Ollama on a standalone server http://192.168.0.22:11434, works with openwebui and other tools.
bolt.new installed on a development VM, OLLAMA_API_BASE_URL set on the .env.local file
initiate using pnpm run dev --host 
accessing the web UI from another computer, then select Ollama, but the Ollama models are not available to select

### Expected behavior

Select Ollama from the first list, second dropdown should show all models I've downloaded with ollama

### Platform

- OS: [Linux]
- Browser: [Chrome,]
- Version: [130.0.6723.59]

**Comment by CesarPetrescu** [comment]
![{A81B7803-DF92-481A-AE78-403CB287517A}](https://github.com/user-attachments/assets/14fc0c54-e1df-4fa3-9440-425daf709f5b)

Hello, i happen to have the same problem. Everything is wokring locally ( checked if ollama is running well with openwebUI) yet ollama's models arent showing on bolt.new

**Comment by saintman23** [comment]
same here

**Comment by vgcman16** [comment]
You have ollama downloaded ? And open

**Comment by midqc** [comment]
I was having the same issue. I had been running Ollama on Ubuntu (WSL) before, but I installed the Windows version, and it seems to be working now. However, local models like llama3.2 and deepseek-coder-v2 are not smart enough to follow the prompt guidelines. I also tried running `npm run dev` through WSL, but it didn’t work.

**Comment by fcools** [comment]
See also #43

**Comment by drabspirit** [comment]
I had to manually install ollama LLM's via cmd line. 
Make sure you have Ollama installed first by running;

`ollama -v`

Installed just these three to test first;

`ollama pull llama3.1`
`ollama pull codellama:7b`
`ollama pull gemma:2b`

Currently theyre not generating in the codebase/preview though :/ Idk exactly why

**Comment by AlexanderHanff** [comment]
Same issue here - have tried all of the fixes suggested in these issues threads but nothing fixes it.  Ollama is running and working fine and I have a web ui sat on top of it as well (which connects to Ollama's api) which also works and allows me to select models with no issues - but this bolt build will not allow me to select any Ollama models.

**Comment by fcools** [comment]
@AlexanderHanff 

It could be that your Ollama is only listening at localhost, that would explain why your webui is working because the webui is is running on the same machine as Ollama, hence for the webui Ollama is running on localhost.

You need to make Ollama listen on 0.0.0.0.
You can verify this in your browser, put the server address and port (eg. 192.168.1.202:11434) and Ollama has to respond with 'Ollama running'.

**Comment by AlexanderHanff** [comment]
> @AlexanderHanff
> 
> It could be that your Ollama is only listening at localhost, that would explain why your webui is working because the webui is is running on the same machine as Ollama, hence for the webui Ollama is running on localhost.
> 
> You need to make Ollama listen on 0.0.0.0. You can verify this in your browser, put the server address and port (eg. 192.168.1.202:11434) and Ollama has to respond with 'Ollama running'.

Nope my Ollama is running on 0.0.0.0:11434 (I get the message saying it is running when I hit 127.0.0.1:11434, localhost:11434 or 0.0.0.0:11434 and no matter what I put in the .env.local or if I change other files as suggested - I still cannot select any models.

I have exported OLLAMA_HOST=0.0.0.0:11434 as well.

**Comment by nowjon** [comment]
> > @AlexanderHanff
> > It could be that your Ollama is only listening at localhost, that would explain why your webui is working because the webui is is running on the same machine as Ollama, hence for the webui Ollama is running on localhost.
> > You need to make Ollama listen on 0.0.0.0. You can verify this in your browser, put the server address and port (eg. 192.168.1.202:11434) and Ollama has to respond with 'Ollama running'.
> 
> Nope my Ollama is running on 0.0.0.0:11434 (I get the message saying it is running when I hit 127.0.0.1:11434, localhost:11434 or 0.0.0.0:11434 and no matter what I put in the .env.local or if I change other files as suggested - I still cannot select any models.
> 
> I have exported OLLAMA_HOST=0.0.0.0:11434 as well.

I believe the new version should fix the Ollama issues, you also need to format this as 
OLLAMA_API_BASE_URL=http://%IP%:11434

**Comment by AlexanderHanff** [comment]
> > > @AlexanderHanff
> > > It could be that your Ollama is only listening at localhost, that would explain why your webui is working because the webui is is running on the same machine as Ollama, hence for the webui Ollama is running on localhost.
> > > You need to make Ollama listen on 0.0.0.0. You can verify this in your browser, put the server address and port (eg. 192.168.1.202:11434) and Ollama has to respond with 'Ollama running'.
> > 
> > 
> > Nope my Ollama is running on 0.0.0.0:11434 (I get the message saying it is running when I hit 127.0.0.1:11434, localhost:11434 or 0.0.0.0:11434 and no matter what I put in the .env.local or if I change other files as suggested - I still cannot select any models.
> > I have exported OLLAMA_HOST=0.0.0.0:11434 as well.
> 
> I believe the new version should fix the Ollama issues, you also need to format this as OLLAMA_API_BASE_URL=http://%IP%:11434

I can confirm that a new pull has fixed the Ollama models issue.

Many thanks.

**Comment by slnnz** [comment]
@drabspirit did you ever figure out how to make the code base load up on the right side. Mine works fine with an OpenAI api key but not with local ollama llm

**Comment by BLS-Aidan-Bromley** [comment]
I am having the same issue and can reach ollama from the pc I am running the bolt docker from as ollama is on a mac mini.

**Comment by noobydp** [comment]
@BLS-Aidan-Bromley can you access http://<macip>:11433 from your pc web browser?

If not you probably need to configure your ollama container with OLLAMA_HOST=0.0.0.0, docker port forwarding, and/or you macOS firewall to allow the port through

**Comment by BLS-Aidan-Bromley** [comment]
@noobydp I have done that and can connect to it, the issue is it is not picking the values up from the ENV file so I have had to hard code them in instead of using the default localhost one.

**Comment by ranedisk** [comment]
> > > > [@AlexanderHanff](https://github.com/AlexanderHanff)
> > > > It could be that your Ollama is only listening at localhost, that would explain why your webui is working because the webui is is running on the same machine as Ollama, hence for the webui Ollama is running on localhost.
> > > > You need to make Ollama listen on 0.0.0.0. You can verify this in your browser, put the server address and port (eg. 192.168.1.202:11434) and Ollama has to respond with 'Ollama running'.
> > > 
> > > 
> > > Nope my Ollama is running on 0.0.0.0:11434 (I get the message saying it is running when I hit 127.0.0.1:11434, localhost:11434 or 0.0.0.0:11434 and no matter what I put in the .env.local or if I change other files as suggested - I still cannot select any models.
> > > I have exported OLLAMA_HOST=0.0.0.0:11434 as well.
> > 
> > 
> > I believe the new version should fix the Ollama issues, you also need to format this as OLLAMA_API_BASE_URL=http://%IP%:11434
> 
> I can confirm that a new pull has fixed the Ollama models issue.
> 
> Many thanks.

Hi,I'm having the same exact issue with a fresh pull. I did update OLLAMA_API_BASE_URL=http://%IP%:11434 ,but same same issue.
  curl http://localhost:11434  , curl http://127.0.0.1:11434  , and   curl http://localIP:11434  
StatusCode        : 200
StatusDescription : OK
Content           : Ollama is running
RawContent        : HTTP/1.1 200 OK

All works, but not bolt.dyi.  I even updated my local env win=OLLAMA_HOST -0.0.0.0  , OLLAMA_ORIGINS *.
No luck.  I'm running bolt directly and tried using docker.  I originally had this running on proxmox and on linux but becasue of self hosted SSL issues, i'm trying to run it locally, but now cant get bolt to see the files even updating base URL with 127, localhost or the %:11434. nothing.  any ideas where one may look elsewhere? thank you

**Comment by nirmith99** [comment]
bro i uninstalled bolt.diy. i went back and forth for two hours. please i request the app devloper to update this bug. also even i am sharing the same problems as others.

**Comment by catclaw** [comment]
For heaven's sake! 
Can you fix this bug, please?
Ollama is running and is configured.

<img width="1931" height="1272" alt="Image" src="https://github.com/user-attachments/assets/a09f840c-215c-4e49-8bed-360880f88620" />

<img width="1929" height="1271" alt="Image" src="https://github.com/user-attachments/assets/d4e91c2e-2811-42cd-b2d7-01dc6523cc17" />

<img width="1112" height="627" alt="Image" src="https://github.com/user-attachments/assets/56276363-094b-47b8-8ad6-1462c0262eb9" />
