### ISSUE TITLE
 Failed to execute 'postMessage' on 'Worker': SharedArrayBuffer transfer requires self.crossOriginIsolated.

### ISSUE THREAD

**Issue by hellangleZ** [coleam00/bolt.new-any-llm#293]
### Describe the bug

![image](https://github.com/user-attachments/assets/6842047e-78c8-407f-a9a0-5b86c25da630)

Failed to execute 'postMessage' on 'Worker': SharedArrayBuffer transfer requires self.crossOriginIsolated.

### Link to the Bolt URL that caused the error

locallink

### Steps to reproduce

1- start bolt local
2- using xAI
3- let it create a website

### Expected behavior

create code

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/7691fc86-b299-4c52-a654-6a1944cf549d)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by hellangleZ** [comment]
[Symbol(vercel.ai.error)]: true,
  [Symbol(vercel.ai.error.AI_APICallError)]: true
}
undefined
undefined
^C(base) root123@A11:/aml/bolt.new-any-llm$ pnpm run dev --host

> bolt@ dev /aml/bolt.new-any-llm
> remix vite:dev "--host"

  ➜  Local:   http://localhost:5173/
  ➜  Network: http://172.16.2.5:5173/
  ➜  Network: http://172.16.2.250:5173/
  ➜  Network: http://172.18.0.1:5173/
  ➜  Network: http://172.17.0.1:5173/
  ➜  press h + enter to show help
undefined
undefined


still this error: undefined

**Comment by itinfserv** [comment]
did you solve this ?
