### ISSUE TITLE
High CPU and RAM Usage with Bolt.New

### ISSUE THREAD

**Issue by ahmedashraf443** [coleam00/bolt.new-any-llm#295]
### Describe the bug

When using language models that fit within my GPU (e.g., through Aider or OpenWebUI), they run smoothly, utilizing only the GPU and delivering optimal performance. However, when attempting to use the same models through Bolt.New, I encounter significant performance issues:

as soon as i send anything through bolt.new the ollama server spikes in both ram and CPU usage its as if im running a model that is a lot bigger not the same small model i am running.

### Link to the Bolt URL that caused the error

I used pnpm run dev to test it out before deploying

### Steps to reproduce

Load a language model that fits within the GPU using Bolt.New.
Observe CPU and RAM usage in the system monitor.
Note the token generation speed compared to other platforms.

### Expected behavior

The model should run smoothly, leveraging the GPU for computation, similar to its performance in other environments like Aider or OpenWebUI.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by zjjt** [comment]
i second this too. right now i am 1hour  into generating an app with phi3.5 model on my M1 mac 8gb ram. this is the only model which responded fast and could actually execute and preview code. the others only behaved like chat-gpt offering me solutions that i could implement myself....but 1h into it and still going it hasnt finished generating the package.json file...
Is there a way to smooth this out ?

**Comment by Shreyash113** [comment]
Same here high CPU and RAM Usage What will be the fix to this?

**Comment by ahmedashraf443** [comment]
yeah so I'm on windows so what I did was set it in the environment variables. After that, I restarted the Ollama process to ensure it picked up the changes. Unfortunately, the issue still persists. Any ideas on what else I could try?"

![image](https://github.com/user-attachments/assets/02f69901-6353-465d-8737-f372eb69db86)

**Comment by ahmedashraf443** [comment]
I already have that pre-configured, also when i send a prompt using bolt.new if i open a a command terminal and type ollama ps I can see that the model I picked is the only one that's running so I don't think the issue is that multiple models are being loaded

**Comment by dustinwloring1988** [comment]
this is an outdated version please try the latest and start a new issue if the problem persists

**Comment by kayahasan** [comment]
The problem persists.

**Comment by soifur** [comment]
has anyone found a fix to this?

**Comment by wassmi** [comment]
Problem persists, nothing has changed

**Comment by AbsoluteDanLab** [comment]
One more "the same issue". I have very fluent experience while talking with ollama (deepseek r1:8b), and high GPU usage can be seen in the monitor. But when I use bolt.diy, the output of tokens is very slow, meanwhile, high CPU usage is observed instead of the expected usage of GPU....

Could anyone find a solution to this?

**Comment by Hosselo** [comment]
Same problem, it seems to be balancing the load on the RAM, CPU and GPU.

**Comment by Anybody2007** [comment]
Same issue, it's using 50% GPU and 50% CPU. I am watching from 
```
ollama ps
```
