### ISSUE TITLE
Error processing request

### ISSUE THREAD

**Issue by ARIS-2004** [coleam00/bolt.new-any-llm#297]
**Is your feature request related to a problem? problem showing "There was an error processing your request: No details were returned
"
in the console its showing "hook.js:608 
 Warning: Encountered two children with the same key, `cohere/command`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version. Error Component Stack
 

i added a .env file and then ran it but still...

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

**Comment by amehat** [comment]
same issue

**Comment by swan01** [comment]
I'm also experiencing the same issue. I performed a clean install on the machine, and even installed a brand new instance of the app on another computer!  Any help would be gratefully appreciated. Thanks.

**Comment by Mika97400** [comment]
Hello.

Personnaly I had to create a new model with different name :

Ex:  `ollama create -f ./Modelfile qwen2.5-coder:7b-32k`

And use this model to get it work `qwen2.5-coder:7b-32k`

Hope it could help

**Comment by amehat** [comment]
Thanks, but I have the same error.

<img width="1158" alt="bolt-error-4" src="https://github.com/user-attachments/assets/1496dc1f-3adc-45fb-99d4-f8931670d2a3">

**Comment by Mika97400** [comment]
Just by the way you must keep the two models (original and 32k version)
What is your error code from browser?

**Comment by amehat** [comment]
I have a 500 error and I have kept the previous models

<img width="704" alt="bolt-error-5" src="https://github.com/user-attachments/assets/f032a623-332b-4eb6-b0c7-25f460972f90">
<img width="702" alt="bolt-error-6" src="https://github.com/user-attachments/assets/66b5e851-b930-4655-8aa9-39edf1d7a00a">

**Comment by amehat** [comment]
I solved the problem by changing the model

<img width="615" alt="bolt-success" src="https://github.com/user-attachments/assets/f01fad5d-2921-4e09-a872-1c21c0d5a625">

**Comment by Mika97400** [comment]
Where is running your ollama stack ? In docker ? Same VM PC MAC ?

**Comment by dvmac00** [comment]
I'm having the same issue, tried using OpenRouter and ChatGPT as providers  but the same error occurs

**Comment by dustinwloring1988** [comment]
Please try with the latest vanilla version of this fork
