### ISSUE TITLE
Cue this. Don't know what's wrong

### ISSUE THREAD

**Issue by alanblogooo** [coleam00/bolt.new-any-llm#300]
### Describe the bug

![image](https://github.com/user-attachments/assets/e01ec913-8dff-45ae-8e87-8b1414b32055)

### Link to the Bolt URL that caused the error

Cue this. Don't know what's wrong

### Steps to reproduce

Cue this. Don't know what's wrong

### Expected behavior

Cue this. Don't know what's wrong

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by pdichone** [comment]
Same here. and also the code panel preview is now showing or rendering nothing.

**Comment by rvpv** [comment]
Same problem with LM Studio

**Comment by 2xaltf4** [comment]
Clear cookies & browser data

**Comment by dustinwloring1988** [comment]
please try the latest version if you are still having problems please open a new issue
