### ISSUE TITLE
no .env.exmple found

### ISSUE THREAD

**Issue by bolognaa** [coleam00/bolt.new-any-llm#311]
### Describe the bug

hi

after cloning the folder using this git clone https://github.com/coleam00/bolt.new-any-llm.git

i can't find the env.exmple file 

why and how can I use it?

### Link to the Bolt URL that caused the error

.

### Steps to reproduce

hi

after cloning the folder using this git clone https://github.com/coleam00/bolt.new-any-llm.git

i can't find the env.exmple file 

why and how can I use it?

### Expected behavior

.

### Platform

- OS: macOS
- Browser: Chrome
- Version: 131.0.6778.69

**Comment by jpetro416** [comment]
Here is the file:
`
# Rename this file to .env once you have filled in the below environment variables!

# Get your GROQ API Key here -
# https://console.groq.com/keys
# You only need this environment variable set if you want to use Groq models
GROQ_API_KEY=

# Get your Open AI API Key by following these instructions -
# https://help.openai.com/en/articles/4936850-where-do-i-find-my-openai-api-key
# You only need this environment variable set if you want to use GPT models
OPENAI_API_KEY=

# Get your Anthropic API Key in your account settings -
# https://console.anthropic.com/settings/keys
# You only need this environment variable set if you want to use Claude models
ANTHROPIC_API_KEY=

# Get your OpenRouter API Key in your account settings -
# https://openrouter.ai/settings/keys
# You only need this environment variable set if you want to use OpenRouter models
OPEN_ROUTER_API_KEY=

# Get your Google Generative AI API Key by following these instructions -
# https://console.cloud.google.com/apis/credentials
# You only need this environment variable set if you want to use Google Generative AI models
GOOGLE_GENERATIVE_AI_API_KEY=

# You only need this environment variable set if you want to use oLLAMA models
# EXAMPLE http://localhost:11434
OLLAMA_API_BASE_URL=http://localhost:11434

# You only need this environment variable set if you want to use OpenAI Like models
OPENAI_LIKE_API_BASE_URL=

# You only need this environment variable set if you want to use DeepSeek models through their API
DEEPSEEK_API_KEY=

# Get your OpenAI Like API Key
OPENAI_LIKE_API_KEY=

# Get your Mistral API Key by following these instructions -
# https://console.mistral.ai/api-keys/
# You only need this environment variable set if you want to use Mistral models
MISTRAL_API_KEY=


# Get LMStudio Base URL from LM Studio Developer Console
# Make sure to enable CORS
# Example: http://localhost:1234
LMSTUDIO_API_BASE_URL=

# Get your xAI API key
# https://x.ai/api
# You only need this environment variable set if you want to use xAI models
XAI_API_KEY=

# Include this environment variable if you want more logging for debugging locally
VITE_LOG_LEVEL=debug

`

**Comment by bolognaa** [comment]
where is the file? its not attached :)

**Comment by bolognaa** [comment]
i wonder why its not there automatically after i follow the steps in the readme file

**Comment by tautist** [comment]
I have no idea how mac works, but a quick google Command + Shift + . (period) in the folder will display hidden files. possible shes tucked away in there

**Comment by bolognaa** [comment]
it worked! found it 
but now getting an error when trying to run it without docker: "pnpm run dev
 ERR_PNPM_NO_SCRIPT  Missing script: dev"

:\

**Comment by bolognaa** [comment]
anyone know how to fix it?

**Comment by TechHunter07** [comment]
Failed to spawn bolt shell

Failed to execute 'postMessage' on 'Worker': SharedArrayBuffer transfer requires self.crossOriginIsolated. following error I am facing

**Comment by dustinwloring1988** [comment]
the original issue is resolved correct? please open up a new issue for any other issues you still have so we can track them better.

**Comment by thecodacus** [comment]
closing this as the original issue is fixed
