### ISSUE TITLE
Astro Blog Prompt Fails to Install Dependencies on Linux Mint

### ISSUE THREAD

**Issue by zero2999** [coleam00/bolt.new-any-llm#315]
### Describe the bug

When attempting to execute the example blog prompt in Astro on Linux Mint, the project creation process is incomplete. Dependencies are not installed via npm, even after clearing the cache and reinstalling them. Additionally, the command execution during blog creation is noticeably slow.

I encountered the same issue with a to-do list prompt, where dependency installation was either incomplete or excessively slow.

### Link to the Bolt URL that caused the error

http://localhost:5175/chat/astro-blog-2

### Steps to reproduce

1. Download the Astro blog prompt project from Bolt.new.
2. Configure all required APIs as instructed.
3. Initiate the project creation process.
4. Observe that dependencies are not installed correctly via npm.
5. Clear the cache and attempt to reinstall dependencies.
6. Note the slow command execution during project creation.

### Expected behavior

The project creation process should successfully install all necessary dependencies via npm without delays or incompleteness.

### Screen Recording / Screenshot

![Captura de pantalla de 2024-11-17 23-00-03](https://github.com/user-attachments/assets/da22e68c-5cb0-4306-89a7-434dad0dbc07)

### Platform

- OS: Linux Mint 20
- Browser: Microsoft Edge (Version 131.0.2903.51)

**Comment by chrismahoney** [comment]
> The project creation process should successfully install all necessary dependencies via npm without delays or incompleteness.

That's right! There are a few moving parts related to successful one-shots of these example prompts, and they are absolutely a near-term priority. We may adjust the content/behavior of the sample prompts to reflect the current state of codegen going forward, at least I would like to recommend we do so.
