### ISSUE TITLE
Environment variables from .env.local not applied when starting project via Docker

### ISSUE THREAD

**Issue by dwichers** [coleam00/bolt.new-any-llm#317]
### Describe the bug

When starting the project via Docker and having filled in the .env.local file with API keys and URLs of local LLM systems, the environment variables are not being picked up. This forces manual entry of the values when starting the Docker project, despite the expectation that they would be automatically applied.

### Link to the Bolt URL that caused the error

http://localhost:5173/

### Steps to reproduce

1. Fill in the .env.local file with API keys and URLs for local LLM systems.
2. Start the project via Docker using the provided commands.
4. Observe that the environment variables from .env.local are not applied and require manual input during project initialization.

### Expected behavior

The environment variables specified in the .env.local file should be automatically applied when the Docker project starts, eliminating the need for manual entry.

### Platform

OS: Windows 11 24H2, OS Build: 26120.2222

Browsers Tested:
- Chrome (Regular), 130.0.6723.117
- Chrome Canary, 133.0.6844.0 
- Microsoft Edge, 131.0.2903.51

### Additional context

Docker deployment tested with valid .env.local configuration, the config works when starting with pnpm run dev

**Comment by radumalica** [comment]
it happens because that file matches a string in `.dockerignore` file. remove it from there and it will be available in the container

**Comment by octionicsolutions** [comment]
I commented out both .env and *.local and it finally worked for me. Thanks!
