### ISSUE TITLE
Support of 1MinAI API

### ISSUE THREAD

**Issue by JSmithOner** [coleam00/bolt.new-any-llm#318]
**Is your feature request related to a problem? Please describe:**

No

**Describe the solution you'd like:**

Support of the 1MinAI API

**Describe alternatives you've considered:**

implementing it myself

**Additional context:**

Here is the link to [1MinAI](app.1min.ai)
and the [documentation](https://gleaming-wren-2af.notion.site/1min-AI-API-Docs-111af080bd8f8046a4e6e1053c95e047) of the API

**Comment by JSmithOner** [comment]
@dustinwloring1988 hello. why is this marked as completed?Thanks in advance

**Comment by dustinwloring1988** [comment]
> @dustinwloring1988 hello. why is this marked as completed?Thanks in advance

It will be added to the readme, sorry not meaning completed as added

**Comment by JSmithOner** [comment]
@dustinwloring1988 oh ok well I've opened up a new feature request.Thanks

**Comment by dustinwloring1988** [comment]
thanks I see it and tagged it
