### ISSUE TITLE
Error: No route matches URL "/sw.js"

### ISSUE THREAD

**Issue by nigelp** [coleam00/bolt.new-any-llm#319]
### Describe the bug

Install app
Run 'run dev'
go to http://localhost:5173/
Not able to access API key setup
CMD modal showing Error: No route matches URL "/sw.js"
Examine \public and no sw.js is there. 

### Link to the Bolt URL that caused the error

http://localhost:5173/

### Steps to reproduce

Install app
Run 'run dev'
go to http://localhost:5173/
Not able to access API key setup
CMD modal showing Error: No route matches URL "/sw.js"
Examine \public and no sw.js is there. 

### Expected behavior

I expected to be able to access the API key set up. I had already entered in the keys in .env, but still no access. Also the models are showing but no way to trigger the API key setup.

### Platform

Windows 10, 
Firefox

**Comment by chrismahoney** [comment]
Hmmm, this is an unusual one, but I did notice you're using Firefox; the recommended browser to use due to differences in major Chromium versions is Chrome Canary. Please try that instead and report back if you see the same results.

**Comment by nigelp** [comment]
@chrismahoney ah thanks, that worked. Great. The only tiny glitch is the API key box seems broken. Or maybe that's how it should be? I can't add more keys, unless I use .env. see attached. 
![apikeybox](https://github.com/user-attachments/assets/ac9bc538-5c11-4abd-903a-cecbe0bc5111)

**Comment by chrismahoney** [comment]
Glad that helped :) The message is a bit misleading, but there may be some issues with the API key box. Roadmap discussion is taking place this week and I think we'll be taking a look at API setup holistically to resolve outlying issues.

**Comment by nigelp** [comment]
Great, thanks @chrismahoney I will do. 🙂

When you're in the meeting could you ask why 'code revert' is not higher up the roadmap list? Seems to me it's one of the most compelling features from the original Bolt.new platform.

**Comment by nigelp** [comment]
Cool. This video from Bolt.new is extremely interesting I think. :) Have a
good day.

https://www.youtube.com/live/Y0g_9ZhqiRg
