### ISSUE TITLE
Ollama models missing from dropdown

### ISSUE THREAD

**Issue by hardj300** [coleam00/bolt.new-any-llm#320]
### My setup details
 Ollama + OpenWebUI container and the Bolt container are both running on the same ubuntu VM host.  

### Error message
When I browse to bolt from any machine on my LAN I am met with a CORS error in the browser.  
![image](https://github.com/user-attachments/assets/0cfb8e29-d842-4c2f-b1e7-7d418463c7fa)

### Link to the Bolt URL that caused the error

http://<ANY_LAN_IP>:5174

### Validated Bolt container can curl to Ollama just fine.

1. Open browser on and local LAN machine to Bolt server ip:port
2. Switch first drop down to Ollama
3. Second drop down is blank
4. Right click on second drop down and select "inspect"
5. Click on console
6. See error regarding CORS header
![image](https://github.com/user-attachments/assets/4f4d006f-2ee4-4a0a-9b47-6e7391b2d6fb)

### Expected behavior

I would like to be able to run bolt as a container on a server VM.  Perhaps this is more of a feature request?

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/c1fdc615-07af-4dd4-be0a-14425f367fe6)

### VM Running on Proxmox
linux x86_64 Ubuntu 24.04.1 LTS
Docker Engine 27.3.1 (API: 1.47)
Ollama and Bolt running in two different containers

### Additional context

I would love to help troubleshoot this or test as needed.

**Comment by chrismahoney** [comment]
Is the 172.* IP address you're acccessing your local machine? If so, localhost is less restrictive about the COOP/other origin-based issues you're running into. I believe this requires a code change on the server side to account for COOP, etc. - If you can in the meantime, please try localhost if possible and I'll put some notes together for update of those cross-origin headers.

**Comment by hardj300** [comment]
The 172 IP is the IP of the doker host (ubuntu server VM).  I am accessing Bolt from a different IP on the same 172.16.1.1/24 LAN.  When I use localhost I am seeing 403 forbidden errors in addition to the above error.  I will test more tonight in order to get a detailed screenshot for you.

**Comment by chrismahoney** [comment]
Right, 172.16 is generally a docker network. Will standby for any more details, thanks!

**Comment by hardj300** [comment]
> Is the 172.* IP address you're acccessing your local machine? If so, localhost is less restrictive about the COOP/other origin-based issues you're running into. I believe this requires a code change on the server side to account for COOP, etc. - If you can in the meantime, please try localhost if possible and I'll put some notes together for update of those cross-origin headers.

172.16.1.1/24 is my local lan.  Ollama and bolt containers both running inside my ubuntu server VM at 172.16.1.19.  Changing to localhost results in the same error.  Attached is the new screen shot showing the additional 403 errors.  This has me stumped. 
![image](https://github.com/user-attachments/assets/ca595441-59d5-4eb6-b279-c25849382ebc)

Thanks for the help so far.

**Comment by sroller** [comment]
I have the same problem. I run Bolt via pnpm run dev --host.

The line .env.local is set to
`OLLAMA_API_BASE_URL=http://localhost:11434`
the interface shows
![image](https://github.com/user-attachments/assets/4a48f957-5857-4b31-b320-8ce0fb58b1b3)

What can I do?

**Comment by Mika97400** [comment]
Hello.

The request to ollama seems to be send from the browser not from the server. Personnaly I had to move to the server to test bolt.new because my ollama is only open to localhost.
For docker you can use http://host.docker.internal:11434 to connect to docker host.

Hope it could help.

**Comment by TarikTS** [comment]
Hello, 
I've managed to gain access to the models by finding this topic : 
You need to edit the /etc/systemd/system/ollama.service and add in [service] : 
Environment="OLLAMA_ORIGINS=*"

Then do a systemctl daemon-reload and systemctl restart ollama

Source from https://medium.com/dcoderai/how-to-handle-cors-settings-in-ollama-a-comprehensive-guide-ee2a5a1beef0

**Comment by sroller** [comment]
@TarikTS What configuration do you run?
Ollama on Linux, browser on  the same machine (Linux) or from a different machine (Windows?).

**Comment by dialbat** [comment]
> Hello, I've managed to gain access to the models by finding this topic : You need to edit the /etc/systemd/system/ollama.service and add in [service] : Environment="OLLAMA_ORIGINS=*"
> 
> Then do a systemctl daemon-reload and systemctl restart ollama
> 
> Source from https://medium.com/dcoderai/how-to-handle-cors-settings-in-ollama-a-comprehensive-guide-ee2a5a1beef0

Hello Tarik,

Does Environment="OLLAMA_ORIGINS=*" need to be added as a separate line, or at the end of my existing environment path?
thank you

**Comment by TarikTS** [comment]
@dialbat : This should be added under the section [Service] in /etc/systemd/system/ollama.service as explained in the link like this : 
[Service]
Some stuff you have
Environment="OLLAMA_ORIGINS=*"

**Comment by av** [comment]
For the folks on Linux, 172.17.0.1 is the host's address both on the host itself and within the container.

**Comment by sroller** [comment]
@TarikTS thank you for your comment.
What‘s your value for OLLAMA_API_KEY? Is it http://localhost:11434 ?

**Comment by TarikTS** [comment]
@sroller, i have put network_mode: host under my docker-compose file so my Ollama api key is the IP adress of my machine with the ollama port.

**Comment by dustinwloring1988** [comment]
this should be fixed now

**Comment by hardj300** [comment]
I just performed a fresh pull / install and the issue is not resolved for me.  Perhaps this is the same as #343.

**Comment by hardj300** [comment]
I apologize for not adding the error I see in the browser console window.  It seems I am getting 403 forbidden when using http://172.16.1.19:11434 as my Ollama API URL.  172.16.1.19 is my docker host. I am accessing Bolt from a browser on 172.16.1.13 and getting the 403 forbidden error.

**Comment by hardj300** [comment]
I just changed the .env.local file to reference http://localhost:11434 and now the error is "connection refused"  likely because ollama is not running at localhost but instead at 172.16.1.19 within my local network.

**Comment by hardj300** [comment]
For further clarity.  I have no issues running "curl http://172.16.1.19:11434/api/tags" on the 172.16.1.13 host.  Thanks for all the help

**Comment by h4de5** [comment]
host.docker.internal is only working on windows (and mac). in a remote setup (where ollama and/or bolt is not running on localhost, but on a different computer) localhost or a linux equivalent of host.docker.internal won't work. we need to put the ip of the server where ollama is running.
and the problem is (also described in #343) that the browser does not allow a certain needed browser functionality when there are multiple hosts (ollama and bolt) involved.

**Comment by Mika97400** [comment]
Remember that when you use ollama in a container, it's like ollama is running on a different host then Bolt.new, they only share same network. So you need to set ollama to listen outside localhost. It could not be a problem with Bolt.new
[https://github.com/ollama/ollama/blob/main/docs/faq.md](url)
![image](https://github.com/user-attachments/assets/cce43cad-86a7-477e-931a-ea9ec263b236)
Or with this method depending on your configuration
Environment="OLLAMA_ORIGINS=*"

**Comment by h4de5** [comment]
It is not an issue on ollama side - ollama works fine with severa other containers that use it's API.
the problem is the bolt UI - which connects to the bolt webui (which is running on the network) and it tries to send messages to ollama (which is also running on the network).

the browser will only allow to use certain features (e.g. SharedArrayBuffer, [see issues](https://github.com/search?q=repo%3Acoleam00%2Fbolt.new-any-llm+SharedArrayBuffer&type=issues)) as long as those services are either running on localhost or when certain headers + valid certificates (and valid domains) are in place.

for public llms - like openai which is hardend and use tokens for authentication - this works fine. ollama does not have such a token auth - so not a good idea to make the ollama api reachable through a public hostname.

**Comment by spratling** [comment]
I'm not running in docker but also got connection refused from Ollama. I had to use the IPs in .env.local like:
OLLAMA_API_BASE_URL=http://127.0.0.1:11434

**Comment by SarveshM213** [comment]
i dont know if its a solution but i started to get the ollama second drop down box
here is what i did:
i set up everything normally
then i opened the bolt.new folder that is the project folder in vscode i am on fedora workstation
now i tried ollama list on terminal in vs code
after that i just opened pnpm run dev
![Screenshot From 2024-12-22 13-32-36](https://github.com/user-attachments/assets/9b05421d-9029-417a-b980-e9e0029dfc30)
 and viola i got them

**Comment by hardj300** [comment]
I found my issue with ollama models not populating in the drop down.  The
issue was actually with Ollama container missing an environment variable.
I added the environment variable OLLAMA_ORIGINS=* and now it’s working.

**Comment by AcmeGamers** [comment]
After searching for Eons, finally found the issue with a solution

### How to Fix
- Open `bolt.diy` in your vscode
- Press `Ctrl + P` and type `stores settings`
- - Or simply open the file present in `app/lib/stores/settings.ts`
- Press `Ctrl + F` and search for `enabled: !LOCAL_PROVIDERS.includes(provider.name),`
- Change 
- - from = `enabled: !LOCAL_PROVIDERS.includes(provider.name),` 
- - to    = `enabled: LOCAL_PROVIDERS.includes(provider.name),`

And lastly, make sure in `.env.local`, your API key is set properly `OLLAMA_API_BASE_URL=http://127.0.0.1:11434`

### Resolution
This way, it should show you the list of the models you are using

![Local Model Fix](https://github.com/AcmeGamers/random/blob/main/ollama_model_fix.png?raw=true)

### Additional Fixes
Les say, in case if it still doesn't show you, here are few things I recommend doing:

#### Ollama Checks

##### Check 1
- Visit the URL http://127.0.0.1:11434/
-  [ ] Does the page says `Ollama is running`
- - If yeah, neat!
- - If not, open cmd and write `ollama serve &`
- - - If the command doesn't work, reinstall ollama
- - - Else visit the URL http://127.0.0.1:11434/ - and it should work

##### Check 2
- Open cmd and write `ollama list` 
-  [ ] Does it show a list of models?
- - If yeah, neat!
- - If not then you need to add your models using `ollama run modelName` (e.g. `ollama run llama3.1:latest`)

##### Check 3
- Visit the URL http://127.0.0.1:11434/api/tags
- - At top right corner of the page, it says `pretty-print`, check mark that [not necessary, can be skipped]
- - Press `Ctrl + F`
- - From check 2 above, you got a list of models using `ollama list` in cmd
- - Search for one model name (e.g. `llama3.1:latest`)

##### Check 4 [cause wai not]
This was me messing around and you can totally skip this, this step is debugging stuff, not fix

But if your bolt application is running 
- Go to url http://localhost:5173/api/models/Ollama
- - At top right corner of the page, it says `pretty-print`, check mark that [not necessary, can be skipped]
- - The first few lines of codes are the names of the ollama models you have installed in your system

### You have completed all ollama checks
Congratulations, now try working with your bolt, it should work

Make sure in `.env.local`, your API key is set properly `OLLAMA_API_BASE_URL=http://127.0.0.1:11434`

Saying it again cause I didn't xD

Though, hope it helps! :D

**Comment by Mugane** [comment]
OMG WHY would this be disabled by default and not mentioned anywhere in the docs? The hours lost. Ugh.
Thank you @AcmeGamers! I did also find a setting for this in the UI under "local providers". I think you can just change it there. However, you will still need to potentially change the .env.local vars and ensure that if you're in docker you add the right networks to each container you are running so they can talk to each other.
