### ISSUE TITLE
Bad default model

### ISSUE THREAD

**Issue by moas** [coleam00/bolt.new-any-llm#331]
this line https://github.com/coleam00/bolt.new-any-llm/blob/main/app/components/chat/Chat.client.tsx#L78-L80 causes a 500 error for me as I don't have this model active. I use Ollama with the Qwen2.5 Coder 14B model.

**Comment by chrismahoney** [comment]
Would a quick fix for this be defining no default model from the get-go? I just tried that and it seemed fine, but I don't have time just yet to look into it myself. No default model, cookies deleted was able to auto-select Anthropic & Sonnet (new), with Ollama loading my model list OK.

@wonderwhy-er Any thoughts?

**Comment by dustinwloring1988** [comment]
please try the latest version, this should be fix
