### ISSUE TITLE
Please make the ollama context length a config or env setting

### ISSUE THREAD

**Issue by matiashegoburu** [coleam00/bolt.new-any-llm#334]
Hi all, I noticed the context length for ollama has been hardcoded to 32k, would it be possible to make it a configurable value somehow? Either a env variable, or a config setting somewhere? I have the ability to run longer context windows, but I am not sure how to set it up without modifying the code. Thanks!

**Comment by chrismahoney** [comment]
Anyone with similar issues, please refer to the links above 🙌
