### ISSUE TITLE
Stuck in a "Create `index.html`" loop

### ISSUE THREAD

**Issue by ItsJamesMurray** [coleam00/bolt.new-any-llm#335]
### Describe the bug

I am trying to use LM Studio and `meta-llama-3.1-8b-instruct`.  When creating a site I am stuck in a loop where it constantly creates, then recreates, `index.html`.  

It has occurred on each of my 3 attempts with different LLMs loaded via LM Studio.

### Link to the Bolt URL that caused the error

http://localhost:5173/chat/my-website

### Steps to reproduce

1. Start a new chat
2. Select "LM Studio" and your LLM
3. Enter a description
4. Hit Enter
5. Wait for your laptop to have an asthma attack while looping in the `index.html` loop

### Expected behavior

After submitting a prompt it would progress through the steps required to preview a site based on my prompt.

### Screen Recording / Screenshot

<img width="216" alt="image" src="https://github.com/user-attachments/assets/07c2288b-410c-490b-b5ac-b45710080030">

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by dustinwloring1988** [comment]
please try the latest version, this should be fixed
