### ISSUE TITLE
HTML Entities Output Instead of JSX Tags (<View> appears as &lt;View&gt;)

### ISSUE THREAD

**Issue by rushter777** [coleam00/bolt.new-any-llm#336]
### Describe the bug

All .js files containing JSX syntax (e.g., <View>, <Card>, etc.) are incorrectly outputting HTML entities instead of JSX tags. For instance, <View> and <Card> render as &lt;View&gt; and &lt;Card&gt;, affecting the readability and functionality of the UI.

### Link to the Bolt URL that caused the error

localhost:5173

### Steps to reproduce

1.	Open any .js file with JSX content.
2.	Render the file to view the output.
3.	Observe that all JSX tags (e.g., <View>, <Card>) appear as HTML entities (&lt;View&gt;, &lt;Card&gt;).

### Expected behavior

JSX tags should render correctly as <View> and <Card> without being converted to HTML entities.

Actual behavior: All JSX tags render as HTML entities (e.g., <View> renders as &lt;View&gt;), causing incorrect display and making debugging more challenging.

### Platform

- OS: macOS
- Browser: Chrome Canary

### Additional context

This issue might be due to encoding configuration or a component processing bug that automatically escapes HTML entities in JSX.

**Comment by chrismahoney** [comment]
Could you please share the prompt you used where you encountered this issue? It sounds rare but I'm curious as to why that's happening.

**Comment by rushter777** [comment]
I missed this. I was only testing it after an update when it did this. It is not happening now. Other issues I'm finding I'll post later. Sorry for the delay.
