### ISSUE TITLE
LiteLLM Proxy Support

### ISSUE THREAD

**Issue by bakes82** [coleam00/bolt.new-any-llm#34]
Instead of adding each LLM individually why not support LiteLLM Proxy, this allows for almost every LLM and it simplifies the process and it has endpoints for to get the models. It also supports other auth methods other than just api key. We use Azure OpenAi but in the enterprise world we dont allow auth via api keys we have to use service principals and we require some other headers to be passed over, so this proxy supports all our custom auth.

https://docs.litellm.ai/docs/proxy/quick_start

**Comment by HomeDev68** [comment]
But isn't  litellm complex to setup most times, you have to deal with config files, and docs. I think people prefer a straight of the box solution that does not need extra config. At least that what I think about litellm.

**Comment by edv-sml** [comment]
litellm provides an openai like api - so maybe it should work with the OPENAI_LIKE_API_BASE_URL?
