### ISSUE TITLE
Sass @import rules are deprecated and will be removed in Dart Sass 3.0.

### ISSUE THREAD

**Issue by opalsignum** [coleam00/bolt.new-any-llm#342]
### Describe the bug

Multiple console error message when running on local host.

<img width="1377" alt="Bildschirmfoto 2024-11-20 um 04 44 52" src="https://github.com/user-attachments/assets/15b5bf84-6885-4ea0-b4cd-2e3b04aa0099">

### Link to the Bolt URL that caused the error

http://localhost:5173/

### Steps to reproduce

1. Run npm run dev

### Expected behavior

No warnings should come in console

### Platform

- OS: macOS
-  Terminal

**Comment by dustinwloring1988** [comment]
fixed
