### ISSUE TITLE
Enhance Prompt function appears to not work

### ISSUE THREAD

**Issue by Freffles** [coleam00/bolt.new-any-llm#35]
### Describe the bug

After entering a prompt and clicking on the "Enhance Prompt" symbol, the prompt box is cleared and no enhanced prompt appears

### Link to the Bolt URL that caused the error

None

### Steps to reproduce

As described

### Expected behavior

The user provided prompt should be replaced with an enhanced prompt

### Platform

Windows 10

**Comment by BenjaminKeating1986** [comment]
same here, the prompt for it though is
"I want you to improve the user prompt that is wrapped in \`<original_prompt>\` tags.
IMPORTANT: Only respond with the improved prompt and nothing else!"

could just use that in chat GPT or a local model

**Comment by jgrisafe** [comment]
We should figure out what they use on https://replit.com/ because their prompt enhancer is amazing.
