### ISSUE TITLE
Revert didn't work, but fork did kind of work

### ISSUE THREAD

**Issue by nigelp** [coleam00/bolt.new-any-llm#352]
### Describe the bug

I pressed the Revert button to go back up a prompt. It did a lot of code wrangling, but at the end no preview was shown. However when I pressed Fork, it again did code wrangling and this time it went back to the previous prompt, except it lost all the design features.

### Link to the Bolt URL that caused the error

http://localhost:5173/

### Steps to reproduce

1. click on revert. 
2. App flashed through code changes. 
3. Ends up with no Preview (and assume therefore, no reversion?)
4. Click on Fork.
5. App does code changes
6. Preview shows, but with lost design elements (bare HTML it looks like)
7. When trying to fix design, again breaks. 
8. Fork again goes back to bare app with no design. 
9. Design completely gone in Bolt (looks lovely in the local Dev mode though, but no way to get it up to Bolt?)

### Expected behavior

I hoped the dev app would revert to an earlier prompt, and remove the code which was causing the issue. 

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]
Windows 10
Chrome Canary

**Comment by dustinwloring1988** [comment]
this should be fixed now
