### ISSUE TITLE
The operation is insecure.

### ISSUE THREAD

**Issue by jacocal** [coleam00/bolt.new-any-llm#362]
### Describe the bug

When Bolt is writting to file, a series of pop-up errors come up stating "The operation is insecure."

Only happens on the first prompt, but the following ones get bugged

### Link to the Bolt URL that caused the error

http://localhost:5173/chat/astro-blog-3

### Steps to reproduce

1. Choose a source (I chose Mistral)
2. Choose a model (I chose Mistral 7B)
3. Make a prompt (I prompted Build a simple blog using Astro)
4. LLM will start faltering on screen and the series of pop-ups will be triggered

### Expected behavior

Bolt to start programing and adding code to files, running commands on terminal and showcasing a preview of project

### Screen Recording / Screenshot

https://github.com/user-attachments/assets/3c2334b3-80a0-4e8e-a613-2b45a8fac82d

### Platform

- Windows (WSL)
- Firefox
- Version: 132.0.2

**Comment by dustinwloring1988** [comment]
this is fixed now

**Comment by stormbkk87** [comment]
I still get this error "The operation is insecure" in the current build of bolt.diy using the example todos with Tailwind prompt.

<img width="1169" alt="Screen Shot 2024-12-21 at 12 16 09 PM" src="https://github.com/user-attachments/assets/86acd168-4ae4-4733-9bca-5e4e1a1c2684" />

**Comment by DjarallahBrahim** [comment]
hello

i'm having the same problem with v0.0.3


Screenshot:

![image](https://github.com/user-attachments/assets/bcd46a33-a241-4ee5-a4fd-2a2a1b242c3e)


Scenario:

clone the project.

- swithc to v0.0.3 tag
- change the api key to deepseek v3.
- Run my prompt.
