### ISSUE TITLE
Docker issue 

### ISSUE THREAD

**Issue by NvidiaShadowClone** [coleam00/bolt.new-any-llm#370]
**I am getting this while running the docker command while installing** 

>npm run dockerbuild
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path F:\ai\ai coder(bolt)/package.json
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, open 'F:\ai\ai coder(bolt)\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

**Comment by chrismahoney** [comment]
If I had to guess, perhaps this is an issue with the parentheses and slash usage in the file path? Can rule that out by duplicating the `ai coder(bolt)` directory without (bolt) on the end and try running again. Make sure to use `pnpm` as well as the lock file is based on it.
