### ISSUE TITLE
Folders not creating what it suppose to do

### ISSUE THREAD

**Issue by k2an** [coleam00/bolt.new-any-llm#381]
### Describe the bug

I tried to test about huggingface qwen2.5-coder.  and enter the prompt Design an accounting application with a modern, sleek, and animation-rich user interface. The project should be developed using Next.js and shadcn.  than voila :) and this happens all model local. what am i wrong about. 
![image](https://github.com/user-attachments/assets/23db1130-409c-48e7-9154-2039f37b9167)

### Link to the Bolt URL that caused the error

http://localhost:5173/chat/accounting-app-nextjs-shadcn

### Steps to reproduce

Just selected Hugging face and qwen 2.5 and enter the prompt than you will(i suppose) get the same error. 

### Expected behavior

Create a right folder structure and add shadcn properly. Thanks for you all great effort.

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/23db1130-409c-48e7-9154-2039f37b9167)

### Platform

- OS: [ Windows]
- Browser: [Chrome,Arc,Brave]

**Comment by leex279** [comment]
I´ve got the same problems with nextjs. It creates a app-folder while init, but the further steps / implementations of bolt, not putting it into the app, instead putting it directly in the root.

**Comment by dustinwloring1988** [comment]
did the newest version fix this?

**Comment by k2an** [comment]
Yes thanks for this great effort. Nicely done!
