### ISSUE TITLE
issue with Pinokio Bolt API Request

### ISSUE THREAD

**Issue by baraka78** [coleam00/bolt.new-any-llm#389]
Hello,

I recently installed Pinokio Bolt, but I am encountering an issue when trying to make API requests. The response always returns the following error:

yaml
Copier le code
There was an error processing your request: No details were returned.
I’ve ensured that the setup is correct, but the issue persists. Could you please help me understand what might be causing this error or guide me on how to resolve it?

Thank you in advance for your assistance!

Best regards,

**Comment by filipenava** [comment]
It didn't work here, I have the same problem when using the open ia api where I get the following error (There was an error processing your request: No details were returned)

**Comment by xXSamuXx** [comment]
I have the same problem, even inserting the openai API gives me this problem

**Comment by filipenava** [comment]
on Twitter I saw how to use the open AI api, but even with other apis I still have the same error, I think I'll try to reinstall here

**Comment by dustinwloring1988** [comment]
since there has not been anything further I will close this please open a new issue if you get any more errors.
