### ISSUE TITLE
Is there any chance someone can merge this excellent Backup/Restore/Clone function in the repo?

### ISSUE THREAD

**Issue by nigelp** [coleam00/bolt.new-any-llm#390]
**Is your feature request related to a problem? Please describe:**
The problem is Bolt is currently one way only. This feature would give the power to save and import projects from Github and work on them from at leisure.

Once you've done a Bolt initial project, there's no way to work on it again easily. Because there's no import function.

**Describe the solution you'd like:**
Merge this feature -

https://github.com/burgil/bolt.new-any-llm_windows

**Comment by kustomzone** [comment]
There's a second version of "import from Github" under review which seems to also work.
I've folded both methods in with my own pull method (which uses a token as needed for private repos) along with other UI pre-merges as a compatibility test.  Merging mine is therefore not easy, thou as an app installer it's under construction.

https://github.com/coleam00/bolt.new-any-llm/pull/395

**Comment by nigelp** [comment]
Oh wow, that's great news. So I'm assuming we'll get something integrated soon, once the options have been refined and checked?

**Comment by kustomzone** [comment]
For now [burgil's](https://github.com/burgil) is best as it adds the repo to Bolt's context after page reload so is available to chat about.   ([example](https://github.com/kontains/selectron/blob/main/Selectron_2024-11-24.md))

[thecodacus](https://github.com/thecodacus) has enquired about this before merging the new one.

**Comment by nigelp** [comment]
I think I'm just going to wait until all the dust has settled and something concrete has been merged into the main repo before taking a plunge. :)

**Comment by burgil** [comment]
BTW this is the issue where I solved it all if anyone is interested how it was done: https://github.com/coleam00/bolt.new-any-llm/issues/382
