### ISSUE TITLE
Ollama Qwen Enhance prompt not working

### ISSUE THREAD

**Issue by Jordain** [coleam00/bolt.new-any-llm#394]
### Describe the bug

When I select Ollama and select the Qwen2.5-coder:32b (32.8B) model and try and click enhance prompt. I get Invalid or missing provider. I am guessing that it's looking for an API key, but since it's a local model that's downloaded there isn't one. How do you get around that?
![image](https://github.com/user-attachments/assets/ae8058c3-62ac-451e-a722-1015d1e1c79e)

### Link to the Bolt URL that caused the error

localhost

### Steps to reproduce

Select Ollama
Select qwen2.5-coder:32b (32.8B)
type in create a todo web app
click enhance
![image](https://github.com/user-attachments/assets/f1c79f68-7aca-424d-b8af-1a92fad34de8)

### Expected behavior

enhancing the prompt.

**Comment by eburakars** [comment]
I have a similar problem, I send the request but nothing changes

**Comment by dustinwloring1988** [comment]
it is fixed in the latest version
