### ISSUE TITLE
LMStudio does not list models

### ISSUE THREAD

**Issue by tdnghia98** [coleam00/bolt.new-any-llm#398]
### Describe the bug

The LMStudio provider seems to hit the LMStudio endpoint but it does not show the available models to the user

### Link to the Bolt URL that caused the error

/

### Steps to reproduce

1. Start LMStudio server
2. Mount a model
3. Choose LMStudio as provider
4. List available models

### Expected behavior

The available models should contain mounted models in LMStudio

### Platform

- OS: macOS
- Browser: Chrome
- Version: https://github.com/coleam00/bolt.new-any-llm/commit/7fc8e40c031aee5a3d4edf86f72951038e99886a

**Comment by wonderwhy-er** [comment]
Weird, worked for me before, i even showed it in a video

**Comment by ero** [comment]
I have same issue. I use LM studio on second machine trough LAN. Tested from server if possible to curl it, so its available.

LM studio does not require key, IMO?
I have added into .env the line:
LM_STUDIO_URL=$LM_STUDIO_URL

**Comment by jojiathomas** [comment]
i had similar issue, when i changed the LM Studio Url to http://localhost:1234/v1, the model was loading.

**Comment by jimff** [comment]
> ### Describe the bug
> 
> The LMStudio provider seems to hit the LMStudio endpoint but it does not show the available models to the user
> 
> ### Link to the Bolt URL that caused the error


Were you able to solve this?  I have the exact same problem.  adding v1 did not work.

**Comment by wonderwhy-er** [comment]
Can you share link on which you access bolt
Like ip or local host

But also share full link on which you access lm studio

For me its:
bolt:
http://localhost:5173/

lm studio
http://localhost:1234/v1/models

![Image](https://github.com/user-attachments/assets/18ffc9c9-9911-42ea-af8c-1cccc6bbf02b)

Though we are not logging url on which we get the list
Needed to add console log to lmstudio.ts file

If its not working for you I would expect some kind of cross domain access issues
I think I heard people having trouble with docker and lmstudio

**Comment by jimff** [comment]
Hi, tx,
I use the exact same links, and the models get returned fine as well als you can here:
{
  "data": [
    {
      "id": "deepseek-r1-distill-llama-8b",
      "object": "model",
      "owned_by": "organization_owner"
    },
    {
      "id": "hermes-3-llama-3.2-3b",
      "object": "model",
      "owned_by": "organization_owner"
    },
    {
      "id": "text-embedding-nomic-embed-text-v1.5",
      "object": "model",
      "owned_by": "organization_owner"
    }
  ],
  "object": "list"
}
I've tried putting in bolt.diy providers LM Studio link both http://localhost:1234/v1/models and http://localhost:1234 as the last one I see used in YouTube video's here and there.  However my bolt.diy is running in docker.  Could that be the issue then?

**Comment by jimff** [comment]
I was running 0.0.5.  Now tried with the latest 0.0.6 and it works now!
