### ISSUE TITLE
Create a upload area 

### ISSUE THREAD

**Issue by abhi634367** [coleam00/bolt.new-any-llm#399]
There  is no way to upload my project files to bolt. add a option to upload the files.

If its already there please tell me how to do it.

**Comment by lrivera27** [comment]
If you go [here](https://github.com/coleam00/bolt.new-any-llm?tab=readme-ov-file#requested-additions-to-this-fork---feel-free-to-contribute), it's a High Priority Item listed.

**Comment by dustinwloring1988** [comment]
check out the latest version
