### ISSUE TITLE
Deploying Bolt on Vercel fails

### ISSUE THREAD

**Issue by maxdinech** [coleam00/bolt.new-any-llm#416]
### Describe the bug

I get the error `FUNCTION_INVOCATION_FAILED` when I try to deploy the app to Vercel.

### Link to the Bolt URL that caused the error

-

### Steps to reproduce

Deploy the app on Vercel from the latest version of the current repository

### Expected behavior

Working app

### Screen Recording / Screenshot

![2024-11-25-100324_537x432_scrot](https://github.com/user-attachments/assets/b2700cad-3cc5-4b9e-992d-f23d37d04e4b)

**Comment by dustinwloring1988** [comment]
I think it is because you are trying to run it serverless?
