### ISSUE TITLE
Ollama provider has default model set to 'claude-3-5-sonnet-latest'

### ISSUE THREAD

**Issue by sammcj** [coleam00/bolt.new-any-llm#423]
### Describe the bug

When selecting Ollama as the provider and entering a prompt, the request fails, looking at the console output Bolt is trying to use the model 'claude-3-5-sonnet-latest' which... is not a model you can run on Ollama 😅

<img width="329" alt="image" src="https://github.com/user-attachments/assets/cc318cb8-4fa8-464c-baa9-0dd199d7b8cc">

<img width="672" alt="image" src="https://github.com/user-attachments/assets/226ff7c6-e2d1-4ea7-9eaf-0504ab6d2a0a">

Looking through the code, I saw the variable `DEFAULT_MODEL`, however setting this to `qwen2.5-coder-32b-instruct-128k:q6_k` had no effect.

I noted that when trying to use Ollama as the LLM no models appear in the drop down list (I see this has been logged #29 #191 #320, so it could be related - or perhaps even the cause.

### Link to the Bolt URL that caused the error

https://bolt.imy.internal.domain/chat/3

### Steps to reproduce

1. Run Bolt with the official docker image (production) via Docker compose
2. Set your Ollama base url (e.g. https://ollama.my.internal.domain)
3. Start the app
4. Note that there's no models in the drop down
5. Try to use the prompt with whatever the default model is
6. Experience serious lack of claude 3.5 sonnet latest running at home 🤣 

### Expected behavior

- The default model for Ollama should be something sensible like qwen-2.5-coder-14b:q6_k or similar.
- Ollama models to show in the drop down list

### Screen Recording / Screenshot

```
APICallError [AI_APICallError]: Not Found
    at null.<anonymous> (file:///app/node_modules/.pnpm/@ai-sdk+provider-utils@1.0.20_zod@3.23.8/node_modules/@ai-sdk/provider-utils/src/response-handler.ts:72:16)
    at async postToApi (file:///app/node_modules/.pnpm/@ai-sdk+provider-utils@1.0.20_zod@3.23.8/node_modules/@ai-sdk/provider-utils/src/post-to-api.ts:81:28)
    at async OllamaChatLanguageModel.doStream (file:///app/node_modules/.pnpm/ollama-ai-provider@0.15.2_zod@3.23.8/node_modules/ollama-ai-provider/src/ollama-chat-language-model.ts:230:50)
    at async fn (file:///app/node_modules/.pnpm/ai@3.4.9_react@18.3.1_sswr@2.1.0_svelte@4.2.18__svelte@4.2.18_vue@3.4.30_typescript@5.5.2__zod@3.23.8/node_modules/ai/core/generate-text/stream-text.ts:345:23)
    at null.<anonymous> (async file:///app/.wrangler/tmp/dev-ck1mC6/functionsWorker-0.12668731906422614.js:30634:22)
    at async _retryWithExponentialBackoff (file:///app/node_modules/.pnpm/ai@3.4.9_react@18.3.1_sswr@2.1.0_svelte@4.2.18__svelte@4.2.18_vue@3.4.30_typescript@5.5.2__zod@3.23.8/node_modules/ai/util/retry-with-exponential-backoff.ts:37:12)
    at async startStep (file:///app/node_modules/.pnpm/ai@3.4.9_react@18.3.1_sswr@2.1.0_svelte@4.2.18__svelte@4.2.18_vue@3.4.30_typescript@5.5.2__zod@3.23.8/node_modules/ai/core/generate-text/stream-text.ts:310:13)
    at async fn (file:///app/node_modules/.pnpm/ai@3.4.9_react@18.3.1_sswr@2.1.0_svelte@4.2.18__svelte@4.2.18_vue@3.4.30_typescript@5.5.2__zod@3.23.8/node_modules/ai/core/generate-text/stream-text.ts:387:11)
    at null.<anonymous> (async file:///app/.wrangler/tmp/dev-ck1mC6/functionsWorker-0.12668731906422614.js:30634:22)
    at async chatAction (file:///app/build/server/index.js:1324:20) {
  cause: undefined,
  url: 'http://ollama:11434/api/chat',
  requestBodyValues: {
    format: undefined,
    model: 'claude-3-5-sonnet-latest',
    options: { num_ctx: 32768, num_predict: 8000, temperature: 0 },
    messages: [ [Object], [Object] ],
    tools: undefined
  },
  statusCode: 404,
  responseHeaders: {
    'content-length': '78',
    'content-type': 'application/json; charset=utf-8',
    date: 'Tue, 26 Nov 2024 01:44:05 GMT'
  },
  responseBody: '{"error":"model \\"claude-3-5-sonnet-latest\\" not found, try pulling it first"}',
  isRetryable: false,
  data: undefined,
  [Symbol(vercel.ai.error)]: true,
  [Symbol(vercel.ai.error.AI_APICallError)]: true
}
[wrangler:inf] POST /api/chat 500 Internal Server Error (11ms)
```

### Platform

- OS: Linux
- Browser: Firefox
- Version: 134

**Comment by sammcj** [comment]
Interestingly, if you exec into the container and run `find /app/app -type f -exec sed -i 's/claude-3-5-sonnet-latest/qwen2.5-coder-14b-instruct-128k:q6_k/g' {} +`, Bolt works with Ollama, but it's limited to this default model name.

**Comment by genlicos** [comment]
remove these red lines from the file: bolt.new-any-llm\app\utils\constants.ts
![erro1](https://github.com/user-attachments/assets/a7012810-d763-4971-b592-21f96c59e5c0)
![erro2](https://github.com/user-attachments/assets/cfd1452c-9cb8-4883-b9da-d8c8953f8e35)
![erro3](https://github.com/user-attachments/assets/f8b4e53d-a355-45c1-8509-9e529f464ece)

It will work normally

**Comment by snowsky** [comment]
Had the same issue, thanks, will give it a test

**Comment by sammcj** [comment]
Unfortunately that didn't make any difference for me:

<img width="771" alt="image" src="https://github.com/user-attachments/assets/df882e1c-2941-4690-82aa-5cbcbe26ed5d">

**Comment by genlicos** [comment]
Do a git clone again and only change these lines

**Comment by genlicos** [comment]
do this in .env
![others1](https://github.com/user-attachments/assets/776deac8-72ad-4f2e-a23a-bd12032e7edc)
![others2](https://github.com/user-attachments/assets/fdcb8d5b-8fd0-46f0-bdae-d259d3b26ef8)
![others3](https://github.com/user-attachments/assets/d26e80cb-39ee-47dd-81bf-fbb7ebca54ab)

**Comment by sammcj** [comment]
That's not my Ollama API URL though?

It works if I run it and Ollama locally, it does not work when running in a container and pointed at my existing Ollama server (https://ollama.my.internal.domain).

**Comment by iamangus** [comment]
> remove these red lines from the file: bolt.new-any-llm\app\utils\constants.ts ![erro1](https://private-user-images.githubusercontent.com/36393568/389773743-a7012810-d763-4971-b592-21f96c59e5c0.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2NDAzMzYsIm5iZiI6MTczMjY0MDAzNiwicGF0aCI6Ii8zNjM5MzU2OC8zODk3NzM3NDMtYTcwMTI4MTAtZDc2My00OTcxLWI1OTItMjFmOTZjNTllNWMwLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI2VDE2NTM1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1YTQ0YzlkZmUwNjVlOGNlNGQ4ZDU5ODdjYjhiMDQwYTJlZGVhNWM3ZmFkNjQ0YWI3ODE3ZmNiY2MzMGQyNGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.mwuwqYAXQmuhbgbTNCshrciJQi3enqJ7FNpI1vaKdTA) ![erro2](https://private-user-images.githubusercontent.com/36393568/389773751-cfd1452c-9cb8-4883-b9da-d8c8953f8e35.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2NDAzMzYsIm5iZiI6MTczMjY0MDAzNiwicGF0aCI6Ii8zNjM5MzU2OC8zODk3NzM3NTEtY2ZkMTQ1MmMtOWNiOC00ODgzLWI5ZGEtZDhjODk1M2Y4ZTM1LlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI2VDE2NTM1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkZGI4NGY3Y2Y5NzA5ZGFhZjExNWEwY2NkOWYyYjE4ODdjYTRiYjRkMGM3ZWQ4YjRiYTY5MzhkOGNjNTI5ZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rJizy3JpFc8HWEgaV_hJZ8QHdOKL6mUJ2pao_vTsicM) ![erro3](https://private-user-images.githubusercontent.com/36393568/389773752-f8b4e53d-a355-45c1-8509-9e529f464ece.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2NDAzMzYsIm5iZiI6MTczMjY0MDAzNiwicGF0aCI6Ii8zNjM5MzU2OC8zODk3NzM3NTItZjhiNGU1M2QtYTM1NS00NWMxLTg1MDktOWU1MjlmNDY0ZWNlLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI2VDE2NTM1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2ZmNhNWY1YjNiYzk4M2MyZDM1YzI2NjY5ZDEzOTU1NTM4ZmM0N2U3MzZjYTMyY2JiNzdlNzVmZjJjY2U5MzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.O1W_lyldCdcTehhVY0wYEdWnj8zl8cCwj5lN1R4BpNw)
> 
> It will work normally

Can anyone confirm if this worked for them? I am having this issue and attempted this fix but it did not work.

**Comment by Blitchy** [comment]
> > remove these red lines from the file: bolt.new-any-llm\app\utils\constants.ts ![erro1](https://private-user-images.githubusercontent.com/36393568/389773743-a7012810-d763-4971-b592-21f96c59e5c0.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2NDAzMzYsIm5iZiI6MTczMjY0MDAzNiwicGF0aCI6Ii8zNjM5MzU2OC8zODk3NzM3NDMtYTcwMTI4MTAtZDc2My00OTcxLWI1OTItMjFmOTZjNTllNWMwLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI2VDE2NTM1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1YTQ0YzlkZmUwNjVlOGNlNGQ4ZDU5ODdjYjhiMDQwYTJlZGVhNWM3ZmFkNjQ0YWI3ODE3ZmNiY2MzMGQyNGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.mwuwqYAXQmuhbgbTNCshrciJQi3enqJ7FNpI1vaKdTA) ![erro2](https://private-user-images.githubusercontent.com/36393568/389773751-cfd1452c-9cb8-4883-b9da-d8c8953f8e35.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2NDAzMzYsIm5iZiI6MTczMjY0MDAzNiwicGF0aCI6Ii8zNjM5MzU2OC8zODk3NzM3NTEtY2ZkMTQ1MmMtOWNiOC00ODgzLWI5ZGEtZDhjODk1M2Y4ZTM1LlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI2VDE2NTM1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkZGI4NGY3Y2Y5NzA5ZGFhZjExNWEwY2NkOWYyYjE4ODdjYTRiYjRkMGM3ZWQ4YjRiYTY5MzhkOGNjNTI5ZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rJizy3JpFc8HWEgaV_hJZ8QHdOKL6mUJ2pao_vTsicM) ![erro3](https://private-user-images.githubusercontent.com/36393568/389773752-f8b4e53d-a355-45c1-8509-9e529f464ece.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2NDAzMzYsIm5iZiI6MTczMjY0MDAzNiwicGF0aCI6Ii8zNjM5MzU2OC8zODk3NzM3NTItZjhiNGU1M2QtYTM1NS00NWMxLTg1MDktOWU1MjlmNDY0ZWNlLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI2VDE2NTM1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2ZmNhNWY1YjNiYzk4M2MyZDM1YzI2NjY5ZDEzOTU1NTM4ZmM0N2U3MzZjYTMyY2JiNzdlNzVmZjJjY2U5MzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.O1W_lyldCdcTehhVY0wYEdWnj8zl8cCwj5lN1R4BpNw)
> > It will work normally
> 
> Can anyone confirm if this worked for them? I am having this issue and attempted this fix but it did not work.

not working for me :'
![image](https://github.com/user-attachments/assets/fe394821-8c1a-4480-aca1-289ca0dbf322)

**Comment by coyottetv** [comment]
for me I had to change DEFAULT_MODEL = 'qwen2.5-coder:32b'; in app\utils\constants.ts for it to work

**Comment by ryooooo** [comment]
got the same error. 
none of above works for me.

**Comment by tdvoracek** [comment]
same problem here, cloned repo, updatet env, running thru pnpm. Local ollama and lm studio, same problem.

**Comment by snowsky** [comment]
The gut feeling told me there is something wrong with https://github.com/vercel/ai/.

**Comment by spencerframe** [comment]
Same problem here. Will try a few options

**Comment by snowsky** [comment]
As a workaround, when you build local model, use `claude-3-5-sonnet-latest` as the name:
```
ollama create -f Modelfile claude-3-5-sonnet-latest
```

**Comment by snowsky** [comment]
This https://github.com/coleam00/bolt.new-any-llm/blob/main/app/lib/.server/llm/stream-text.ts#L44C22-L44C35 seems the cause, `DEFAULT_MODEL` will always be used.

**Comment by mouimet-infinisoft** [comment]
Hi everyone, look at that issue #396 . It is explaining the issue in details with a complete solution. I am preparing a PR with the complete implementation code of the proposed solution that will fix all issues you are facing. :)

**Comment by 7R4S3R** [comment]
go to app\utils\constants.ts     where you see this line:  export const DEFAULT_MODEL = 'Godmoded/llama3-lexi-uncensored:latest'; ( Replace it with your model name from your ollama as a default. then you can choose whichever one afterwards on Ollama.  for those that have problems with .env file this works for me on windows 11 pro.  # Rename this file to .env.local once you have filled in the below environment variables!

# oLLAMA Local API Base URL
# Make sure your oLLAMA server is running locally on this port
OLLAMA_API_BASE_URL=http://localhost:11434

# Optional: Include this environment variable if you want more logging for debugging locally
VITE_LOG_LEVEL=debug

**Comment by beuself** [comment]
After I printed MODEL_LIST, I found that the model list of openrouter was too long, about 100 or so. I don't understand the front end, so I don't know why. I guess it might be the browser policy or my machine's memory is too small, which makes it impossible to get the model of Ollama. When I commented out this section(https://github.com/coleam00/bolt.new-any-llm/blob/main/app/utils/constants.ts#L68-L119), I could get the model list of Ollama correctly.
But it initiated a `/api/tags` request from my browser, which made me feel very bad.

**Comment by MilesPourb** [comment]
> for me I had to change DEFAULT_MODEL = 'qwen2.5-coder:32b'; in app\utils\constants.ts for it to work

This definitely worked! Thank you

**Comment by ArturArutunyan** [comment]
This is what helped me get ollama to work with bolt locally

![CleanShot 2024-12-01 at 18 13 54@2x](https://github.com/user-attachments/assets/8043ba94-9f08-480a-b3de-d9a2d8416d98)

**Comment by dustinwloring1988** [comment]
this has been solved in the latest

**Comment by marhensa** [comment]
> this has been solved in the latest

no it has not.

i have to manually change DEFAULT_MODEL = 'xxxxxxxxxxxx'; 

in `app\utils\constants.ts` as @coyottetv said.

I create project from scratch 2024-12-04 : 18:45

**Comment by miaogong** [comment]
> This is what helped me get ollama to work with bolt locally
> 
> ![CleanShot 2024-12-01 at 18 13 54@2x](https://private-user-images.githubusercontent.com/47005191/391338251-8043ba94-9f08-480a-b3de-d9a2d8416d98.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5NjUxNDEsIm5iZiI6MTczMzk2NDg0MSwicGF0aCI6Ii80NzAwNTE5MS8zOTEzMzgyNTEtODA0M2JhOTQtOWYwOC00ODBhLWIzZGUtZDlhMmQ4NDE2ZDk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEyVDAwNTQwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiZWFiYTEyYTk0MzMxZTE0NTk4ZjA3Y2E3NjMwYjYzYmUwMjFkODk1MjQ0OWIxNGE3M2MyZWNlYjc2ZjQ0YTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.S_loLKyT11YBZaexlTqvYNczR43xTyuWU6femsuQqXc)

使用这个方案，解决了问题。

**Comment by marhensa** [comment]
> 使用这个方案，解决了问题。

your image is broken, I cannot see it.

你的图片坏了，看不到。
