### ISSUE TITLE
Models not loaded if Ollama is not on locakhost

### ISSUE THREAD

**Issue by fcools** [coleam00/bolt.new-any-llm#43]
### Describe the bug

I have Ollama running on a different server (http://192.168.1.202:11434).
The models do not show in the dropdown.

### Link to the Bolt URL that caused the error

http://localhost:5173/

### Steps to reproduce

1. In env.local set the OLLAMA_API_BASE_URL to a server, not localhost (eg. http://192.168.1.202:11434)
2. Start Bolt, the Ollama models do not show.

### Expected behavior

The Ollama models should show in the dropdown.

### Platform

- OS: Linux (Ubuntu 24.04)
- Browser: Firefox

### Additional context

In constants.ts, the Ollama url 'localhost' is hard coded, this url should come from OLLAMA_API_BASE_URL.

```
async function getOllamaModels(): Promise<ModelInfo[]> {
  try {
    const response = await fetch(`http://localhost:11434/api/tags`);
    const data = await response.json();
    return data.models.map((model: any) => ({
      name: model.name,
      label: `${model.name} (${model.details.parameter_size})`,
      provider: 'Ollama',
    }));
  } catch (e) {
    return [];
  }
}

```

**Comment by fcools** [comment]
It is not only the model list that doesn't show, it seems that Ollama is hardcoded on 127.0.0.1.

**Comment by mtcl** [comment]
> After testing with hardcoding my Ollama url in constants.ts, the list shows but Bolt insists on using 127.0.0.1 as the base url for Ollama.

This is accurate. I can reproduce it as well. I looked up for the constant OLLAMA_API_BASE_URL in the codebase and couldn't find it. If I get more time today I'll dig deeper.

**Comment by CesarPetrescu** [comment]
@fcools What did you edit? I tried editing
.env.local with
```
OLLAMA_API_BASE_URL=http://server-ip:port
```
and
constants.ts
```
const response = await fetch(`http://server-ip:port/api/tags`);
```


is there anything else that's needed? Since this didnt work for me

**Comment by mtcl** [comment]
> @fcools What did you edit? I tried editing .env.local with
> 
> ```
> OLLAMA_API_BASE_URL=http://server-ip:port
> ```
> 
> and constants.ts
> 
> ```
> const response = await fetch(`http://server-ip:port/api/tags`);
> ```
> 
> is there anything else that's needed? Since this didnt work for me

What he means is that if you go to getOllamaModels() method and hard code your Ollama base URL in it, it only populates the Ollama models in it. Now when you pick a model, it attempts to use your localhost with that model name and fails with model not found error.

**Comment by CesarPetrescu** [comment]
I have tried a hack with nginx,
I tried running this on the bolt.new instance so that it can acces it via localhost(since my ollama is remote), yet didnt work
```
server {
    listen 11434;
    server_name _;

    location / {
        proxy_pass http://server-ip:port
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
```

**Comment by dudesw575** [comment]
This is easy to overcome.

In `app/lib/.server/llm/model.ts`
Modify the import for the ollama-ai-provider
`import { createOllama } from 'ollama-ai-provider';`

And then modify the ollama block
```
export function getOllamaModel(model: string) {
  const ollama = createOllama({
    baseURL: 'http://{ip here}:11434/api',
  });

  return ollama(model);
}

**Comment by NeoMatrixJR** [comment]
Not sure if anyone else is running into this... I set the app/utils/constants.ts hardcoded to my ollama server url.  It looks like this code is directing the browser to access this (not pulled internally then sent to the frontend).  For some reason, I'm getting a 403 Forbidden trying to access tags.  If I go to it directly it works fine.

**Comment by leex279** [comment]
@NeoMatrixJR I think I figured out the same problem and for me it is still not working with https.

`Access to fetch at 'https://192.168.1.106:8443/api/tags' from origin 'https://192.168.1.106' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`


Tried so add the control-headers by myself, but didnt work :(

I think most people here dont test with a server as well, instead just using it locally all.

**Comment by aaronbolton** [comment]
I've had some luck with this, it not bolt which is the issue but rather the Ollama config, you need to set CORS Origins to 

OLLAMA_ORIGINS=*

**Comment by turbra** [comment]
> I've had some luck with this, it not bolt which is the issue but rather the Ollama config, you need to set CORS Origins to
> 
> OLLAMA_ORIGINS=*

other than setting that variable in ollama, what other settings have you configured/changed in the bolt config?

**Comment by aaronbolton** [comment]
I did hardcode the Ollama urls in here as I found it wasent picking up the variable and was revert to the OR value

app/utils/constants.ts

**Comment by Dkhil** [comment]
if it could help any one 
just add these env variables to /etc/systemd/system/ollama.service 
Environment="OLLAMA_HOST=0.0.0.0"
Environment="OLLAMA_ORIGINS='*'"

**Comment by ptapiabordones** [comment]
If you are running "bolt.diy" in a dev environment the application Ex: docker compose up --build app-dev

You would have to modify the Dockerfile file, go to the end of the file and modify the server startup command to include the correct headers for COOP: original command: #CMD ["pnpm", "run", "dev", "--host", "0.0.0.0"] 

update to this: CMD ["pnpm", "run", "dev", "--host", "0.0.0.0", "--", "--headers", "Cross-Origin-Opener-Policy=same-origin; Cross-Origin-Embedder-Policy=require-corp"]

save the changes and restart the container:

docker compose build --no-cache && docker compose up app-dev

This solves the problem at least in a dev environment since in production it should work if you activate the SSL certificates.

more info to add COOP on some more common web servers: https://webcontainers.io/guides/configuring-headers
