### ISSUE TITLE
llm model not working

### ISSUE THREAD

**Issue by visvapravin** [coleam00/bolt.new-any-llm#437]
### Describe the bug

![Screenshot from 2024-11-27 13-03-03](https://github.com/user-attachments/assets/85f4f88f-87e8-4ffd-af39-7b6c65b16d22)
![Screenshot from 2024-11-27 13-03-08](https://github.com/user-attachments/assets/c91d8c4c-6d83-49f4-b17d-3eb2b477ee25)
![Screenshot from 2024-11-27 13-03-11](https://github.com/user-attachments/assets/b179d16c-7736-46ad-a5a9-6e0570863188)
![Screenshot from 2024-11-27 13-03-32](https://github.com/user-attachments/assets/3bfd843d-fa89-44f2-9cce-f07fafc3ed1a)
only works with openrouter..does not work with any llm...i am using kali linux

### Link to the Bolt URL that caused the error

http://localhost:5173/chat/basic-vite-project

### Steps to reproduce

asusual open it you can see that not working

### Expected behavior

unable to use the model

### Screen Recording / Screenshot

https://github.com/user-attachments/assets/5f05e0ba-bdba-4ecf-bec9-c804d7b6c435

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]
linux
firefox

**Comment by g97iulio1609** [comment]
I fixed it, how can I commit and share it ?

**Comment by g97iulio1609** [comment]
fixed here https://github.com/g97iulio1609/bolt.new-any-llm/tree/main try this version
