### ISSUE TITLE
Serving on Cloudflare Pages

### ISSUE THREAD

**Issue by liveweb22** [coleam00/bolt.new-any-llm#439]
Hello! After I deployed the application in Cloudflare Pages, I noticed that the variables found in .env.local in the preview stage were not kept for the build. How can the variables be defined in the production mode?

**Comment by aliasfoxkde** [comment]
You set them in "Variables and Secrets" within Cloudflare within "Workers & Pages". See docs:
https://developers.cloudflare.com/pages/configuration/build-configuration/#environment-variables

Setting them there will encrypt them. The problem I'm having is they don't appear to be getting detected by the app, but they are clearly set to work in api-keys.ts. Not sure what I'm doing wrong. Tried setting them straight as ANTHROPIC_API_KEY, cloudflareEnv.ANTHROPIC_API_KEY, and a few others.

Hope this at least puts you down the correct path, sorry I don't know why mine isn't working. Maybe you can figure it out.

```
switch (provider) {
    case 'Anthropic':
      return env.ANTHROPIC_API_KEY || cloudflareEnv.ANTHROPIC_API_KEY;
    case 'OpenAI':
      return env.OPENAI_API_KEY || cloudflareEnv.OPENAI_API_KEY;
    case 'Google':
      return env.GOOGLE_GENERATIVE_AI_API_KEY || cloudflareEnv.GOOGLE_GENERATIVE_AI_API_KEY;
    case 'Groq':
      return env.GROQ_API_KEY || cloudflareEnv.GROQ_API_KEY;
    case 'HuggingFace':
      return env.HuggingFace_API_KEY || cloudflareEnv.HuggingFace_API_KEY;
    case 'OpenRouter':
      return env.OPEN_ROUTER_API_KEY || cloudflareEnv.OPEN_ROUTER_API_KEY;
    case 'Deepseek':
      return env.DEEPSEEK_API_KEY || cloudflareEnv.DEEPSEEK_API_KEY;
    case 'Mistral':
      return env.MISTRAL_API_KEY || cloudflareEnv.MISTRAL_API_KEY;
    case 'OpenAILike':
      return env.OPENAI_LIKE_API_KEY || cloudflareEnv.OPENAI_LIKE_API_KEY;
    case 'xAI':
      return env.XAI_API_KEY || cloudflareEnv.XAI_API_KEY;
    case 'Cohere':
      return env.COHERE_API_KEY;
    case 'AzureOpenAI':
      return env.AZURE_OPENAI_API_KEY;
    default:
      return '';
  }
```
