### ISSUE TITLE
Fresh install, program only looks for LMStudio models

### ISSUE THREAD

**Issue by EasternIndustries-IT** [coleam00/bolt.new-any-llm#449]
### Describe the bug

in console i see that it is constantly calling for LMStudio models. Hover i see the request form ollama

### Link to the Bolt URL that caused the error

default

### Steps to reproduce

Following the steps to install locally using pnpm or npm

### Expected behavior

not calling LMStudio models even without a env defined. 
Env Definitions should not default. They should error and move on because if it is blank it is not used

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/e6a7fc45-ec73-4fdb-866f-03a3e074eaf5)
![image](https://github.com/user-attachments/assets/70e2758c-1277-47d4-85fb-036c5f0ab87d)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]
windows 11
chrome

### Additional context
This is how to get rid of the error and how it should be written  
`
async function getLMStudioModels(): Promise<ModelInfo[]> {
  if (typeof window === 'undefined') {
    return [];
  }

  try {
    if (import.meta.env.LMSTUDIO_API_BASE_URL === undefined || import.meta.env.LMSTUDIO_API_BASE_URL === "") {
      return [];
    }
    const baseUrl = import.meta.env.LMSTUDIO_API_BASE_URL || http://localhost:11434';
    const response = await fetch(${baseUrl}/v1/models);
    const data = (await response.json()) as any;

    return data.data.map((model: any) => ({
      name: model.id,
      label: model.id,
      provider: LMStudio,
    }));
  } catch (e) {
    console.error(Error getting LMStudio models:, e);
    return [];
  }
}
`

also ollama is making a request to ollama when claude is still selected even though in ui ollama is selected 

` url: 'http://localhost:11434/api/chat',
  requestBodyValues: {
    format: undefined,
    model: 'claude-3-5-sonnet-latest',
    options: { num_ctx: 32768, num_predict: 8000, temperature: 0 },
    messages: [ [Object], [Object], [Object] ],
    tools: undefined
  },`

**Comment by hamadaDev** [comment]
change claude-3-5-sonnet-latest in app\utils\constants.ts to 
`export const DEFAULT_MODEL = 'qwen2.5-coder:32b';`
or 7b as you have in your ollama server 
check it by 
`ollama list`

**Comment by dustinwloring1988** [comment]
try the latest as it should be fixed
