### ISSUE TITLE
Is there a way to upload a zip folder and make that your starting base and add on to it? 

### ISSUE THREAD

**Issue by derickcaps** [coleam00/bolt.new-any-llm#45]
I just want to add on to existing builds not from bolt is uploading to github and forking the only way or could you just upload a zip some how

**Comment by ggindev** [comment]
There is apparently but haven't tested myself -

https://github.com/coleam00/bolt.new-any-llm/pull/31

**Comment by witzulu** [comment]
Great idea or have sync to exisitng project
