### ISSUE TITLE
OpenAI Like and Ollama UI change

### ISSUE THREAD

**Issue by dustinwloring1988** [coleam00/bolt.new-any-llm#461]
**Is your feature request related to a problem? Please describe:**

When selecting OpenAI Like I would like to have a a textbox for the url and textbox for model name. Since this will not be retrieved automatically. Then The Ollama provider could extend from that with a populated url but editable, and a model dropdown for the model name as it is now.

This relatively simple change should add needed compatibility.

**Comment by dustinwloring1988** [comment]
This would allow hosting this and connecting to a ollama instance in the cloud that i spin up when using this.

**Comment by b3nt3ch** [comment]
I agree adding those options will make it more usuable for me at least
