### ISSUE TITLE
Publishing to Cloudflare Pages

### ISSUE THREAD

**Issue by aliasfoxkde** [coleam00/bolt.new-any-llm#472]
### Describe the bug

I was able to publish to Cloudflare pages, and I set the "Variables and Secrets" within Cloudflare within "Workers & Pages". But the UI does not appear to be picking them up. Has anyone successfully got this working and if so, what were your steps? There are no errors per se, it just doesn't work.

### Link to the Bolt URL that caused the error

https://

### Steps to reproduce

1. Added various *_API_KEY values to "Variables and Secrets" within Cloudflare for the "Page"
2. Re-deployed bolt.new repository.
3. Test and repeat (tried *_API_KEY, cloudflareEnv.*_API_KEY, etc.)

### Expected behavior

Show Model API choices from the dropdown menu in the Bolt.New Cloudflare Page (per the API_KEYS set in "Secrets").

### Platform

- OS: [Windows]
- Browser: [Chrome, Edge]
- Version: [Unknown]

### Additional context

I spend hours on this, going to bed now. Lol.

**Comment by dustinwloring1988** [comment]
please try latest version and make sure to use pnpm deploy when doing this. if you still get an error open a new issue as this worked for me.

**Comment by aliasfoxkde** [comment]
That is not the issue, because I am using the latest version. I literally installed it yesterday. Is there explicit documentation you can point me to try?

**Comment by aliasfoxkde** [comment]
> please try latest version and make sure to use pnpm deploy when doing this. if you still get an error open a new issue as this worked for me.

What exactly did you test? Cloudflare Workers, Pages? And did you test passing an API_KEY like it was specifically mentioned?

I want Pages to pickup the key and to update on commit (which is working, except for the Cloudflare env).

Thanks🙏

**Comment by dustinwloring1988** [comment]
Yes please test with the latest and if the error persists please open a new issue, along with all commands ran after cloning
