### ISSUE TITLE
Add xAI API support

### ISSUE THREAD

**Issue by achimghita** [coleam00/bolt.new-any-llm#48]

**Comment by rahulmr** [comment]
with grok-2 beta version we get the $25 credit and no token limits. Kindly consider this on priority

**Comment by Raylopi** [comment]
That would be awesome.

**Comment by biznizai** [comment]
Thumbs up on this please

**Comment by milutinke** [comment]
Working on this right now, but the model seems not to be that good.

**Comment by milutinke** [comment]
The PR is merged, so the issue can be closed.
From my testing, the model is not that good by itself, you have do a bit of manual intervention here and there (namely it generates the outdated package versions sometimes), and good prompt engineering.
Still, for free 25$ it's better than nothing.

**Comment by Bortus-AI** [comment]
Can we get the other models added
grok-2-vision
grok-vision-beta
