### ISSUE TITLE
any idea adding o1, o1-preview soon?

### ISSUE THREAD

**Issue by fortunamagix** [coleam00/bolt.new-any-llm#487]
**Is your feature request related to a problem? Please describe:**

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

**Comment by dustinwloring1988** [comment]
looks like someone has started it: https://github.com/coleam00/bolt.new-any-llm/pull/485

**Comment by fortunamagix** [comment]
that's a good news but not quite related to bolt.new all LLM why not just implement and add it here?

**Comment by fortunamagix** [comment]
edit: myfault sleep less haha:
it's quite good thx
