### ISSUE TITLE
Project templates before start create

### ISSUE THREAD

**Issue by danielmeloalencar** [coleam00/bolt.new-any-llm#52]
I noticed that the original Bolt.new uses project templates with the entire basic structure according to the project type (React, Vite, Express, Vue) when it recognizes the required project type based on the prompt. This helps prevent errors, such as occasionally adding unnecessary or non-existent dependencies to the package.json. I believe this could be done directly in the prompt within app\lib\.server\llm\prompts.ts.

![image](https://github.com/user-attachments/assets/e33faf3f-744d-44e0-8ef5-ac9372917a27)

An alternative would be to choose the project type (template) before starting the prompt. That way, the entire project base (Vite/React, Node Express, Vue, etc.) would be set up correctly, and then the user could proceed with their prompt.

**Comment by faddy19** [comment]
Absolutely right. This would make things much easier. We need to take out the guess work and channel the system so we get the endresult we want. 

Any idea how to implement that?

**Comment by danielmeloalencar** [comment]
> I'm noticing an issue when comparing the output from the official site with my local output. Even when using the Sonnet 3.5 model, the results still fall short of the quality seen on .`bolt.new``bolt.new`
> 
> And I found a folder that seems to contain the configuration settings for project templates. The config.json file within this folder shows a variety of available templates:`.bolt `
> 
> <img alt="image" width="1630" src="https://private-user-images.githubusercontent.com/29654145/383986786-ee3b2b00-bf21-4cf8-b182-6b13e2082225.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExMDAwNTIsIm5iZiI6MTczMTA5OTc1MiwicGF0aCI6Ii8yOTY1NDE0NS8zODM5ODY3ODYtZWUzYjJiMDAtYmYyMS00Y2Y4LWIxODItNmIxM2UyMDgyMjI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA4VDIxMDIzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlYjhjZjA1Y2VhOTlmNzUwM2NmNWQ2N2JmNjIzZGI4MmU2ZmQzZGRjNmUyYjk3YjNhZjRmYmYxZTU3ZjJkODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.4MME5Xsc7pNCUroxn8r-D2hPtEdkO-neSaoJ1Jui_i4">
> To improve this, I recommend creating a set of high-quality project templates and storing them in the Git repository. Each template should include a name and description, and we could make them selectable through a configuration panel.
> 
> When a user starts a new project, the system could first engage an LLM, supplying it with the list of templates and their descriptions. The LLM could then output a structured response indicating the chosen template, or it could suggest starting with a blank template.
> 
> Once a template is chosen, the system would clone it into the web container and proceed with the usual setup process.
> 
> Without these templating features, achieving high-quality code output is challenging, and this project risks being viewed as a toy if it can't support serious development.
> 
> (P.S: this comment is refined with AI for better readability 😆 , here us the prompt `I am writing this comment in a github issue, rewrite it for better readability` )

I believe that with the use of agents (which is already on the project roadmap), this can be solved.
An agent can be run to choose a suitable template from the predefined options and then other agents follow the process of generating the code.

**Comment by chrismahoney** [comment]
^^ Keep an eye on the above PR regarding templates, thanks @thecodacus for the work and also reminding me about the .bolt directory!

**Comment by thecodacus** [comment]
closed the previous PR, as @wonderwhy-er suggested it would be better to have text based approach for for tool calling.
submitted #302 with that solution in mind
