### ISSUE TITLE
Display Model Provider and Model Name on prompt entry box when model settings are closed

### ISSUE THREAD

**Issue by Freffles** [coleam00/bolt.new-any-llm#543]
When the user closes Model Settings, the user cannot see what model is being used unless the settings are reopened. There is enough white space to the right of the Model Settings label to display the selected model provider and model name.

![image](https://github.com/user-attachments/assets/7ff2c2db-41c3-4a5a-be17-28e8501afcf1)

**Comment by thecodacus** [comment]
this is fixed on #565
