### ISSUE TITLE
⚠[Security risk] built-in together API links to together.xyz?☠

### ISSUE THREAD

**Issue by System233** [coleam00/bolt.new-any-llm#576]
> [!CAUTION]
>The built-in Together API is currently linked to `together.xyz` instead of the expected `together.ai`.  
>
>According to the TLS certificate information of `together.xyz`, it seems to be operated by a different entity than Together AI. This discrepancy may introduce potential security concerns, such as the unintended exposure of sensitive data.  

https://github.com/coleam00/bolt.new-any-llm/blob/2af32b0333e4457b1212b1cab951d63724e8cc18/app/lib/.server/llm/api-key.ts#L51-L56

**Comment by thecodacus** [comment]
both operated by same entity 
<img width="877" alt="image" src="https://github.com/user-attachments/assets/df97f722-9cb7-444f-bee7-745cfbfd4789">
