### ISSUE TITLE
Not able to install packages

### ISSUE THREAD

**Issue by jaymeanchante** [coleam00/bolt.new-any-llm#601]
### Describe the bug

Hello,
First of all, great project!

It seems like Bolt is not able to install libraries. Whenever I got to the installation step, I get the following (this is cat from the log since there is no download button for that):

0 verbose cli /usr/local/bin/node /usr/local/bin/npm
1 info using npm@10.2.3
2 info using node@v18.20.3
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 6ms
5 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 2ms
6 timing config:load:builtin Completed in 3ms
7 timing config:load:cli Completed in 2ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/home/project/.npmrc Completed in 16ms
10 timing config:load:project Completed in 32ms
11 timing config:load:file:/home/.npmrc Completed in 48ms
12 timing config:load:user Completed in 48ms
13 timing config:load:file:/usr/local/etc/npmrc Completed in 13ms
14 timing config:load:global Completed in 14ms
15 timing config:load:flatten Completed in 2ms
16 timing config:load:setEnvs Completed in 1ms
17 timing config:load Completed in 111ms
18 timing npm:load:configload Completed in 112ms
19 timing npm:load:mkdirpcache Completed in 0ms
20 timing npm:load:mkdirplogs Completed in 1ms
21 verbose title npm install
22 verbose argv "install"
23 timing npm:load:setTitle Completed in 1ms
24 timing npm:load:display Completed in 0ms
25 verbose logfile logs-max:10 dir:/home/.npm/_logs/2024-12-08T18_47_51_778Z-
26 verbose logfile /home/.npm/_logs/2024-12-08T18_47_51_778Z-debug-0.log
27 timing npm:load:logFile Completed in 10ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 127ms
31 timing arborist:ctor Completed in 0ms
32 silly logfile done cleaning log files
33 timing arborist:ctor Completed in 0ms
34 timing idealTree:init Completed in 149ms
35 timing idealTree:userRequests Completed in 0ms
36 timing idealTree:preloadMetadata Completed in 2791ms
37 silly idealTree buildDeps
38 silly fetch manifest leaflet@^1.9.4
39 http fetch GET 404 https://registry.npmjs.org/leaflet 305ms (cache skip)
40 http fetch GET 404 https://registry.npmjs.org/leaflet 225ms (cache skip)
41 silly fetch manifest react@^18.2.0
42 http fetch GET 404 https://registry.npmjs.org/react 702ms (cache skip)
43 http fetch GET 404 https://registry.npmjs.org/react 602ms (cache skip)
44 silly fetch manifest react-dom@^18.2.0
45 http fetch GET 404 https://registry.npmjs.org/react-dom 719ms (cache skip)
46 http fetch GET 404 https://registry.npmjs.org/react-dom 311ms (cache skip)
47 silly fetch manifest react-leaflet@^4.2.1
48 http fetch GET 404 https://registry.npmjs.org/react-leaflet 290ms (cache skip)
49 http fetch GET 404 https://registry.npmjs.org/react-leaflet 703ms (cache skip)
50 silly fetch manifest @types/react@^18.0.28
51 http fetch GET 404 https://registry.npmjs.org/@types%2freact 434ms (cache skip)
52 http fetch GET 404 https://registry.npmjs.org/@types%2freact 435ms (cache skip)
53 silly fetch manifest @types/react-dom@^18.0.11
54 http fetch GET 404 https://registry.npmjs.org/@types%2freact-dom 1707ms (cache skip)
55 http fetch GET 404 https://registry.npmjs.org/@types%2freact-dom 406ms (cache skip)
56 silly fetch manifest @vitejs/plugin-react@^4.0.3
57 http fetch GET 404 https://registry.npmjs.org/@vitejs%2fplugin-react 263ms (cache skip)
58 http fetch GET 404 https://registry.npmjs.org/@vitejs%2fplugin-react 350ms (cache skip)
59 silly fetch manifest vite@^4.3.9
60 http fetch GET 404 https://registry.npmjs.org/vite 402ms (cache skip)
61 http fetch GET 404 https://registry.npmjs.org/vite 282ms (cache skip)
62 silly placeDep ROOT @types/react@ OK for: henrique-dias-lawyer@0.0.0 want: ^18.0.28
63 silly placeDep ROOT @types/react-dom@ OK for: henrique-dias-lawyer@0.0.0 want: ^18.0.11
64 silly placeDep ROOT @vitejs/plugin-react@ OK for: henrique-dias-lawyer@0.0.0 want: ^4.0.3
65 silly placeDep ROOT leaflet@ OK for: henrique-dias-lawyer@0.0.0 want: ^1.9.4
66 silly placeDep ROOT react@ OK for: henrique-dias-lawyer@0.0.0 want: ^18.2.0
67 silly placeDep ROOT react-dom@ OK for: henrique-dias-lawyer@0.0.0 want: ^18.2.0
68 silly placeDep ROOT react-leaflet@ OK for: henrique-dias-lawyer@0.0.0 want: ^4.2.1
69 silly placeDep ROOT vite@ OK for: henrique-dias-lawyer@0.0.0 want: ^4.3.9
70 timing idealTree:#root Completed in 8179ms
71 timing idealTree:node_modules/@types/react Completed in 0ms
72 timing idealTree:node_modules/@types/react-dom Completed in 1ms
73 timing idealTree:node_modules/@vitejs/plugin-react Completed in 0ms
74 timing idealTree:node_modules/leaflet Completed in 0ms
75 timing idealTree:node_modules/react Completed in 0ms
76 timing idealTree:node_modules/react-dom Completed in 0ms
77 timing idealTree:node_modules/react-leaflet Completed in 0ms
78 timing idealTree:node_modules/vite Completed in 0ms
79 timing idealTree:buildDeps Completed in 8180ms
80 timing idealTree:fixDepFlags Completed in 1ms
81 timing idealTree Completed in 11124ms
82 timing command:install Completed in 11130ms
83 verbose stack f: 404 Not Found - GET https://registry.npmjs.org/@types%2freact - Not found
83 verbose stack     at f (/usr/local/lib/node_modules/npm/dist/common.js:437:2228)
83 verbose stack     at i/< (/usr/local/lib/node_modules/npm/dist/common.js:437:917)
83 verbose stack     at then/< (https://k03e2io1v3fx9wvj0vr8qd5q58o56n-fkdo.w-corp-staticblitz.com/blitz.fc837ba8.js:40:23092)
84 verbose statusCode 404
85 verbose pkgid @types/react@^18.0.28
86 verbose cwd /home/project
87 verbose Linux 5.0 (Windows)
88 verbose node v18.20.3
89 verbose npm  v10.2.3
90 error code E404
91 error 404 Not Found - GET https://registry.npmjs.org/@types%2freact - Not found
92 error 404
93 error 404  '@types/react@^18.0.28' is not in this registry.
94 error 404
94 error 404 Note that you can also install from a
95 error 404 tarball, folder, http url, or git url.
96 verbose exit 1
97 timing npm Completed in 11285ms
98 verbose unfinished npm timer reify 1733683671929
99 verbose unfinished npm timer reify:loadTrees 1733683671932
100 verbose code 1
101 error A complete log of this run can be found in: /home/.npm/_logs/2024-12-08T18_47_51_778Z-debug-0.log

### Link to the Bolt URL that caused the error

http://localhost:5173/chat/lawyer-website

### Steps to reproduce

1. git clone https://github.com/coleam00/bolt.new-any-llm
2. cd bolt.new-any-llm
3. pnpm install
4. pnpm run dev
5. I setup my prompt and Google API Key
6. Libraries are not automatically installed, I tried to run `npm install` in the Bolt terminal but there is this error

0 verbose cli /usr/local/bin/node /usr/local/bin/npm
1 info using npm@10.2.3
2 info using node@v18.20.3
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 6ms
5 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 2ms
6 timing config:load:builtin Completed in 3ms
7 timing config:load:cli Completed in 2ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/home/project/.npmrc Completed in 16ms
10 timing config:load:project Completed in 32ms
11 timing config:load:file:/home/.npmrc Completed in 48ms
12 timing config:load:user Completed in 48ms
13 timing config:load:file:/usr/local/etc/npmrc Completed in 13ms
14 timing config:load:global Completed in 14ms
15 timing config:load:flatten Completed in 2ms
16 timing config:load:setEnvs Completed in 1ms
17 timing config:load Completed in 111ms
18 timing npm:load:configload Completed in 112ms
19 timing npm:load:mkdirpcache Completed in 0ms
20 timing npm:load:mkdirplogs Completed in 1ms
21 verbose title npm install
22 verbose argv "install"
23 timing npm:load:setTitle Completed in 1ms
24 timing npm:load:display Completed in 0ms
25 verbose logfile logs-max:10 dir:/home/.npm/_logs/2024-12-08T18_47_51_778Z-
26 verbose logfile /home/.npm/_logs/2024-12-08T18_47_51_778Z-debug-0.log
27 timing npm:load:logFile Completed in 10ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 127ms
31 timing arborist:ctor Completed in 0ms
32 silly logfile done cleaning log files
33 timing arborist:ctor Completed in 0ms
34 timing idealTree:init Completed in 149ms
35 timing idealTree:userRequests Completed in 0ms
36 timing idealTree:preloadMetadata Completed in 2791ms
37 silly idealTree buildDeps
38 silly fetch manifest leaflet@^1.9.4
39 http fetch GET 404 https://registry.npmjs.org/leaflet 305ms (cache skip)
40 http fetch GET 404 https://registry.npmjs.org/leaflet 225ms (cache skip)
41 silly fetch manifest react@^18.2.0
42 http fetch GET 404 https://registry.npmjs.org/react 702ms (cache skip)
43 http fetch GET 404 https://registry.npmjs.org/react 602ms (cache skip)
44 silly fetch manifest react-dom@^18.2.0
45 http fetch GET 404 https://registry.npmjs.org/react-dom 719ms (cache skip)
46 http fetch GET 404 https://registry.npmjs.org/react-dom 311ms (cache skip)
47 silly fetch manifest react-leaflet@^4.2.1
48 http fetch GET 404 https://registry.npmjs.org/react-leaflet 290ms (cache skip)
49 http fetch GET 404 https://registry.npmjs.org/react-leaflet 703ms (cache skip)
50 silly fetch manifest @types/react@^18.0.28
51 http fetch GET 404 https://registry.npmjs.org/@types%2freact 434ms (cache skip)
52 http fetch GET 404 https://registry.npmjs.org/@types%2freact 435ms (cache skip)
53 silly fetch manifest @types/react-dom@^18.0.11
54 http fetch GET 404 https://registry.npmjs.org/@types%2freact-dom 1707ms (cache skip)
55 http fetch GET 404 https://registry.npmjs.org/@types%2freact-dom 406ms (cache skip)
56 silly fetch manifest @vitejs/plugin-react@^4.0.3
57 http fetch GET 404 https://registry.npmjs.org/@vitejs%2fplugin-react 263ms (cache skip)
58 http fetch GET 404 https://registry.npmjs.org/@vitejs%2fplugin-react 350ms (cache skip)
59 silly fetch manifest vite@^4.3.9
60 http fetch GET 404 https://registry.npmjs.org/vite 402ms (cache skip)
61 http fetch GET 404 https://registry.npmjs.org/vite 282ms (cache skip)
62 silly placeDep ROOT @types/react@ OK for: henrique-dias-lawyer@0.0.0 want: ^18.0.28
63 silly placeDep ROOT @types/react-dom@ OK for: henrique-dias-lawyer@0.0.0 want: ^18.0.11
64 silly placeDep ROOT @vitejs/plugin-react@ OK for: henrique-dias-lawyer@0.0.0 want: ^4.0.3
65 silly placeDep ROOT leaflet@ OK for: henrique-dias-lawyer@0.0.0 want: ^1.9.4
66 silly placeDep ROOT react@ OK for: henrique-dias-lawyer@0.0.0 want: ^18.2.0
67 silly placeDep ROOT react-dom@ OK for: henrique-dias-lawyer@0.0.0 want: ^18.2.0
68 silly placeDep ROOT react-leaflet@ OK for: henrique-dias-lawyer@0.0.0 want: ^4.2.1
69 silly placeDep ROOT vite@ OK for: henrique-dias-lawyer@0.0.0 want: ^4.3.9
70 timing idealTree:#root Completed in 8179ms
71 timing idealTree:node_modules/@types/react Completed in 0ms
72 timing idealTree:node_modules/@types/react-dom Completed in 1ms
73 timing idealTree:node_modules/@vitejs/plugin-react Completed in 0ms
74 timing idealTree:node_modules/leaflet Completed in 0ms
75 timing idealTree:node_modules/react Completed in 0ms
76 timing idealTree:node_modules/react-dom Completed in 0ms
77 timing idealTree:node_modules/react-leaflet Completed in 0ms
78 timing idealTree:node_modules/vite Completed in 0ms
79 timing idealTree:buildDeps Completed in 8180ms
80 timing idealTree:fixDepFlags Completed in 1ms
81 timing idealTree Completed in 11124ms
82 timing command:install Completed in 11130ms
83 verbose stack f: 404 Not Found - GET https://registry.npmjs.org/@types%2freact - Not found
83 verbose stack     at f (/usr/local/lib/node_modules/npm/dist/common.js:437:2228)
83 verbose stack     at i/< (/usr/local/lib/node_modules/npm/dist/common.js:437:917)
83 verbose stack     at then/< (https://k03e2io1v3fx9wvj0vr8qd5q58o56n-fkdo.w-corp-staticblitz.com/blitz.fc837ba8.js:40:23092)
84 verbose statusCode 404
85 verbose pkgid @types/react@^18.0.28
86 verbose cwd /home/project
87 verbose Linux 5.0 (Windows)
88 verbose node v18.20.3
89 verbose npm  v10.2.3
90 error code E404
91 error 404 Not Found - GET https://registry.npmjs.org/@types%2freact - Not found
92 error 404
93 error 404  '@types/react@^18.0.28' is not in this registry.
94 error 404
94 error 404 Note that you can also install from a
95 error 404 tarball, folder, http url, or git url.
96 verbose exit 1
97 timing npm Completed in 11285ms
98 verbose unfinished npm timer reify 1733683671929
99 verbose unfinished npm timer reify:loadTrees 1733683671932
100 verbose code 1
101 error A complete log of this run can be found in: /home/.npm/_logs/2024-12-08T18_47_51_778Z-debug-0.log

### Expected behavior

Automatically install libraries and be able to see the Preview in the left screen,

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/8db85c77-14a2-4429-b5cf-455ae0270260)
![image](https://github.com/user-attachments/assets/c935db05-b7d8-491a-8443-e999d11901a9)

### Platform

- OS: Windows
- Browser: Firefox
- Version: 133.0
- [ba29e59](https://github.com/coleam00/bolt.new-any-llm/commit/ba29e5927f7300b67d1398155d476157fa5460fc)

### Provider Used

Google/Gemini

### Model Used

I tried all the available and all failed for the same reason, I tried to manually install the dependencies, but that failed too

**Comment by kustomzone** [comment]
`[@types%2freact] . . . (https://registry.npmjs.org/@types%2freact)`

The forward slashes are being left as '%2f'. This might work in a browser context as browsers convert them back usually, but looks like Bolt's terminal node in it's current configuration doesn't handle this.
If you put the url as-is in a browser it works fine. Unsure what causes them to be converted in the first place.

**Comment by harellevy** [comment]
Npm had maintenance yesterday. Should work today.

**Comment by jaymeanchante** [comment]
Hello, I pulled the latest commit it is working now
