### ISSUE TITLE
Error getting Ollama models: TypeError: fetch failed

### ISSUE THREAD

**Issue by tautist** [coleam00/bolt.new-any-llm#613]
### Describe the bug

Fresh install, after installing dependencies i get the following error  when attempting to execute npm run dev
`*** Received structured exception #0xc0000005: access violation; stack: 7ff82f922a9f 7ff6a5b8aa5a 7ff6a5b8ab23 7ff6a5b2c4ac 7ff6a5b2c457 7ff6a539143e 7ff6a539174f 7ff6a41a1ed6 7ff6a54bbcef 7ff6a54c2f86 7ff6a54bc1f3 7ff6a54c2f86 7ff6a54b9b8c 7ff6a4191e66 7ff6a6cf961f 7ff84b1d7033 7ff84be02650`

can be solved with running

`npm install wrangler@3.57.1`
 But the new error is
 
`Error getting Ollama models: TypeError: fetch failed`

env is configured, ollama is running and detecting the model.
i've had this running fine a few time previous to the latest update to the git. any ideas?

### Link to the Bolt URL that caused the error

local

### Steps to reproduce

fresh install
attempt to execute npm run dev

### Expected behavior

function like previous running models

### Screen Recording / Screenshot

<img width="611" alt="1" src="https://github.com/user-attachments/assets/3d591967-b48f-4d6f-ab23-4a3870d47e62">
<img width="600" alt="2" src="https://github.com/user-attachments/assets/0dc8b4d1-b257-4812-9847-fe2cf40b5181">

### Platform

- OS: Windows 10 Enterprise LTSC
- Browser: brave 

### Model Used

ollama

**Comment by nushret** [comment]
same error

**Comment by tautist** [comment]
Switch the suggested http://localhost:11434 to http://127.0.0.1:11434 cleared it up for me.
<img width="501" alt="1" src="https://github.com/user-attachments/assets/7e1462c8-50c5-4a5e-bb08-5ac4926fe826">

**Comment by ChrisDag21** [comment]
I had the same error on Windows, the solution is to install the latest Visual C++ Redistributable from Microsoft => [https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170)
