### ISSUE TITLE
Cross Origin and Data Clone errors on client(browser) side -> see console section on the right in screenshots

### ISSUE THREAD

**Issue by msfreud** [coleam00/bolt.new-any-llm#69]
### Describe the bug

When running in a browser (including Canary) - it fails to perform the tasks - see the crossed red tasks. But no error from the DEBUG or any message.

![image](https://github.com/user-attachments/assets/6556b8c7-0feb-4b41-bf74-a21259ab60dc)

### Link to the Bolt URL that caused the error

localhost

### Steps to reproduce

Just request a new ToDo List app from the list of examples at the bottom of the Bolt.new front screen

### Expected behavior

should perform the tasks on the list

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by msfreud** [comment]
![image](https://github.com/user-attachments/assets/df7efaa1-65b8-4246-92c3-4ed67ca42b9e)

**Comment by gelbcke** [comment]
@msfreud you need to run over https

Check Issue #57
