### ISSUE TITLE
<FEATURE> Nemotron 70b

### ISSUE THREAD

**Issue by Thedrassbass** [coleam00/bolt.new-any-llm#72]
Supposedly Nemotron 70b is the absolute best LLM out there, even better than GPT4o and LLama 3.1

**Comment by nowjon** [comment]
I believe this is available via Ollama, what are you requesting be done here?

**Comment by Thedrassbass** [comment]
Sorry, I did not see the LLM. I fixed the issue thx. Thank you for reaching
out to me 😄

fre. 25. okt. 2024 kl. 03:50 skrev nowjon ***@***.***>:

**Comment by BenjaminKeating1986** [comment]
you can use this via OpenRouter but openrouter seems slow for me and i didnt get good results with Nemotron, gpt-40 seems to be the best at the moment
