### ISSUE TITLE
On Save - Failed to update file content

### ISSUE THREAD

**Issue by DurosAtari** [coleam00/bolt.new-any-llm#75]
### Describe the bug

No issues encountered during installation. Ollama connects normally. AI suggests steps including the creation of files and file content. I create the file, but after pasting the content, I click the save button and get an error message: Failed to update the file content. 

### Link to the Bolt URL that caused the error

localhost

### Steps to reproduce

use touch or cat to create a new file. 
Copy / paste AI generated content to the file
Click Save button

### Expected behavior

the file saves

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]
Windows OS
Edge

### Additional context

re-cloned the repo today to get the option to "synch folder", but that works only one way.

**Comment by nowjon** [comment]
I would recommend trying out the official bolt.new if you haven't. 
I believe you're following the instructions from the LLM but it's supposed to create the files, execute the code, etc for you. It shouldn't be something you're needing to do manually.

**Comment by DurosAtari** [comment]
OK that made me think of context windows. I followed this to adjust the context window: https://blog.driftingruby.com/ollama-context-window/ and now bolt.new is creating the files and executing the code. Not sure what the best value is though, but the default 2048 did not cut it. 

It would be great though if we could make manual modifications and save them

**Comment by new4u** [comment]
I met the same problem  it seems i dont have auth to write file content by hand.(but can touch create an empty file..) 

but im thinking of ,is there a folder we can do it with terminal
<img width="1323" alt="image" src="https://github.com/user-attachments/assets/c5cb1f38-6910-45ee-8625-6f00a8638bf2">

**Comment by new4u** [comment]
you can use touch and echo instead
```
echo '<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    ...
  </body>
</html>' > index.html
```
