### ISSUE TITLE
Anthropic API Key Missing

### ISSUE THREAD

**Issue by maelstrom009** [coleam00/bolt.new-any-llm#76]
### Describe the bug

Starting server without entering any api keys in environment variables. Choose ollama latest from dropdowns, then select first prompt results in error message: LoadAPIKeyError Anthropic API Key is missing.

### Link to the Bolt URL that caused the error

http://localhost:5173/chat/1

### Steps to reproduce

1. Starting server without entering any api keys in environment variables. 
2. Choose ollama latest from dropdowns
3. then select first example prompt

### Expected behavior

Should have worked since using a local model doesn't require any additional setup

### Platform

wsl2 on windows 11 using ubuntu 24.04

**Comment by electroheadfx** [comment]
I have the same issue, I entered the anthropic key, and it does the same issue, anthropic and ollama error:
`hook.js:608 Warning: Text content did not match. Server: "Anthropic" Client: "Ollama" Error Component Stack`

**Comment by schilling3003** [comment]
Same issue here. I tried using ZerxZ's fork, but unfortunately with that no models were displayed for Ollama. Hoping this can get fixed soon.
