### ISSUE TITLE
Code and preview not displaying code nor be able to preview.

### ISSUE THREAD

**Issue by Thiararapeter** [coleam00/bolt.new-any-llm#78]
### Describe the bug

>displaying previous chat history
![chat history not working] (https://github.com/user-attachments/assets/97c2587d-c041-4492-bf7a-95211de3c5c6)

>am using Ollama LLM, when i generate the code, not showing the code generated nor be able to preview. 
![code and preview not working] (https://github.com/user-attachments/assets/d9a73f14-35bc-46e5-9a51-d33b303bf9a5)

### Link to the Bolt URL that caused the error

http://localhost:5173/chat/11

### Steps to reproduce

>displaying previous chat history
![chat history not working](https://github.com/user-attachments/assets/97c2587d-c041-4492-bf7a-95211de3c5c6)

>am using Ollama LLM, when i generate the code, not showing the code generated nor be able to preview. 
![code and preview not working] (https://github.com/user-attachments/assets/d9a73f14-35bc-46e5-9a51-d33b303bf9a5)

### Expected behavior

not working as expected

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by panteLx** [comment]
which browser are u using? is it working with another llm like gpt-4?

**Comment by Thiararapeter** [comment]
am using brave browser, using google working on code display but on preview not working

> which browser are u using? is it working with another llm like gpt-4?

**Comment by BJR-developer** [comment]
same here on chrome into linux

**Comment by lantjie** [comment]
same here on chrome and mozilla on linux

**Comment by granthooks** [comment]
Same issue here. Chrome browser, code generates, but preview is empty.  No errors/messages in the Terminal

**Comment by witzulu** [comment]
### Same issue:
Tried Canary and brave.
Using 

ollama and windows.

**tried :**
codelamma (7b)
qwen2.5-coder:7b (7.6B)
incept5/llama3.1-claude:latest (8.0B)
![bolt test](https://github.com/user-attachments/assets/7e323531-7bb9-4dfe-ad60-690d432bf958)

**Comment by noxvitae** [comment]
Same. It seemed to be working on first run. Rebooted and now it's just basic chat functionality. Chrome/Edge, Win 11, tried a handful of models.

**Comment by clickbrain** [comment]
I am having the same issue. No preview and no code insertion.

**Comment by ironico** [comment]
same issue here

**Comment by witzulu** [comment]
Just some feedback. I tested in using 
 { name: 'google/gemini-flash-1.5-exp', label: 'Google: Gemini Flash 1.5 Experimental (OpenRouter)', provider: 'OpenRouter' }, 
  { name: 'meta-llama/llama-3.2-3b-instruct', label: 'Meta: Llama 3.2 3B Instruct (OpenRouter)', provider: 'OpenRouter' }, 
and it works so i suspect it is an ollama  issue. i had to run

**Comment by hoverflow** [comment]
- in the stream-text.ts replace the streamText function with this code: 
`export function streamText(messages: Messages, env: Env, options?: StreamingOptions) {
  let currentModel = DEFAULT_MODEL;
  const systemMessage = {
    role: 'system',
    content: getSystemPrompt()
  };
  
  const processedMessages = [systemMessage, ...messages.map((message) => {
    if (message.role === 'user') {
      const { model, content } = extractModelFromMessage(message);
      if (model && MODEL_LIST.find((m) => m.name === model)) {
        currentModel = model; // Update the current model
      }
      return { ...message, content };
    }
    return message;
  })];

  const provider = MODEL_LIST.find((model) => model.name === currentModel)?.provider || DEFAULT_PROVIDER;
  //console.warn('streamText', getSystemPrompt())
  return _streamText({
    model: getModel(provider, currentModel, env),
    system: getSystemPrompt(),
    maxTokens: MAX_TOKENS,
    // headers: {
    //   'anthropic-beta': 'max-tokens-3-5-sonnet-2024-07-15',
    // },
    messages: convertToCoreMessages(processedMessages),
    ...options,
  });
}`

- in the bolt configuration set the OPENAI_API_KEY to a random string and OPENAI_LIKE_BASE_URL to http://localhost:11434/v1 which is the local ollama instance

![image](https://github.com/user-attachments/assets/b471369d-bba4-4351-91e5-7e7d40de9a8c)

**Comment by hoverflow** [comment]
> > * in the stream-text.ts replace the streamText function with this code:
> >   `export function streamText(messages: Messages, env: Env, options?: StreamingOptions) { let currentModel = DEFAULT_MODEL; const systemMessage = { role: 'system', content: getSystemPrompt() }; const processedMessages = [systemMessage, ...messages.map((message) => { if (message.role === 'user') { const { model, content } = extractModelFromMessage(message); if (model && MODEL_LIST.find((m) => m.name === model)) { currentModel = model; // Update the current model } return { ...message, content }; } return message; })]; const provider = MODEL_LIST.find((model) => model.name === currentModel)?.provider || DEFAULT_PROVIDER; //console.warn('streamText', getSystemPrompt()) return _streamText({ model: getModel(provider, currentModel, env), system: getSystemPrompt(), maxTokens: MAX_TOKENS, // headers: { //   'anthropic-beta': 'max-tokens-3-5-sonnet-2024-07-15', // }, messages: convertToCoreMessages(processedMessages), ...options, }); }`
> > * in the bolt configuration set the OPENAI_API_KEY to a random string and OPENAI_LIKE_BASE_URL to http://localhost:11434/v1 which is the local ollama instance
> > 
> > ![image](https://private-user-images.githubusercontent.com/35294825/381938115-b471369d-bba4-4351-91e5-7e7d40de9a8c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzOTIyODgsIm5iZiI6MTczMDM5MTk4OCwicGF0aCI6Ii8zNTI5NDgyNS8zODE5MzgxMTUtYjQ3MTM2OWQtYmJhNC00MzUxLTkxZTUtN2U3ZDQwZGU5YThjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMxVDE2MjYyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzYjE4NzQzMzQzNGExOTIxNTIwZWU5OTYwM2ZhYmE3ZmFmZjdiZjQzNzMzMjFhY2JhMzk2ZTU4ODM5NzdhOWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.bZ1-N1IrTQ6Uj2vPPgas5aNNvJ5-a-a25K_Ler50s9Q)
> 
> is it work with qwen 2.5 ?

Yes the 14b

**Comment by NotADeveloperAtAll** [comment]
> * in the stream-text.ts replace the streamText function with this code:
>       `export function streamText(messages: Messages, env: Env, options?: StreamingOptions) {
>       let currentModel = DEFAULT_MODEL;
>       const systemMessage = {
>       role: 'system',
>       content: getSystemPrompt()
>       };
>       const processedMessages = [systemMessage, ...messages.map((message) => {
>       if (message.role === 'user') {
>       const { model, content } = extractModelFromMessage(message);
>       if (model && MODEL_LIST.find((m) => m.name === model)) {
>       currentModel = model; // Update the current model
>       }
>       return { ...message, content };
>       }
>       return message;
>       })];
>       const provider = MODEL_LIST.find((model) => model.name === currentModel)?.provider || DEFAULT_PROVIDER;
>       //console.warn('streamText', getSystemPrompt())
>       return _streamText({
>       model: getModel(provider, currentModel, env),
>       system: getSystemPrompt(),
>       maxTokens: MAX_TOKENS,
>       // headers: {
>       //   'anthropic-beta': 'max-tokens-3-5-sonnet-2024-07-15',
>       // },
>       messages: convertToCoreMessages(processedMessages),
>       ...options,
>       });
>       }`
> 
>     * in the bolt configuration set the OPENAI_API_KEY to a random string and OPENAI_LIKE_BASE_URL to http://localhost:11434/v1 which is the local ollama instance
> 
> 
> ![image](https://private-user-images.githubusercontent.com/35294825/381938115-b471369d-bba4-4351-91e5-7e7d40de9a8c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0Nzk0NDYsIm5iZiI6MTczMDQ3OTE0NiwicGF0aCI6Ii8zNTI5NDgyNS8zODE5MzgxMTUtYjQ3MTM2OWQtYmJhNC00MzUxLTkxZTUtN2U3ZDQwZGU5YThjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAxVDE2MzkwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjOTFhOTZkZDgyMTlmMDRkMmQ3YjQ4MzhhNTdiZGNhN2FlNTUyYzg5OWM2NDkyY2RmMTU1OTZhZDA2NzNiZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-DQHgWI5DBfAesYZ-ilgXQiRAg8MO8zvP11X_Tx8A-A)

This fixes the code window but there is no preview.

**Comment by witzulu** [comment]
> es the code window but there is no preview.
seems to work for me but you can always type the commands in the terminal .

1. click terminal button above code preview
2. type commands that is shown in terminal e.g. npm run dev
