### ISSUE TITLE
Docker Build - Error: wrangler Cannot Resolve ../build/server During Bolt Build Process

### ISSUE THREAD

**Issue by 80Builder80** [coleam00/bolt.new-any-llm#79]
### Describe the bug

I encountered an error while attempting to build and run the bolt project with wrangler. The error message indicates that wrangler cannot resolve the ../build/server path in [[path]].ts, causing the build process to fail. I have verified that build/server/index.js exists, yet the issue persists both in Docker and on a local installation.

✘ [ERROR] Could not resolve "../build/server"

    [[path]].ts:5:29:
      5 │ import * as serverBuild from '../build/server';
        ╵                              ~~~~~~~~~~~~~~~~~

### Link to the Bolt URL that caused the error

localhost:5173 or 192.168.0.30:5173

### Steps to reproduce

Clone the Bolt repository to a local machine.
Run pnpm install in the project directory to install dependencies.
Copy .env.example to .env.local and update any necessary environment variables.
Build and run the application in Docker:

bash

sudo docker-compose up -d --build

Observe the error in the Docker logs.

### Expected behavior

The application should build and run successfully, with wrangler correctly resolving ../build/server and serving the application on the specified port.

### Platform

Server:
Distributor ID:	Ubuntu
Description:	Ubuntu 24.04.1 LTS
Release:	24.04
Codename:	noble
Docker version 27.3.1, build ce12230
node v20.15.1 (npm v10.7.0)
pnpm version 9.4.0
wrangler 3.63.2 (update available 3.83.0)

Local machine:
Distributor ID:	Ubuntu
Description:	Ubuntu 24.04.1 LTS
Release:	24.04
Codename:	noble
Docker version 24.0.5, build ced0996
node v20.15.1 (npm v10.7.0)
pnpm --version 9.4.0
wrangler 3.63.2 (update available 3.83.0)

### Additional context

I have attempted to install via docker on both my local server and local machine with the same error. The vite.config.ts file on the server has been modified to host 0.0.0.0 port 5173. The files on the local machine are unaltered. I have also confirmed that the program will run on my local machine and on my server on port 3000, outside of a docker container. However, I am having an issue in changing the port number to avoid conflicts. I am having to use pnpm run preview due to my processor Arm64 not being compatible with Chrome Canary.

**Comment by kemo1593** [comment]
I faced the same issue and after some research, someone said that it's a windows vs ubuntu thing, so he suggested something and it worked for me....
Head over to package.json file in the root folder, then to scripts and replace the line that starts with: "start" with the following;

"start": "wrangler pages dev ./build/client --binding OPEN_ROUTER_API_KEY=your actual api key here",

This part "OPEN_ROUTER_API_KEY" you can change according to the API you're using in the .env.local file

**Comment by 80Builder80** [comment]
Thank you @kemo1593 Your suggestion did not solve the issue. But it did put me on the right track to find my stupid mistake. When attempting to change the port, apparently I did not save the docker-compose.yml file correctly. I also did not change my Dockerfile to pnpm run preview. It is now working on my server inside a docker container.

I did not need to alter my package.json file to get this to work.
Changes:
sudo nano docker-compose.yml:
ports:
      - "5173:3000"
sudo nano Dockerfile:
# Start the application
CMD ["pnpm", "run", "preview"]

Now I am running Bolt.New-any-llm on my Ubuntu Arm64 server on port 5173 and bypassing the Ubuntu/Canary issue by running in preview mode. Now on to the new issue I discovered.
