### ISSUE TITLE
Enhance Prompt using Anthropic Claude Sonnet instead of Chose Model and Provider

### ISSUE THREAD

**Issue by karrot0** [coleam00/bolt.new-any-llm#91]
### Describe the bug

So I wanted to enhance my prompt using Google Gemini 1.5 Pro, When I click on the enhance button. It didn't work and reloaded the site. When I looked at the code and added some debugging, I found the app is using the default Anthropic Claude Sonnet model which I don't have the api key for. 
![image](https://github.com/user-attachments/assets/31e0a3e2-3bba-4d9e-802a-ec8233bae4b0)

### Link to the Bolt URL that caused the error

http://localhost:5173

### Steps to reproduce

1. Go to web app
2. Type in a basic prompt for whatever webapp
3. Click the enhance prompt button

### Expected behavior

If you don't have an Anthropic Key than it is expected to use the Anthropic Model causing it to not enhance your prompt, but delete it instead.

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/31e0a3e2-3bba-4d9e-802a-ec8233bae4b0)

### Platform

- OS: Windows
- Browser: Chrome
- Version: idk

**Comment by chrismahoney** [comment]
> Being able to choose 2 different models would be great. i.e., coder model for the tasks and general model for prompt enhancement.

I would suggest this become its own enhancement request, as I'd expect it to be a popular one.

My suggestion for _this_ issue would be to frame it as the ability to dynamically allow prompt enhancement independent of Sonnet; I have seen it work once with a similar model at some point with some minor syntax issues.

**Comment by robonxt-ai** [comment]
Would it be a better idea to use whatever LLM that was also selected for the coder, at least for now?
